// SPDX-FileCopyrightText: 2026 Koivisto Capital Oy
// SPDX-License-Identifier: EUPL-1.2

package dev.vertique.examples.sse;

import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertNotNull;

import dev.vertique.application.test.VertiqueAppExtension;
import io.restassured.RestAssured;
import io.restassured.filter.log.RequestLoggingFilter;
import io.restassured.filter.log.ResponseLoggingFilter;
import io.restassured.response.Response;
import io.vertx.core.json.JsonObject;
import java.util.concurrent.TimeUnit;
import org.junit.jupiter.api.AfterAll;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.Timeout;
import org.junit.jupiter.api.extension.RegisterExtension;

/**
 * Black-box integration test for the job-creation endpoint that the SSE feed is subscribed against.
 *
 * <p>Boots the application via {@link VertiqueAppExtension} (using the factory generated by the
 * {@code @VertiqueApp} annotation processor) with the same tight configuration the feed test uses,
 * and verifies only that {@code POST /jobs} answers with a usable job identifier.
 *
 * <p>The exchange is a single buffered request/response, so it is issued with RestAssured and needs
 * no HTTP client of its own. It lives here rather than alongside the SSE feed tests in
 * {@code SseJobProgressIT} because that class claims the raw {@code HttpClient} exemption for
 * incremental stream consumption, and a test that never consumes a stream must not ride along on
 * that exemption.
 */
@Timeout(value = 20, unit = TimeUnit.SECONDS)
public class JobCreationIT {

    @RegisterExtension
    static final VertiqueAppExtension app = VertiqueAppExtension.forFactory(new AppComponentVertiqueComponentFactory())
            .withConfig(new JsonObject()
                    .put("http", new JsonObject().put("port", 0).put("host", "127.0.0.1"))
                    .put("management", new JsonObject().put("enabled", false))
                    .put("job", new JsonObject().put("stepIntervalMs", 20).put("stepCount", 4)));

    @BeforeAll
    static void setUp() {
        RestAssured.baseURI = "http://127.0.0.1";
        RestAssured.port = app.httpPort();
        RestAssured.filters(new RequestLoggingFilter(), new ResponseLoggingFilter());
    }

    @AfterAll
    static void tearDown() {
        RestAssured.reset();
    }

    @Test
    @DisplayName("POST /jobs creates a job and returns an id")
    void createJobReturnsId() {
        Response response = RestAssured.given()
                .contentType("application/json")
                .when()
                .post("/jobs")
                .then()
                .statusCode(200)
                .contentType("application/json")
                .extract()
                .response();

        String id = response.jsonPath().getString("id");
        assertNotNull(id, "Job id should be present");
        assertFalse(id.isBlank(), "Job id should not be blank");
    }
}
