// SPDX-FileCopyrightText: 2026 Koivisto Capital Oy
// SPDX-License-Identifier: EUPL-1.2

package dev.vertique.examples.sse;

import static org.junit.jupiter.api.Assertions.*;

import dev.vertique.application.test.VertiqueAppExtension;
import io.restassured.RestAssured;
import io.restassured.filter.log.RequestLoggingFilter;
import io.restassured.filter.log.ResponseLoggingFilter;
import io.restassured.response.Response;
import io.vertx.core.buffer.Buffer;
import io.vertx.core.http.HttpClient;
import io.vertx.core.http.HttpMethod;
import io.vertx.core.http.RequestOptions;
import io.vertx.core.json.JsonObject;
import io.vertx.junit5.VertxExtension;
import io.vertx.junit5.VertxTestContext;
import java.util.ArrayList;
import java.util.List;
import java.util.concurrent.TimeUnit;
import org.junit.jupiter.api.*;
import org.junit.jupiter.api.extension.ExtendWith;
import org.junit.jupiter.api.extension.RegisterExtension;

/**
 * Black-box integration test for the SSE job progress feed.
 *
 * <p>Boots the application via {@link VertiqueAppExtension} (using the factory generated by the
 * {@code @VertiqueApp} annotation processor) with a tight configuration (fast steps, random port)
 * and verifies the SSE wire protocol: progress frames, terminal complete frame, stream close, and
 * Last-Event-ID replay filtering.
 */
@Timeout(value = 20, unit = TimeUnit.SECONDS)
@ExtendWith(VertxExtension.class)
public class SseJobProgressIT {

    @RegisterExtension
    static final VertiqueAppExtension app = VertiqueAppExtension.forFactory(new AppComponentVertiqueComponentFactory())
            .withConfig(new JsonObject()
                    .put("http", new JsonObject().put("port", 0))
                    .put("management", new JsonObject().put("enabled", false))
                    .put("job", new JsonObject().put("stepIntervalMs", 20).put("stepCount", 4)));

    private static HttpClient httpClient;

    @BeforeAll
    static void setUp() {
        httpClient = app.vertx().createHttpClient();
        RestAssured.baseURI = "http://localhost";
        RestAssured.port = app.httpPort();
        RestAssured.filters(new RequestLoggingFilter(), new ResponseLoggingFilter());
    }

    @AfterAll
    static void tearDown() {
        if (httpClient != null) {
            httpClient.close();
        }
        RestAssured.reset();
    }

    @Test
    @DisplayName("POST /jobs creates a job and returns an id")
    void createJobReturnsId() {
        Response response = RestAssured.given()
                .contentType("application/json")
                .when()
                .post("/jobs")
                .then()
                .statusCode(200)
                .contentType("application/json")
                .extract()
                .response();

        String id = response.jsonPath().getString("id");
        assertNotNull(id, "Job id should be present");
        assertFalse(id.isBlank(), "Job id should not be blank");
    }

    @Test
    @DisplayName("GET /jobs/{id}/events streams progress frames then a complete frame and closes")
    void sseStreamProgressAndComplete(VertxTestContext ctx) throws Exception {
        // Create a job first
        String jobId = RestAssured.given()
                .contentType("application/json")
                .when()
                .post("/jobs")
                .then()
                .statusCode(200)
                .extract()
                .jsonPath()
                .getString("id");

        Buffer accumulated = Buffer.buffer();
        List<SseFrame> frames = new ArrayList<>();

        RequestOptions opts = new RequestOptions()
                .setHost("localhost")
                .setPort(app.httpPort())
                .setMethod(HttpMethod.GET)
                .setURI("/jobs/" + jobId + "/events");

        httpClient.request(opts).compose(req -> req.send()).onComplete(ctx.succeeding(response -> {
            response.handler(chunk -> accumulated.appendBuffer(chunk));
            response.endHandler(v -> {
                ctx.verify(() -> {
                    frames.addAll(parseSseFrames(accumulated.toString()));

                    List<SseFrame> progressFrames = frames.stream()
                            .filter(f -> "progress".equals(f.event()))
                            .toList();
                    List<SseFrame> completeFrames = frames.stream()
                            .filter(f -> "complete".equals(f.event()))
                            .toList();

                    assertTrue(
                            progressFrames.size() >= 3, "Expected >=3 progress frames, got: " + progressFrames.size());
                    assertFalse(completeFrames.isEmpty(), "Expected a complete frame");

                    // Check monotonically increasing ids in progress frames
                    int lastId = -1;
                    for (SseFrame frame : progressFrames) {
                        int id = Integer.parseInt(frame.id());
                        assertTrue(id > lastId, "ids should be monotonically increasing");
                        lastId = id;
                    }

                    // Complete frame should come after progress frames
                    int completeIndex = frames.indexOf(completeFrames.get(0));
                    int lastProgressIndex = frames.lastIndexOf(progressFrames.get(progressFrames.size() - 1));
                    assertTrue(completeIndex > lastProgressIndex, "complete frame should follow last progress frame");
                });
                ctx.completeNow();
            });
            response.exceptionHandler(ctx::failNow);
        }));
    }

    @Test
    @DisplayName("Reconnect with Last-Event-ID skips replayed events with id <= header value")
    void reconnectWithLastEventIdSkipsReplayedEvents(VertxTestContext ctx) throws Exception {
        // Create and let the job complete first
        String jobId = RestAssured.given()
                .contentType("application/json")
                .when()
                .post("/jobs")
                .then()
                .statusCode(200)
                .extract()
                .jsonPath()
                .getString("id");

        // First subscription — collect all frames
        Buffer firstAccumulated = Buffer.buffer();
        RequestOptions firstOpts = new RequestOptions()
                .setHost("localhost")
                .setPort(app.httpPort())
                .setMethod(HttpMethod.GET)
                .setURI("/jobs/" + jobId + "/events");

        httpClient.request(firstOpts).compose(req -> req.send()).onComplete(ctx.succeeding(firstResponse -> {
            firstResponse.handler(chunk -> firstAccumulated.appendBuffer(chunk));
            firstResponse.endHandler(v -> {
                List<SseFrame> firstFrames = parseSseFrames(firstAccumulated.toString());
                List<SseFrame> progressFrames = firstFrames.stream()
                        .filter(f -> "progress".equals(f.event()))
                        .toList();

                if (progressFrames.size() < 2) {
                    ctx.failNow(new AssertionError("Need at least 2 progress frames for replay test"));
                    return;
                }

                String lastEventId = "1"; // skip seq <= 1

                // Reconnect with Last-Event-ID: 1
                Buffer secondAccumulated = Buffer.buffer();
                RequestOptions secondOpts = new RequestOptions()
                        .setHost("localhost")
                        .setPort(app.httpPort())
                        .setMethod(HttpMethod.GET)
                        .setURI("/jobs/" + jobId + "/events")
                        .addHeader("Last-Event-ID", lastEventId);

                httpClient.request(secondOpts).compose(req -> req.send()).onComplete(ctx.succeeding(secondResponse -> {
                    secondResponse.handler(chunk -> secondAccumulated.appendBuffer(chunk));
                    secondResponse.endHandler(v2 -> {
                        ctx.verify(() -> {
                            List<SseFrame> secondFrames = parseSseFrames(secondAccumulated.toString());
                            // No replayed frame should have id <= 1
                            for (SseFrame frame : secondFrames) {
                                if (frame.id() != null && !frame.id().isBlank()) {
                                    assertTrue(
                                            Integer.parseInt(frame.id()) > 1,
                                            "Replayed frame should have id > 1 but got: " + frame.id());
                                }
                            }
                        });
                        ctx.completeNow();
                    });
                    secondResponse.exceptionHandler(ctx::failNow);
                }));
            });
            firstResponse.exceptionHandler(ctx::failNow);
        }));
    }

    // --- SSE frame parser ---

    /**
     * Parses an SSE byte stream into a list of frames.
     *
     * <p>Each frame is delimited by a blank line ({@code \n\n} or {@code \r\n\r\n}). Lines within
     * a frame may be {@code id:}, {@code event:}, or {@code data:} fields.
     *
     * @param raw the raw SSE response body as a string
     * @return ordered list of parsed frames; never {@code null}
     */
    static List<SseFrame> parseSseFrames(String raw) {
        List<SseFrame> result = new ArrayList<>();
        String[] blocks = raw.split("\n\n|\r\n\r\n");
        for (String block : blocks) {
            if (block.isBlank()) {
                continue;
            }
            String id = null;
            String event = null;
            StringBuilder data = new StringBuilder();
            for (String line : block.split("\n|\r\n")) {
                if (line.startsWith("id:")) {
                    id = line.substring(3).strip();
                } else if (line.startsWith("event:")) {
                    event = line.substring(6).strip();
                } else if (line.startsWith("data:")) {
                    if (data.length() > 0) {
                        data.append('\n');
                    }
                    data.append(line.substring(5).strip());
                }
            }
            if (event != null || data.length() > 0) {
                result.add(new SseFrame(id, event, data.toString()));
            }
        }
        return result;
    }

    /**
     * Minimal representation of a parsed SSE frame.
     *
     * @param id    the {@code id:} field value, or {@code null} if absent
     * @param event the {@code event:} field value, or {@code null} if absent
     * @param data  the {@code data:} field value(s), concatenated with newlines
     */
    record SseFrame(String id, String event, String data) {}
}
