// SPDX-FileCopyrightText: 2026 Koivisto Capital Oy
// SPDX-License-Identifier: EUPL-1.2

package dev.vertique.workflow.registry;

/**
 * Strongly-typed wrapper for a callback identifier used to look up registered functions in the
 * {@link WorkflowCallbackRegistry}.
 *
 * <p>Callback ids are allocated by {@link WorkflowBuilder} when the DSL registers executable Java
 * functions (e.g., payload factories, state updaters, decision resolvers). The id is then stored
 * in the serialization-friendly {@link dev.vertique.workflow.plan.WorkflowPlan} instead of the
 * function itself.
 *
 * @param value the underlying string identifier; generated by the builder and opaque to callers
 */
public record CallbackId(String value) {}
