// SPDX-FileCopyrightText: 2026 Koivisto Capital Oy
// SPDX-License-Identifier: EUPL-1.2

package dev.vertique.mcp.server.runtime;

import static org.assertj.core.api.Assertions.assertThat;

import com.fasterxml.jackson.annotation.JsonSubTypes;
import com.fasterxml.jackson.annotation.JsonTypeInfo;
import com.fasterxml.jackson.annotation.JsonUnwrapped;
import dev.vertique.core.json.JsonMapperProfile;
import dev.vertique.core.json.JsonProfileId;
import dev.vertique.json.DefaultJsonMapperProfileRegistry;
import dev.vertique.json.schema.AnnotationJsonSchemaGenerator;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.io.InputStream;
import java.nio.charset.StandardCharsets;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import java.util.Set;
import java.util.stream.Stream;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.MethodSource;

/**
 * T005 TP-002 — the hardened output of every annotation family the design proof's path probe
 * exercised is pinned against the hardener as it stood at T005's parent commit.
 *
 * <p>FR-014 narrows the closure rule to objects that carry no {@code additionalProperties} member of
 * their own. Today no Swagger or Jackson annotation on any of these shapes makes the generator emit
 * such a member for an object that also declares {@code properties} (design proof v2, § Opener: "No
 * Swagger or Jackson annotation opened anything"), so the narrowed rule must produce exactly the
 * pre-change document for every one of them. A schema-library or Swagger upgrade that starts emitting
 * an {@code additionalProperties} member for one of these shapes would open an object the old
 * hardener closed, and this proof is what fails.
 *
 * <p>The golden files under {@code src/test/resources/hardened-annotation-shapes/} were written from
 * the hardener at T005's parent commit, before the change, and are never regenerated by this test.
 * None of these types declares an any-setter: the shapes FR-015 deliberately opens are proven by
 * {@code McpToolInputShapesIT}, not here.
 */
@DisplayName("MCP hardened annotation shapes — T005 TP-002")
class McpHardenedAnnotationShapesTest {

    /** The profile every shape is generated under: the resolver's unconfigured tail (issue #440). */
    private static final JsonProfileId PROFILE_ID = JsonProfileId.of("vertique");

    /** The classpath directory holding one golden hardened document per shape. */
    static final String GOLDEN_DIRECTORY = "hardened-annotation-shapes";

    /** One entry per annotation family, named for it; the name is also the golden file's base name. */
    static Stream<AnnotationShape> annotationShapes() {
        return Stream.of(
                new AnnotationShape("class-level-additional-properties-true", ClassLevelTrue.class),
                new AnnotationShape("class-level-additional-properties-false", ClassLevelFalse.class),
                new AnnotationShape("member-level-additional-properties-true", MemberLevelTrue.class),
                new AnnotationShape("member-level-additional-properties-false", MemberLevelFalse.class),
                new AnnotationShape("getter-level-additional-properties-true", GetterLevelTrue.class),
                new AnnotationShape("getter-level-additional-properties-false", GetterLevelFalse.class),
                new AnnotationShape("class-level-additional-properties-schema", ClassLevelSchema.class),
                new AnnotationShape("json-type-info-base", TypedBaseHolder.class),
                new AnnotationShape("json-unwrapped", UnwrappedHolder.class),
                new AnnotationShape("record", RecordShape.class),
                new AnnotationShape("optional-of-dto", OptionalHolder.class),
                new AnnotationShape("generic-box-of-dto", GenericBoxHolder.class));
    }

    @ParameterizedTest(name = "{0}")
    @MethodSource("annotationShapes")
    @DisplayName("hardens each annotation shape exactly as the pre-change hardener did")
    void annotationShapesHardenAsBeforeTheChange(AnnotationShape shape) throws IOException {
        String hardened = hardenedDocumentFor(shape.type());

        assertThat(hardened)
                .as("the hardened document for the '" + shape.name() + "' shape must be byte-identical to the "
                        + "document the hardener at T005's parent produced; a difference means the narrowed "
                        + "closure rule changed a shape that declares no additionalProperties of its own, or "
                        + "that the schema library started emitting one for it")
                .isEqualTo(golden(shape.name()));
    }

    /** Generates one type through {@code forInputProfile} and hardens it, exactly as composition does. */
    static String hardenedDocumentFor(Class<?> type) {
        JsonMapperProfile profile = new DefaultJsonMapperProfileRegistry(Set.of()).profile(PROFILE_ID);
        String generated =
                AnnotationJsonSchemaGenerator.forInputProfile(profile).generateCanonical(type);
        return McpCanonicalJsonWriter.writeCanonical(
                McpSchemaHardener.harden(McpCanonicalJsonWriter.read(generated), List.of()));
    }

    /** Reads one pinned golden document from the test classpath. */
    private static String golden(String shapeName) throws IOException {
        String resource = GOLDEN_DIRECTORY + "/" + shapeName + ".json";
        try (InputStream stream =
                McpHardenedAnnotationShapesTest.class.getClassLoader().getResourceAsStream(resource)) {
            assertThat(stream)
                    .as("the golden document " + resource + " must exist; it is written once, from the "
                            + "hardener at T005's parent, and never regenerated")
                    .isNotNull();
            return new String(stream.readAllBytes(), StandardCharsets.UTF_8).strip();
        }
    }

    /** One named annotation family and the Java type that carries it. */
    record AnnotationShape(String name, Class<?> type) {
        @Override
        public String toString() {
            return name;
        }
    }

    // --- Shapes: one per annotation family the design proof's path probe exercised ---

    /** A plain DTO reused as a nested type, a schema value, and a box element. */
    static final class Detail {

        /** An ordinary property. */
        public String label;
    }

    /** Class-level Swagger {@code additionalProperties = TRUE}. */
    @Schema(additionalProperties = Schema.AdditionalPropertiesValue.TRUE)
    static final class ClassLevelTrue {

        /** An ordinary property, so the type is a closure candidate. */
        public String name;
    }

    /** Class-level Swagger {@code additionalProperties = FALSE}. */
    @Schema(additionalProperties = Schema.AdditionalPropertiesValue.FALSE)
    static final class ClassLevelFalse {

        /** An ordinary property. */
        public String name;
    }

    /** Member-level Swagger {@code additionalProperties = TRUE} on a map-valued field. */
    static final class MemberLevelTrue {

        /** An ordinary property. */
        public String name;

        /** The annotated member. */
        @Schema(additionalProperties = Schema.AdditionalPropertiesValue.TRUE)
        public Map<String, String> attributes = new LinkedHashMap<>();
    }

    /** Member-level Swagger {@code additionalProperties = FALSE} on a map-valued field. */
    static final class MemberLevelFalse {

        /** An ordinary property. */
        public String name;

        /** The annotated member. */
        @Schema(additionalProperties = Schema.AdditionalPropertiesValue.FALSE)
        public Map<String, String> attributes = new LinkedHashMap<>();
    }

    /** Getter-level Swagger {@code additionalProperties = TRUE}. */
    static final class GetterLevelTrue {

        private Map<String, String> attributes = new LinkedHashMap<>();

        /**
         * Returns the annotated map property.
         *
         * @return the attributes
         */
        @Schema(additionalProperties = Schema.AdditionalPropertiesValue.TRUE)
        public Map<String, String> getAttributes() {
            return attributes;
        }

        /**
         * Sets the annotated map property.
         *
         * @param attributes the attributes
         */
        public void setAttributes(Map<String, String> attributes) {
            this.attributes = attributes;
        }
    }

    /** Getter-level Swagger {@code additionalProperties = FALSE}. */
    static final class GetterLevelFalse {

        private Map<String, String> attributes = new LinkedHashMap<>();

        /**
         * Returns the annotated map property.
         *
         * @return the attributes
         */
        @Schema(additionalProperties = Schema.AdditionalPropertiesValue.FALSE)
        public Map<String, String> getAttributes() {
            return attributes;
        }

        /**
         * Sets the annotated map property.
         *
         * @param attributes the attributes
         */
        public void setAttributes(Map<String, String> attributes) {
            this.attributes = attributes;
        }
    }

    /** Class-level Swagger {@code additionalPropertiesSchema}. */
    @Schema(additionalPropertiesSchema = Detail.class)
    static final class ClassLevelSchema {

        /** An ordinary property. */
        public String name;
    }

    /** A holder of a {@code @JsonTypeInfo} base with one declared subtype. */
    static final class TypedBaseHolder {

        /** The polymorphic member. */
        public Shape shape;
    }

    /** The polymorphic base. */
    @JsonTypeInfo(use = JsonTypeInfo.Id.NAME, include = JsonTypeInfo.As.PROPERTY, property = "kind")
    @JsonSubTypes({@JsonSubTypes.Type(value = Circle.class, name = "circle")})
    interface Shape {}

    /** The one declared subtype. */
    static final class Circle implements Shape {

        /** An ordinary property. */
        public int radius;
    }

    /** A type with a {@code @JsonUnwrapped} member. */
    static final class UnwrappedHolder {

        /** An ordinary property. */
        public String name;

        /** The unwrapped member, whose properties are flattened into this type's own. */
        @JsonUnwrapped
        public Detail detail;
    }

    /** A record. */
    record RecordShape(String city, int zip) {}

    /** A holder of an {@code Optional} of a DTO. */
    static final class OptionalHolder {

        /** The optional member. */
        public Optional<Detail> detail = Optional.empty();
    }

    /** A holder of a generic box parameterized with a DTO. */
    static final class GenericBoxHolder {

        /** The boxed member. */
        public Box<Detail> box;
    }

    /** A generic box.
     *
     * @param <T> the boxed type
     */
    static final class Box<T> {

        /** The boxed value. */
        public T value;
    }
}
