// SPDX-FileCopyrightText: 2026 Koivisto Capital Oy
// SPDX-License-Identifier: EUPL-1.2

package dev.vertique.mcp.server.runtime;

import static org.assertj.core.api.Assertions.assertThat;

import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonSubTypes;
import com.fasterxml.jackson.annotation.JsonTypeInfo;
import com.fasterxml.jackson.annotation.JsonUnwrapped;
import dev.vertique.core.json.JsonMapperProfile;
import dev.vertique.core.json.JsonProfileId;
import dev.vertique.json.DefaultJsonMapperProfileRegistry;
import dev.vertique.json.schema.AnnotationJsonSchemaGenerator;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.io.InputStream;
import java.lang.reflect.ParameterizedType;
import java.lang.reflect.Type;
import java.nio.charset.StandardCharsets;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import java.util.Set;
import java.util.stream.Stream;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.MethodSource;

/**
 * T005 TP-002 — the hardened output of every annotation family the design proof's path probe
 * exercised is pinned against the hardener as it stood at T005's parent commit.
 *
 * <p>FR-014 narrows the closure rule to objects that carry no {@code additionalProperties} member of
 * their own. Today no Swagger or Jackson annotation on any of these shapes makes the generator emit
 * such a member for an object that also declares {@code properties} (design proof v2, § Opener: "No
 * Swagger or Jackson annotation opened anything"), so the narrowed rule must produce exactly the
 * pre-change document for every one of them. A schema-library or Swagger upgrade that starts emitting
 * an {@code additionalProperties} member for one of these shapes would open an object the old
 * hardener closed, and this proof is what fails.
 *
 * <p>The golden files under {@code src/test/resources/hardened-annotation-shapes/} were written from
 * the hardener at T005's parent commit, before the change, and are never regenerated by this test.
 * The nested goldens and the three any-setter shapes were written from the hardener at T010's parent
 * commit {@code 247b0ca5}, which is byte-identical to T005's for this class.
 *
 * <p>Each shape is pinned in two positions (AC-014.2, as round 10 strengthens it). The three
 * any-setter shapes {@link #narrowingSensitivityShapes()} adds are not AC-014.2 families; they exist
 * because none of the twelve can fail for the narrowed closure rule. What those shapes accept at the
 * tool boundary is still proven by {@code McpToolInputShapesIT}, not here: this class pins document
 * bytes only.
 */
@DisplayName("MCP hardened annotation shapes — T005 TP-002")
class McpHardenedAnnotationShapesTest {

    /** The profile every shape is generated under: the resolver's unconfigured tail (issue #440). */
    private static final JsonProfileId PROFILE_ID = JsonProfileId.of("vertique");

    /** The classpath directory holding one golden hardened document per shape. */
    static final String GOLDEN_DIRECTORY = "hardened-annotation-shapes";

    /** The twelve annotation families, each named for its golden file's base name. */
    private static Stream<AnnotationFamily> annotationFamilies() {
        return Stream.of(
                new AnnotationFamily("class-level-additional-properties-true", ClassLevelTrue.class),
                new AnnotationFamily("class-level-additional-properties-false", ClassLevelFalse.class),
                new AnnotationFamily("member-level-additional-properties-true", MemberLevelTrue.class),
                new AnnotationFamily("member-level-additional-properties-false", MemberLevelFalse.class),
                new AnnotationFamily("getter-level-additional-properties-true", GetterLevelTrue.class),
                new AnnotationFamily("getter-level-additional-properties-false", GetterLevelFalse.class),
                new AnnotationFamily("class-level-additional-properties-schema", ClassLevelSchema.class),
                new AnnotationFamily("json-type-info-base", TypedBaseHolder.class),
                new AnnotationFamily("json-unwrapped", UnwrappedHolder.class),
                new AnnotationFamily("record", RecordShape.class),
                new AnnotationFamily("optional-of-dto", OptionalHolder.class),
                new AnnotationFamily("generic-box-of-dto", GenericBoxHolder.class));
    }

    /**
     * One entry per annotation family <em>and position</em> (AC-014.2, as round 10 strengthens it).
     *
     * <p>The root position is the existing one, where the hardener closes unconditionally by
     * provenance, so it cannot fail for the narrowed closure rule this proof exists to guard. The
     * nested position puts each shape under a property of a holder type, which is the only position
     * where that rule decides anything: there a shape declaring an {@code additionalProperties} member
     * of its own — {@code true}, {@code false}, or a schema — must keep what it declares.
     */
    static Stream<AnnotationShape> annotationShapes() {
        return Stream.concat(annotationFamilies(), narrowingSensitivityShapes())
                .flatMap(family -> Stream.of(
                        new AnnotationShape(family.name(), family.type()),
                        new AnnotationShape(family.name() + "-nested", nestedIn(family.type()))));
    }

    /**
     * Three shapes beyond AC-014.2's twelve families, added because the twelve cannot fail for the
     * rule this proof guards.
     *
     * <p>FR-014 narrows the non-root closure to objects carrying no {@code additionalProperties}
     * member of their own: a declared schema, {@code true}, or {@code false} is never overwritten. Of
     * the twelve families only {@code class-level-additional-properties-false} declares such a member
     * at a non-root position, and it declares {@code false} — exactly what closing would write — so
     * dropping the narrowing changes no byte of any of the twenty-four rows. It was measured: the
     * narrowing mutation left all twenty-four green.
     *
     * <p>These three declare a non-{@code false} member instead, so overwriting one is visible:
     *
     * <ul>
     *   <li>an any-setter over a typed value, which FR-015 describes as {@code additionalProperties:
     *       {"type":"string"}} — the schema case, and the shape the package itself now emits;
     *   <li>an any-setter over {@code Object}, described as the empty schema {@code {}};
     *   <li>the same typed any-setter under a class-level Swagger {@code additionalProperties = TRUE},
     *       which pins the measured answer to "is there a shape declaring {@code true}?": there is
     *       none. FR-015's extras description takes precedence, so the generator emits the extras
     *       schema and never the boolean. No annotation route reaches {@code true}; the member-level
     *       and getter-level {@code TRUE} attributes and a raw {@code Map} property emit no {@code
     *       additionalProperties} member at all.
     * </ul>
     *
     * <p>Their root rows pin the other half of FR-014: the root carrier is closed unconditionally by
     * provenance, so a declared extras schema at the root <em>is</em> overwritten with {@code false}.
     */
    private static Stream<AnnotationFamily> narrowingSensitivityShapes() {
        return Stream.of(
                new AnnotationFamily("any-setter-typed-extras", TypedExtrasAnySetter.class),
                new AnnotationFamily("any-setter-object-extras", ObjectExtrasAnySetter.class),
                new AnnotationFamily("class-level-true-with-any-setter", ClassLevelTrueWithAnySetter.class));
    }

    @ParameterizedTest(name = "{0}")
    @MethodSource("annotationShapes")
    @DisplayName("hardens each annotation shape exactly as the pre-change hardener did")
    void annotationShapesHardenAsBeforeTheChange(AnnotationShape shape) throws IOException {
        String hardened = hardenedDocumentFor(shape.type());

        assertThat(hardened)
                .as("the hardened document for the '" + shape.name() + "' shape must be byte-identical to the "
                        + "document the hardener at its golden's parent produced; a difference means the "
                        + "narrowed closure rule changed a shape that declares no additionalProperties of its "
                        + "own, or that the schema library started emitting one for it")
                .isEqualTo(golden(shape.name()));
    }

    /**
     * The nested position of one shape: {@code NestedShapeHolder<shape>}, whose {@code nested} property
     * carries the shape as a non-root object.
     *
     * @param shapeType the annotation family's own type
     * @return the parameterized holder type
     */
    private static Type nestedIn(Class<?> shapeType) {
        return new ParameterizedType() {
            @Override
            public Type[] getActualTypeArguments() {
                return new Type[] {shapeType};
            }

            @Override
            public Type getRawType() {
                return NestedShapeHolder.class;
            }

            @Override
            public Type getOwnerType() {
                return null;
            }

            @Override
            public String toString() {
                return NestedShapeHolder.class.getSimpleName() + "<" + shapeType.getSimpleName() + ">";
            }
        };
    }

    /**
     * The holder that puts a shape in the hardener's non-root branch.
     *
     * @param <T> the nested shape
     */
    static final class NestedShapeHolder<T> {

        /** The nested position under test. */
        public T nested;

        /** An ordinary property, so the holder itself is a closure candidate like any carrier. */
        public String label;
    }

    /** One named annotation family and the Java type that carries it. */
    private record AnnotationFamily(String name, Class<?> type) {}

    /** Generates one type through {@code forInputProfile} and hardens it, exactly as composition does. */
    static String hardenedDocumentFor(Type type) {
        JsonMapperProfile profile = new DefaultJsonMapperProfileRegistry(Set.of()).profile(PROFILE_ID);
        String generated =
                AnnotationJsonSchemaGenerator.forInputProfile(profile).generateCanonical(type);
        return McpCanonicalJsonWriter.writeCanonical(
                McpSchemaHardener.harden(McpCanonicalJsonWriter.read(generated), List.of()));
    }

    /** Reads one pinned golden document from the test classpath. */
    private static String golden(String shapeName) throws IOException {
        String resource = GOLDEN_DIRECTORY + "/" + shapeName + ".json";
        try (InputStream stream =
                McpHardenedAnnotationShapesTest.class.getClassLoader().getResourceAsStream(resource)) {
            assertThat(stream)
                    .as("the golden document " + resource + " must exist; it is written once, from the "
                            + "hardener at T005's parent, and never regenerated")
                    .isNotNull();
            return new String(stream.readAllBytes(), StandardCharsets.UTF_8).strip();
        }
    }

    /** One named annotation family in one position, and the Java type that realizes it there. */
    record AnnotationShape(String name, Type type) {
        @Override
        public String toString() {
            return name;
        }
    }

    // --- Shapes: one per annotation family the design proof's path probe exercised ---

    /**
     * An any-setter over a typed value: FR-015 describes its extras as {@code additionalProperties:
     * {"type":"string"}}, a declared schema beside non-empty {@code properties}, which is the case the
     * narrowed closure rule exists for.
     */
    static final class TypedExtrasAnySetter {

        /** An ordinary property, so the object is a closure candidate. */
        public String name;

        /** The typed extras the description must survive hardening. */
        @JsonAnySetter
        public Map<String, String> extras = new LinkedHashMap<>();
    }

    /** An any-setter over {@code Object}, whose unconstrained value type is the empty schema. */
    static final class ObjectExtrasAnySetter {

        /** An ordinary property. */
        public String name;

        /** The unconstrained extras. */
        @JsonAnySetter
        public Map<String, Object> extras = new LinkedHashMap<>();
    }

    /**
     * The typed any-setter under a class-level Swagger {@code additionalProperties = TRUE}, which
     * pins that the generator emits the extras description rather than the boolean: there is no
     * annotation shape whose document declares {@code additionalProperties: true}.
     */
    @Schema(additionalProperties = Schema.AdditionalPropertiesValue.TRUE)
    static final class ClassLevelTrueWithAnySetter {

        /** An ordinary property. */
        public String name;

        /** The typed extras, which take precedence over the class-level attribute. */
        @JsonAnySetter
        public Map<String, String> extras = new LinkedHashMap<>();
    }

    /** A plain DTO reused as a nested type, a schema value, and a box element. */
    static final class Detail {

        /** An ordinary property. */
        public String label;
    }

    /** Class-level Swagger {@code additionalProperties = TRUE}. */
    @Schema(additionalProperties = Schema.AdditionalPropertiesValue.TRUE)
    static final class ClassLevelTrue {

        /** An ordinary property, so the type is a closure candidate. */
        public String name;
    }

    /** Class-level Swagger {@code additionalProperties = FALSE}. */
    @Schema(additionalProperties = Schema.AdditionalPropertiesValue.FALSE)
    static final class ClassLevelFalse {

        /** An ordinary property. */
        public String name;
    }

    /** Member-level Swagger {@code additionalProperties = TRUE} on a map-valued field. */
    static final class MemberLevelTrue {

        /** An ordinary property. */
        public String name;

        /** The annotated member. */
        @Schema(additionalProperties = Schema.AdditionalPropertiesValue.TRUE)
        public Map<String, String> attributes = new LinkedHashMap<>();
    }

    /** Member-level Swagger {@code additionalProperties = FALSE} on a map-valued field. */
    static final class MemberLevelFalse {

        /** An ordinary property. */
        public String name;

        /** The annotated member. */
        @Schema(additionalProperties = Schema.AdditionalPropertiesValue.FALSE)
        public Map<String, String> attributes = new LinkedHashMap<>();
    }

    /** Getter-level Swagger {@code additionalProperties = TRUE}. */
    static final class GetterLevelTrue {

        private Map<String, String> attributes = new LinkedHashMap<>();

        /**
         * Returns the annotated map property.
         *
         * @return the attributes
         */
        @Schema(additionalProperties = Schema.AdditionalPropertiesValue.TRUE)
        public Map<String, String> getAttributes() {
            return attributes;
        }

        /**
         * Sets the annotated map property.
         *
         * @param attributes the attributes
         */
        public void setAttributes(Map<String, String> attributes) {
            this.attributes = attributes;
        }
    }

    /** Getter-level Swagger {@code additionalProperties = FALSE}. */
    static final class GetterLevelFalse {

        private Map<String, String> attributes = new LinkedHashMap<>();

        /**
         * Returns the annotated map property.
         *
         * @return the attributes
         */
        @Schema(additionalProperties = Schema.AdditionalPropertiesValue.FALSE)
        public Map<String, String> getAttributes() {
            return attributes;
        }

        /**
         * Sets the annotated map property.
         *
         * @param attributes the attributes
         */
        public void setAttributes(Map<String, String> attributes) {
            this.attributes = attributes;
        }
    }

    /** Class-level Swagger {@code additionalPropertiesSchema}. */
    @Schema(additionalPropertiesSchema = Detail.class)
    static final class ClassLevelSchema {

        /** An ordinary property. */
        public String name;
    }

    /** A holder of a {@code @JsonTypeInfo} base with one declared subtype. */
    static final class TypedBaseHolder {

        /** The polymorphic member. */
        public Shape shape;
    }

    /** The polymorphic base. */
    @JsonTypeInfo(use = JsonTypeInfo.Id.NAME, include = JsonTypeInfo.As.PROPERTY, property = "kind")
    @JsonSubTypes({@JsonSubTypes.Type(value = Circle.class, name = "circle")})
    interface Shape {}

    /** The one declared subtype. */
    static final class Circle implements Shape {

        /** An ordinary property. */
        public int radius;
    }

    /** A type with a {@code @JsonUnwrapped} member. */
    static final class UnwrappedHolder {

        /** An ordinary property. */
        public String name;

        /** The unwrapped member, whose properties are flattened into this type's own. */
        @JsonUnwrapped
        public Detail detail;
    }

    /** A record. */
    record RecordShape(String city, int zip) {}

    /** A holder of an {@code Optional} of a DTO. */
    static final class OptionalHolder {

        /** The optional member. */
        public Optional<Detail> detail = Optional.empty();
    }

    /** A holder of a generic box parameterized with a DTO. */
    static final class GenericBoxHolder {

        /** The boxed member. */
        public Box<Detail> box;
    }

    /** A generic box.
     *
     * @param <T> the boxed type
     */
    static final class Box<T> {

        /** The boxed value. */
        public T value;
    }
}
