// SPDX-FileCopyrightText: 2026 Koivisto Capital Oy
// SPDX-License-Identifier: EUPL-1.2

package dev.vertique.examples.customresponse;

import static io.restassured.RestAssured.given;
import static org.hamcrest.Matchers.containsString;
import static org.hamcrest.Matchers.equalTo;
import static org.hamcrest.Matchers.notNullValue;
import static org.hamcrest.Matchers.startsWith;
import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertTrue;

import dev.vertique.application.test.VertiqueAppExtension;
import dev.vertique.rest.auth.jwt.JwtAuthFactory;
import io.restassured.RestAssured;
import io.restassured.filter.log.RequestLoggingFilter;
import io.restassured.filter.log.ResponseLoggingFilter;
import io.restassured.response.ExtractableResponse;
import io.restassured.response.Response;
import io.vertx.core.json.JsonArray;
import io.vertx.core.json.JsonObject;
import io.vertx.ext.auth.jwt.JWTAuth;
import io.vertx.junit5.VertxExtension;
import java.nio.charset.StandardCharsets;
import java.util.List;
import java.util.concurrent.TimeUnit;
import org.junit.jupiter.api.AfterAll;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.Timeout;
import org.junit.jupiter.api.extension.ExtendWith;
import org.junit.jupiter.api.extension.RegisterExtension;

/**
 * Integration tests for the example-custom-response application.
 *
 * <p>Boots the application via {@link VertiqueAppExtension} (using the factory generated by the
 * {@code @VertiqueApp} annotation processor) and verifies:
 * <ul>
 *   <li>SHA-256 {@code Digest} headers on success and error responses</li>
 *   <li>Request body digest verification (accept/reject)</li>
 *   <li>Categorized error format ({@code type}, {@code message}, {@code id})</li>
 *   <li>JWT + RBAC authorization on the delete endpoint</li>
 * </ul>
 */
@Timeout(value = 20, unit = TimeUnit.SECONDS)
@ExtendWith(VertxExtension.class)
class CustomResponseIT {

    @RegisterExtension
    static final VertiqueAppExtension app = VertiqueAppExtension.forFactory(new AppComponentVertiqueComponentFactory())
            .withConfig(
                    new JsonObject().put("http", new JsonObject().put("port", 0).put("host", "127.0.0.1")));

    private static JWTAuth jwtAuth;

    @BeforeAll
    static void setUp() {
        jwtAuth = JwtAuthFactory.fromSymmetricKey(
                app.vertx(), "HS256", "super-secret-key-for-example-app-minimum-256-bits-long!!");
        RestAssured.baseURI = "http://127.0.0.1";
        RestAssured.port = app.httpPort();
        RestAssured.filters(new RequestLoggingFilter(), new ResponseLoggingFilter());
    }

    @AfterAll
    static void tearDown() {
        RestAssured.reset();
    }

    /**
     * Generates a JWT token with the given subject and roles.
     *
     * @param sub   the subject (user ID)
     * @param roles the list of roles to include (may be null or empty)
     * @return the generated JWT token string
     */
    private static String generateToken(String sub, List<String> roles) {
        JsonObject claims = new JsonObject().put("sub", sub);
        if (roles != null && !roles.isEmpty()) {
            claims.put("roles", new JsonArray(roles));
        }
        return jwtAuth.generateToken(claims);
    }

    // --- Response Digest ---

    @Test
    @DisplayName("GET /items returns Digest header with correct SHA-256")
    void listItemsHasCorrectDigest() {
        ExtractableResponse<Response> response = given().when()
                .get("/items")
                .then()
                .statusCode(200)
                .header("Digest", startsWith("sha-256="))
                .extract();

        verifyDigest(response);
    }

    @Test
    @DisplayName("POST /items returns Digest header on 201 response")
    void createItemHasDigest() {
        ExtractableResponse<Response> response = given().contentType("application/json")
                .body("{\"name\":\"Widget\"}")
                .when()
                .post("/items")
                .then()
                .statusCode(201)
                .header("Digest", startsWith("sha-256="))
                .extract();

        verifyDigest(response);
    }

    // --- Request Digest Verification ---

    @Test
    @DisplayName("POST /items with correct Digest header succeeds")
    void correctRequestDigestAccepted() {
        String body = "{\"name\":\"Verified\"}";
        String digest = "sha-256=" + DigestUtil.sha256Base64(body);

        given().contentType("application/json")
                .header("Digest", digest)
                .body(body)
                .when()
                .post("/items")
                .then()
                .statusCode(201);
    }

    @Test
    @DisplayName("POST /items with wrong Digest header returns 400 VALIDATION")
    void wrongRequestDigestRejected() {
        given().contentType("application/json")
                .header("Digest", "sha-256=AAAA_wrong_digest_value")
                .body("{\"name\":\"Tampered\"}")
                .when()
                .post("/items")
                .then()
                .statusCode(400)
                .body("type", equalTo("VALIDATION"))
                .body("message", equalTo("Request body digest mismatch"))
                .body("id", notNullValue());
    }

    // --- Error Categorization ---

    @Test
    @DisplayName("POST /items with blank name returns 400 VALIDATION error with Digest")
    void blankNameReturnsValidationError() {
        ExtractableResponse<Response> response = given().contentType("application/json")
                .body("{\"name\":\"\"}")
                .when()
                .post("/items")
                .then()
                .statusCode(400)
                .body("type", equalTo("VALIDATION"))
                .body("message", equalTo("Item name must not be blank"))
                .body("id", notNullValue())
                .header("Digest", startsWith("sha-256="))
                .extract();

        verifyDigest(response);
    }

    @Test
    @DisplayName("GET /items/nonexistent returns 404 BUSINESS error with Digest")
    void notFoundReturnsBusinessError() {
        ExtractableResponse<Response> response = given().when()
                .get("/items/nonexistent")
                .then()
                .statusCode(404)
                .body("type", equalTo("BUSINESS"))
                .body("message", containsString("Item not found"))
                .body("id", notNullValue())
                .header("Digest", startsWith("sha-256="))
                .extract();

        verifyDigest(response);
    }

    // --- Security (JWT + RBAC) ---

    @Test
    @DisplayName("DELETE /items/{id} without token returns 401 SECURITY")
    void deleteWithoutTokenReturns401Security() {
        given().when()
                .delete("/items/some-id")
                .then()
                .statusCode(401)
                .body("type", equalTo("SECURITY"))
                .body("id", notNullValue());
    }

    @Test
    @DisplayName("DELETE /items/{id} with wrong role returns 403 SECURITY")
    void deleteWithWrongRoleReturns403Security() {
        String token = generateToken("user1", List.of("user"));

        given().header("Authorization", "Bearer " + token)
                .when()
                .delete("/items/some-id")
                .then()
                .statusCode(403)
                .body("type", equalTo("SECURITY"))
                .body("id", notNullValue());
    }

    @Test
    @DisplayName("DELETE /items/{id} with admin role returns 204")
    void deleteWithAdminRoleSucceeds() {
        // First create an item to delete
        String id = given().contentType("application/json")
                .body("{\"name\":\"ToDelete\"}")
                .when()
                .post("/items")
                .then()
                .statusCode(201)
                .extract()
                .jsonPath()
                .getString("id");

        String token = generateToken("admin1", List.of("admin"));

        given().header("Authorization", "Bearer " + token)
                .when()
                .delete("/items/" + id)
                .then()
                .statusCode(204);
    }

    // --- Helpers ---

    /**
     * Asserts that the {@code Digest} header in the response matches the SHA-256 of the response body.
     *
     * @param response the extracted response to verify
     */
    private void verifyDigest(ExtractableResponse<Response> response) {
        String digestHeader = response.header("Digest");
        assertNotNull(digestHeader, "Digest header must be present");
        assertTrue(digestHeader.startsWith("sha-256="), "Digest must use sha-256 algorithm");

        String expectedDigest =
                DigestUtil.sha256Base64(response.body().asString().getBytes(StandardCharsets.UTF_8));
        String actualDigest = digestHeader.substring("sha-256=".length());
        assertEquals(expectedDigest, actualDigest, "Digest must match SHA-256 of response body");
    }
}
