<?xml version="1.0" encoding="UTF-8"?>
<!--
SPDX-FileCopyrightText: 2026 Koivisto Capital Oy
SPDX-License-Identifier: EUPL-1.2
-->

<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">

    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>dev.vertique</groupId>
        <artifactId>vertique-app-parent</artifactId>
        <version>@vertiqueVersion@</version>
        <relativePath/>
    </parent>

    <artifactId>codegen-it-parent-runtime-dependencies-only</artifactId>
    <version>99.0.0</version>

    <dependencies>
        <dependency>
            <groupId>dev.vertique</groupId>
            <artifactId>vertique-application</artifactId>
        </dependency>
        <dependency>
            <groupId>dev.vertique</groupId>
            <artifactId>vertique-rest-jaxrs</artifactId>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <configuration>
                    <fork>true</fork>
                    <debug>true</debug>
                    <debugFileName>javac</debugFileName>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-help-plugin</artifactId>
                <version>3.5.2</version>
                <executions>
                    <execution>
                        <id>write-effective-pom</id>
                        <phase>prepare-package</phase>
                        <goals>
                            <goal>effective-pom</goal>
                        </goals>
                        <configuration>
                            <output>${project.build.directory}/effective-pom.xml</output>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-dependency-plugin</artifactId>
                <version>3.11.0</version>
                <executions>
                    <execution>
                        <id>write-compile-classpath</id>
                        <phase>prepare-package</phase>
                        <goals>
                            <goal>build-classpath</goal>
                        </goals>
                        <configuration>
                            <includeScope>compile</includeScope>
                            <outputFile>${project.build.directory}/compile-classpath.txt</outputFile>
                        </configuration>
                    </execution>
                    <execution>
                        <id>write-runtime-classpath</id>
                        <phase>prepare-package</phase>
                        <goals>
                            <goal>build-classpath</goal>
                        </goals>
                        <configuration>
                            <includeScope>runtime</includeScope>
                            <outputFile>${project.build.directory}/runtime-classpath.txt</outputFile>
                        </configuration>
                    </execution>
                    <execution>
                        <id>write-test-classpath</id>
                        <phase>prepare-package</phase>
                        <goals>
                            <goal>build-classpath</goal>
                        </goals>
                        <configuration>
                            <includeScope>test</includeScope>
                            <outputFile>${project.build.directory}/test-classpath.txt</outputFile>
                        </configuration>
                    </execution>
                    <execution>
                        <id>write-plugin-artifacts</id>
                        <phase>prepare-package</phase>
                        <goals>
                            <goal>resolve-plugins</goal>
                        </goals>
                        <configuration>
                            <outputFile>${project.build.directory}/plugin-artifacts.txt</outputFile>
                            <outputAbsoluteArtifactFilename>true</outputAbsoluteArtifactFilename>
                            <sort>true</sort>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>
</project>
