// SPDX-FileCopyrightText: 2026 Koivisto Capital Oy
// SPDX-License-Identifier: EUPL-1.2

package dev.vertique.rest.openapi.docs;

import com.fasterxml.jackson.databind.node.ObjectNode;
import dev.vertique.json.schema.AnnotationJsonSchemaGenerator;
import dev.vertique.rest.core.RestConfigurationException;
import io.vertx.core.json.JsonObject;
import jakarta.annotation.Nullable;
import java.lang.reflect.Type;

/**
 * Generates the output-direction schema of one published response type and checks it for the
 * constructs a published schema may not hold.
 *
 * <p>The schema is generated by the output generator of the operation's profile ({@link
 * OutputGenerators}), read into a tree the document owns by the same path captured input schemas
 * take ({@link DocumentWriter#tree}), and checked by {@link SchemaRefusals}. Nothing is published
 * here: the checked schema is relocated into a component only when the document is written.
 *
 * <p>Any exception from resolving the profile, building its generator, or generating the schema
 * fails publication with a {@link RestConfigurationException} that names the document's
 * configuration path, the application and its mount, the operation, what was being published, and
 * its status, and keeps the original exception as its cause. The message never carries schema
 * text.
 */
final class OutputSchemas {

    private OutputSchemas() {}

    /**
     * Generates and checks the output schema of one published type.
     *
     * @param prefix the failure-message prefix naming the document's configuration path, the
     *     application, and its mount
     * @param subject the failure-message subject naming the application and its mount, used by the
     *     refused-construct check
     * @param generators the output generators of the document's assembly
     * @param target the published type and where it is published
     * @return the checked schema, to publish as the target's component
     * @throws RestConfigurationException when the schema cannot be generated or holds a refused
     *     construct
     */
    static SchemaEmbedder.CheckedSchema check(
            String prefix, String subject, OutputGenerators generators, Target target) {
        String text;
        try {
            AnnotationJsonSchemaGenerator generator = generators.generator(target.profileId());
            text = generator.generateCanonical(target.type());
        } catch (RuntimeException e) {
            throw failure(prefix, target, "generating it in output direction failed", e);
        }
        ObjectNode tree = DocumentWriter.tree(new JsonObject(text));
        InputDescription description = target.description();
        SchemaRefusals.check(subject, description, tree);
        return new SchemaEmbedder.CheckedSchema(description, tree);
    }

    /**
     * Builds the failure of one published type.
     *
     * @param prefix the failure-message prefix
     * @param target the published type
     * @param reason why the type cannot be published, without schema text
     * @param cause the original exception
     * @return the failure
     */
    static RestConfigurationException failure(String prefix, Target target, String reason, Throwable cause) {
        return new RestConfigurationException(
                prefix + ": operation '" + target.operationId() + "' cannot publish the output " + target.what()
                        + " of status " + target.status() + ": " + reason,
                cause);
    }

    /**
     * One published output type and where it is published.
     *
     * @param operationId the runtime id of the operation
     * @param status the status a failure names
     * @param header the name of the header whose schema the type is, or {@code null} for a content
     *     schema
     * @param keySuffix the part of the component key after the operation id, before replacement
     * @param type the resolved type to generate
     * @param profileId the operation's resolved output profile id
     */
    record Target(
            String operationId, String status, @Nullable String header, String keySuffix, Type type, String profileId) {

        /**
         * Returns how a failure names the published schema.
         *
         * @return {@code content schema}, or {@code header '<name>' schema}
         */
        String what() {
            return header == null ? "content schema" : "header '" + header + "' schema";
        }

        /**
         * Returns the description of the component the schema is published as.
         *
         * @return the output description, whose collision phrase names the status and the operation
         */
        InputDescription description() {
            String noun = header == null
                    ? "output schema of status " + status
                    : "output schema of header '" + header + "' of status " + status;
            return InputDescription.output(operationId, noun, keySuffix);
        }
    }
}
