// SPDX-FileCopyrightText: 2026 Koivisto Capital Oy
// SPDX-License-Identifier: EUPL-1.2

package dev.vertique.rest.openapi.docs;

import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.node.JsonNodeFactory;
import com.fasterxml.jackson.databind.node.ObjectNode;
import dev.vertique.rest.core.RestConfigurationException;
import dev.vertique.rest.jaxrs.publication.MountPublication;
import dev.vertique.rest.jaxrs.publication.OperationDetail;
import dev.vertique.rest.jaxrs.publication.OperationPublication;
import dev.vertique.rest.jaxrs.publication.ResponseShape;
import io.swagger.v3.oas.annotations.headers.Header;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import jakarta.annotation.Nullable;
import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.SortedMap;

/**
 * Plans the {@code responses} of one operation's Operation Object and checks every schema it will
 * publish, before the document is written.
 *
 * <p>The operation's return type is classified by {@link ResponseInference}. Without a declared
 * {@link ApiResponse} (see {@link DeclaredResponses}), the operation publishes the one inferred
 * response: {@code 204} for no content, {@code 200} for a JSON entity (each media type referencing
 * the component {@code <operationId>.response}) or for raw text (each media type without a schema),
 * and else {@code default}. A non-empty declared set replaces the inferred response entirely: each
 * declared status publishes its description, headers, and content, except that a success status
 * declared without content ({@code 200} to {@code 299} other than {@code 204} and {@code 205}, or
 * {@code 2XX}) receives the inferred content when the return type is inferable. A status declaring
 * {@code useReturnTypeSchema} publishes the inferred content unless it declares content itself, and
 * fails publication when the return type is not inferable.
 *
 * <p>Response keys are published numeric codes ascending, then range keys, then {@code default}. A
 * blank description publishes the status's reason phrase ({@link ResponseStatuses}). A Response
 * Object holds {@code description}, {@code headers}, and {@code content}, in that order. A {@link
 * Content} with a blank media type applies to each of the operation's produced media types ({@code
 * application/json} when none is declared); one media type declared twice in one status fails
 * publication. Its {@code schema} implementation is published as a reference to the component
 * {@code <operationId>.response.<status>}, its {@code array} element implementation as an array of
 * such references, and a content with neither publishes its media type without a schema. When one
 * status declares several different implementations, each component key gains the suffix {@code
 * .<n>}, numbered from 1 in declaration order; one implementation used by several media types of a
 * status is one component. A {@link Header} with a blank name is left out; a header's schema
 * implementation is published as a reference to the component {@code
 * <operationId>.response.<status>.header.<name>}, and a header without one publishes the empty
 * schema.
 *
 * <p>Every published output type is generated by the output generator of the operation's profile
 * ({@link OutputSchemas}) during the check: the inferred type first, and only when some status
 * publishes it, then per status in published order each content implementation in declaration order,
 * then each header implementation. A failure names the status of the content or header; the
 * inferred type is always named as status {@code 200}. The declared statuses, {@code
 * useReturnTypeSchema}, and the media types of every status are checked before any type is
 * generated. Every refusal starts with the document's configuration path.
 */
final class ResponseAssembler {

    /** The media type of a response when the operation produces none. */
    private static final String DEFAULT_MEDIA_TYPE = "application/json";

    private static final JsonNodeFactory NODES = JsonNodeFactory.instance;

    private ResponseAssembler() {}

    /**
     * Plans the responses of one operation.
     *
     * @param subject the failure-message subject naming the application and its mount
     * @param document the enabled document
     * @param publication the detached publication of the mount
     * @param operation the operation
     * @param facts the operation's descriptor facts, or {@code null} when none were taken
     * @param context the component's assembly inputs
     * @param generators the output generators of the document's assembly
     * @param warnings the document's pending warnings
     * @return the plan, to publish once every operation of the document is checked
     * @throws RestConfigurationException when a declared status is invalid or declared twice at one
     *     level, {@code useReturnTypeSchema} is declared on a return type that is not inferable, one
     *     status declares a media type twice, or a published output type cannot be generated or holds
     *     a refused construct
     */
    static ResponsePlan check(
            String subject,
            EnabledDocuments.EnabledDocument document,
            MountPublication publication,
            OperationPublication operation,
            @Nullable OperationFacts facts,
            AssemblyContext context,
            OutputGenerators generators,
            PendingWarnings warnings) {
        OperationDetail detail = operation.detail();
        ResponseShape shape = detail == null ? null : detail.response();
        if (shape == null) {
            return ResponsePlan.NONE;
        }
        String operationId = operation.operationId();
        String prefix = "apidocs.documents." + document.name() + ": " + subject;
        ResponseInference.Inference inference = ResponseInference.classify(shape, context.producerBindings());
        SortedMap<String, ApiResponse> declared = DeclaredResponses.read(prefix, operationId, facts);
        List<String> produces = shape.produces().isEmpty() ? List.of(DEFAULT_MEDIA_TYPE) : shape.produces();

        Slot inferred = inference.outputType() == null
                ? null
                : new Slot(new OutputSchemas.Target(
                        operationId, "200", null, ".response", inference.outputType(), shape.outputProfileId()));
        List<PlannedResponse> responses = new ArrayList<>();
        if (declared.isEmpty()) {
            String status = inference.status();
            responses.add(new PlannedResponse(
                    status,
                    ResponseStatuses.reasonPhrase(status),
                    List.of(),
                    inference.inferable() ? inferredContent(inference, inferred) : null,
                    List.of(),
                    null));
        } else {
            for (Map.Entry<String, ApiResponse> entry : declared.entrySet()) {
                responses.add(declaredResponse(
                        prefix, operationId, entry.getKey(), entry.getValue(), inference, inferred, produces, shape));
            }
        }

        if (inferred != null && responses.stream().anyMatch(response -> response.uses(inferred))) {
            inferred.check(prefix, subject, generators);
        }
        for (PlannedResponse response : responses) {
            for (Slot slot : response.slots()) {
                slot.check(prefix, subject, generators);
            }
            for (PlannedHeader header : response.headers()) {
                if (header.schema() != null) {
                    header.schema().check(prefix, subject, generators);
                }
            }
        }
        return new ResponsePlan(responses);
    }

    /** Plans one declared status. */
    private static PlannedResponse declaredResponse(
            String prefix,
            String operationId,
            String status,
            ApiResponse response,
            ResponseInference.Inference inference,
            @Nullable Slot inferred,
            List<String> produces,
            ResponseShape shape) {
        if (response.useReturnTypeSchema() && !inference.inferable()) {
            throw new RestConfigurationException(prefix + ": operation '" + operationId
                    + "' declares @ApiResponse.useReturnTypeSchema on status " + status
                    + ", but its return type publishes no inferable response content; remove the attribute or"
                    + " declare the content");
        }
        String description = OperationMetadata.isSet(response.description())
                ? response.description()
                : ResponseStatuses.reasonPhrase(status);
        List<Slot> slots = new ArrayList<>();
        List<PlannedMediaType> content;
        if (response.content().length > 0) {
            content = declaredContent(prefix, operationId, status, response.content(), produces, shape, slots);
        } else if (inference.inferable()
                && (response.useReturnTypeSchema() || ResponseStatuses.keepsInferredContent(status))) {
            content = inferredContent(inference, inferred);
        } else {
            content = null;
        }
        List<PlannedHeader> headers = new ArrayList<>();
        for (Header header : response.headers()) {
            if (!OperationMetadata.isSet(header.name())) {
                continue;
            }
            Slot schema = implemented(header.schema().implementation())
                    ? new Slot(new OutputSchemas.Target(
                            operationId,
                            status,
                            header.name(),
                            ".response." + status + ".header." + header.name(),
                            header.schema().implementation(),
                            shape.outputProfileId()))
                    : null;
            headers.add(new PlannedHeader(header.name(), header, schema));
        }
        return new PlannedResponse(status, description, headers, content, slots, response);
    }

    /**
     * Plans the declared content of one status, collecting one slot per distinct implementation in
     * declaration order.
     */
    private static List<PlannedMediaType> declaredContent(
            String prefix,
            String operationId,
            String status,
            Content[] declared,
            List<String> produces,
            ResponseShape shape,
            List<Slot> slots) {
        List<Class<?>> implementations = new ArrayList<>();
        for (Content content : declared) {
            Class<?> implementation = implementation(content);
            if (implementation != null && !implementations.contains(implementation)) {
                implementations.add(implementation);
            }
        }
        Map<Class<?>, Slot> byImplementation = new LinkedHashMap<>();
        for (int i = 0; i < implementations.size(); i++) {
            Class<?> implementation = implementations.get(i);
            String suffix = ".response." + status + (implementations.size() > 1 ? "." + (i + 1) : "");
            Slot slot = new Slot(new OutputSchemas.Target(
                    operationId, status, null, suffix, implementation, shape.outputProfileId()));
            byImplementation.put(implementation, slot);
            slots.add(slot);
        }

        Map<String, PlannedMediaType> mediaTypes = new LinkedHashMap<>();
        for (Content content : declared) {
            Class<?> implementation = implementation(content);
            Slot slot = implementation == null ? null : byImplementation.get(implementation);
            SchemaForm form = slot == null
                    ? SchemaForm.NONE
                    : implemented(content.schema().implementation()) ? SchemaForm.REFERENCE : SchemaForm.ARRAY;
            List<String> applied =
                    OperationMetadata.isSet(content.mediaType()) ? List.of(content.mediaType()) : produces;
            for (String mediaType : applied) {
                if (mediaTypes.containsKey(mediaType)) {
                    throw new RestConfigurationException(prefix + ": operation '" + operationId
                            + "' declares one media type more than once in the content of status " + status
                            + " (@Content.mediaType); declare each media type once per status");
                }
                mediaTypes.put(mediaType, new PlannedMediaType(mediaType, form, slot, content));
            }
        }
        return List.copyOf(mediaTypes.values());
    }

    /** Plans the inferred content: one media type per inferred media type. */
    private static List<PlannedMediaType> inferredContent(
            ResponseInference.Inference inference, @Nullable Slot inferred) {
        boolean json = inference.row() == ResponseInference.Row.JSON_ENTITY;
        List<PlannedMediaType> content = new ArrayList<>();
        for (String mediaType : inference.mediaTypes()) {
            content.add(
                    json
                            ? new PlannedMediaType(mediaType, SchemaForm.REFERENCE, inferred, null)
                            : new PlannedMediaType(mediaType, SchemaForm.NONE, null, null));
        }
        return content;
    }

    /**
     * Returns the implementation a content publishes: its schema's implementation, else its array
     * element's, else {@code null}.
     */
    private static @Nullable Class<?> implementation(Content content) {
        if (implemented(content.schema().implementation())) {
            return content.schema().implementation();
        }
        if (implemented(content.array().schema().implementation())) {
            return content.array().schema().implementation();
        }
        return null;
    }

    /** Whether a {@code @Schema.implementation} member is set; its default is {@code Void}. */
    private static boolean implemented(Class<?> implementation) {
        return implementation != null && implementation != Void.class;
    }

    /** The checked responses of one operation. */
    static final class ResponsePlan {

        /** The plan of an operation without response facts, which publishes no {@code responses}. */
        static final ResponsePlan NONE = new ResponsePlan(null);

        @Nullable
        private final List<PlannedResponse> responses;

        private ResponsePlan(@Nullable List<PlannedResponse> responses) {
            this.responses = responses == null ? null : List.copyOf(responses);
        }

        /**
         * Writes the {@code responses} object, publishing each checked schema once.
         *
         * @param embedder the schema embedder that checked the schemas
         * @return the Responses Object, or {@code null} when the operation publishes none
         * @throws RestConfigurationException when a component key is already taken in the document
         */
        @Nullable
        ObjectNode publish(SchemaEmbedder embedder) {
            if (responses == null) {
                return null;
            }
            ObjectNode node = NODES.objectNode();
            for (PlannedResponse response : responses) {
                node.set(response.status(), response.publish(embedder));
            }
            return node;
        }
    }

    /** How a media type's schema is published. */
    private enum SchemaForm {
        /** The media type publishes no schema. */
        NONE,
        /** The schema is a reference to the slot's component. */
        REFERENCE,
        /** The schema is an array whose items reference the slot's component. */
        ARRAY
    }

    /**
     * One output type published as a component, generated and checked once and published once; every
     * place that references it receives its own copy of the reference.
     */
    private static final class Slot {

        private final OutputSchemas.Target target;

        @Nullable
        private SchemaEmbedder.CheckedSchema checked;

        @Nullable
        private JsonNode reference;

        Slot(OutputSchemas.Target target) {
            this.target = target;
        }

        /** Generates and checks the slot's schema, once. */
        void check(String prefix, String subject, OutputGenerators generators) {
            if (checked == null) {
                checked = OutputSchemas.check(prefix, subject, generators, target);
            }
        }

        /** Publishes the component on first use and returns a new copy of the reference to it. */
        JsonNode reference(SchemaEmbedder embedder) {
            if (reference == null) {
                if (checked == null) {
                    throw new IllegalStateException("A response schema is published before it is checked");
                }
                reference = embedder.publish(checked);
            }
            return reference.deepCopy();
        }
    }

    /**
     * One planned Response Object.
     *
     * @param status the status key
     * @param description the published description
     * @param headers the published headers, in declaration order
     * @param content the published media types in order, or {@code null} when it publishes no content
     * @param slots the components of its declared content, in declaration order
     * @param declaration the declaring annotation, or {@code null} for the inferred response
     */
    private record PlannedResponse(
            String status,
            String description,
            List<PlannedHeader> headers,
            @Nullable List<PlannedMediaType> content,
            List<Slot> slots,
            @Nullable ApiResponse declaration) {

        /** Whether some media type of the response references the slot. */
        boolean uses(Slot slot) {
            return content != null && content.stream().anyMatch(mediaType -> mediaType.slot() == slot);
        }

        /** Writes the Response Object: {@code description}, {@code headers}, and {@code content}. */
        ObjectNode publish(SchemaEmbedder embedder) {
            ObjectNode node = NODES.objectNode();
            node.put("description", description);
            if (!headers.isEmpty()) {
                ObjectNode published = node.putObject("headers");
                for (PlannedHeader header : headers) {
                    published.set(header.name(), header.publish(embedder));
                }
            }
            if (content != null) {
                ObjectNode published = node.putObject("content");
                for (PlannedMediaType mediaType : content) {
                    published.set(mediaType.mediaType(), mediaType.publish(embedder));
                }
            }
            return node;
        }
    }

    /**
     * One planned Header Object.
     *
     * @param name the header name
     * @param declaration the declaring annotation
     * @param schema the component of its schema implementation, or {@code null} for the empty schema
     */
    private record PlannedHeader(
            String name, Header declaration, @Nullable Slot schema) {

        /**
         * Writes the Header Object: {@code description} when set, {@code required} and {@code
         * deprecated} when true, then {@code schema}.
         */
        ObjectNode publish(SchemaEmbedder embedder) {
            ObjectNode node = NODES.objectNode();
            if (OperationMetadata.isSet(declaration.description())) {
                node.put("description", declaration.description());
            }
            if (declaration.required()) {
                node.put("required", true);
            }
            if (declaration.deprecated()) {
                node.put("deprecated", true);
            }
            node.set("schema", schema == null ? NODES.objectNode() : schema.reference(embedder));
            return node;
        }
    }

    /**
     * One planned Media Type Object.
     *
     * @param mediaType the media type
     * @param form how its schema is published
     * @param slot the component its schema references, or {@code null} when it publishes no schema
     * @param declaration the declaring annotation, or {@code null} for inferred content
     */
    private record PlannedMediaType(
            String mediaType,
            SchemaForm form,
            @Nullable Slot slot,
            @Nullable Content declaration) {

        /** Writes the Media Type Object: {@code schema} unless it publishes none. */
        ObjectNode publish(SchemaEmbedder embedder) {
            ObjectNode node = NODES.objectNode();
            switch (form) {
                case NONE -> {}
                case REFERENCE -> node.set("schema", slot.reference(embedder));
                case ARRAY -> {
                    ObjectNode array = node.putObject("schema");
                    array.set("items", slot.reference(embedder));
                    array.put("type", "array");
                }
            }
            return node;
        }
    }
}
