// SPDX-FileCopyrightText: 2026 Koivisto Capital Oy
// SPDX-License-Identifier: EUPL-1.2

package dev.vertique.codegen.integration;

import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertTrue;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.List;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import org.junit.jupiter.api.Test;

/**
 * Documentation policy tests for the public application parent and BOM-only processor-facade
 * recipes.
 */
class CodegenDocumentationPolicyTest {

    private static final Path REACTOR_ROOT =
            Path.of("..", "..").toAbsolutePath().normalize();
    private static final Pattern XML_FENCE = Pattern.compile("```xml\\s*(.*?)```", Pattern.DOTALL);
    private static final Pattern MARKDOWN_FENCE = Pattern.compile("```([^\\r\\n]*)\\R(.*?)```", Pattern.DOTALL);
    private static final Pattern PROCESSOR_LEAF =
            Pattern.compile("<artifactId>vertique-codegen-(?!all(?:</artifactId>))[^<]+</artifactId>");
    private static final Pattern PROCESSOR_LEAF_REFERENCE =
            Pattern.compile("\\bvertique-codegen-(?:application|dagger|jaxrs|rest-client|services|kafka|"
                    + "delayed-job|workflow|cron|sanitization|aop|events)\\b");
    private static final Pattern DIRECT_ADOPTION_INSTRUCTION =
            Pattern.compile("(?is)(?:\\b(?:add|configure|declare|install|select)\\s+(?:the\\s+)?"
                    + "(?:dev\\.vertique:)?`?\\bvertique-codegen-(?:application|dagger|jaxrs|"
                    + "rest-client|services|kafka|delayed-job|workflow|cron|sanitization|aop|events)\\b"
                    + "|\\bpair\\s+(?:it\\s+)?with\\s+`?\\bvertique-codegen-(?:application|dagger|"
                    + "jaxrs|rest-client|services|kafka|delayed-job|workflow|cron|sanitization|aop|events)\\b"
                    + "|\\bneed\\s+only\\s+`?\\bvertique-codegen-(?:application|dagger|jaxrs|"
                    + "rest-client|services|kafka|delayed-job|workflow|cron|sanitization|aop|events)\\b)");
    private static final List<String> PRODUCTION_PROCESSOR_ARTIFACTS = List.of(
            "vertique-codegen-application",
            "vertique-codegen-dagger",
            "vertique-codegen-jaxrs",
            "vertique-codegen-rest-client",
            "vertique-codegen-services",
            "vertique-codegen-kafka",
            "vertique-codegen-delayed-job",
            "vertique-codegen-workflow",
            "vertique-codegen-cron",
            "vertique-codegen-sanitization",
            "vertique-codegen-aop",
            "vertique-codegen-events");

    @Test
    void publishedRecipesUseParentOrFacade() throws IOException {
        List<Path> policyDocuments = policyDocuments();
        List<String> violations = new ArrayList<>();

        for (Path document : policyDocuments) {
            String markdown = Files.readString(document);
            String relativePath = REACTOR_ROOT.relativize(document).toString();

            if (isRequiredEntryPoint(document)) {
                requirePublicRecipe(relativePath, markdown, violations);
            }
            inspectXmlRecipes(relativePath, markdown, violations);
            inspectNonXmlRecipes(relativePath, markdown, violations);
            inspectAdoptionProse(relativePath, markdown, violations);
        }

        assertTrue(
                violations.isEmpty(),
                () -> "Published codegen recipes must use vertique-app-parent or the BOM-only "
                        + "vertique-codegen-all facade, and Lombok must be explicit opt-in:\n"
                        + String.join("\n", violations));
    }

    @Test
    void policyClassifierDistinguishesAdoptionFromArtifactOwnership() {
        assertTrue(isProseAdoptionInstruction(
                "Add `vertique-codegen-jaxrs` to `annotationProcessorPaths` in the application POM."));
        assertTrue(isNonXmlAdoptionRecipe(
                "annotationProcessorPaths = dev.vertique:vertique-codegen-jaxrs", "Configure the processor path:"));

        assertFalse(isProseAdoptionInstruction("`vertique-codegen-jaxrs` owns descriptor emission; "
                + "`vertique-codegen-dagger` owns REST-client bindings."));
        assertFalse(isNonXmlAdoptionRecipe(
                "GeneratedJaxRsResourcesModule // generated by vertique-codegen-jaxrs",
                "Artifact ownership reference:"));
    }

    @Test
    void sourceRetainedAnnotationsDocumentCompileTimeCoreDependency() throws IOException {
        List<Path> sourceAnnotationDocuments = List.of(
                REACTOR_ROOT.resolve("docs/packaging.md"),
                REACTOR_ROOT.resolve(
                        "vertique-job/vertique-job-delayed/src/main/resources/META-INF/vertique/module.md"),
                REACTOR_ROOT.resolve(
                        "vertique-rest/vertique-rest-client/src/main/resources/META-INF/vertique/module.md"),
                REACTOR_ROOT.resolve(
                        "vertique-rest/vertique-rest-jaxrs/src/main/resources/META-INF/vertique/module.md"),
                REACTOR_ROOT.resolve("vertique-services/src/main/resources/META-INF/vertique/module.md"));

        for (Path document : sourceAnnotationDocuments) {
            String markdown = Files.readString(document);
            assertTrue(
                    markdown.contains("vertique-codegen-core") && markdown.contains("provided"),
                    () -> REACTOR_ROOT.relativize(document)
                            + " must document vertique-codegen-core as a compile-time-only dependency");
        }
    }

    private static List<Path> policyDocuments() throws IOException {
        List<Path> documents = new ArrayList<>();
        documents.add(REACTOR_ROOT.resolve("README.md"));
        documents.add(REACTOR_ROOT.resolve("docs/packaging.md"));

        for (String artifactId : PRODUCTION_PROCESSOR_ARTIFACTS) {
            documents.add(REACTOR_ROOT
                    .resolve("vertique-codegen")
                    .resolve(artifactId)
                    .resolve("src/main/resources/META-INF/vertique/module.md"));
        }

        try (var paths = Files.walk(REACTOR_ROOT)) {
            paths.filter(path -> path.endsWith("src/main/resources/META-INF/vertique/module.md"))
                    .filter(path -> !documents.contains(path))
                    .filter(CodegenDocumentationPolicyTest::namesProductionProcessor)
                    .forEach(documents::add);
        }

        assertFalse(documents.isEmpty(), "Expected codegen policy documents to scan");
        for (Path document : documents) {
            assertTrue(Files.isRegularFile(document), () -> "Missing policy document " + document);
        }
        return List.copyOf(documents);
    }

    private static boolean namesProductionProcessor(Path document) {
        try {
            String markdown = Files.readString(document);
            return PRODUCTION_PROCESSOR_ARTIFACTS.stream().anyMatch(markdown::contains);
        } catch (IOException exception) {
            throw new IllegalStateException("Failed to inspect " + document, exception);
        }
    }

    private static boolean isRequiredEntryPoint(Path document) {
        if (document.equals(REACTOR_ROOT.resolve("README.md"))
                || document.equals(REACTOR_ROOT.resolve("docs/packaging.md"))) {
            return true;
        }
        return PRODUCTION_PROCESSOR_ARTIFACTS.stream()
                .map(artifactId -> REACTOR_ROOT
                        .resolve("vertique-codegen")
                        .resolve(artifactId)
                        .resolve("src/main/resources/META-INF/vertique/module.md"))
                .anyMatch(document::equals);
    }

    private static void requirePublicRecipe(String relativePath, String markdown, List<String> violations) {
        if (!markdown.contains("vertique-app-parent") && !markdown.contains("vertique-codegen-all")) {
            violations.add(relativePath + ": missing public parent or BOM-only facade guidance");
        }
    }

    private static void inspectXmlRecipes(String relativePath, String markdown, List<String> violations) {
        Matcher fences = XML_FENCE.matcher(markdown);
        while (fences.find()) {
            String recipe = fences.group(1);
            if (recipe.contains("vertique-app-parent")) {
                if (PROCESSOR_LEAF.matcher(recipe).find()) {
                    violations.add(relativePath + ": application-parent recipe declares a processor leaf");
                }
                if (recipe.contains("<artifactId>lombok</artifactId>")
                        && !isExplicitLombokOptIn(markdown, fences.start())) {
                    violations.add(relativePath + ": public parent default recipe activates Lombok");
                }
            }

            if (!recipe.contains("<annotationProcessorPaths")) {
                continue;
            }
            if (PROCESSOR_LEAF.matcher(recipe).find()) {
                violations.add(relativePath + ": BOM-only processor recipe declares a processor leaf");
            }
            if (recipe.contains("<groupId>dev.vertique</groupId>")
                    && !recipe.contains("<artifactId>vertique-codegen-all</artifactId>")) {
                violations.add(relativePath + ": BOM-only processor recipe does not use vertique-codegen-all");
            }
            if (recipe.contains("<artifactId>lombok</artifactId>")
                    && !isExplicitLombokOptIn(markdown, fences.start())) {
                violations.add(relativePath + ": Lombok processor recipe is not labeled explicit opt-in or internal");
            }
        }
    }

    private static void inspectNonXmlRecipes(String relativePath, String markdown, List<String> violations) {
        Matcher fences = MARKDOWN_FENCE.matcher(markdown);
        while (fences.find()) {
            if ("xml".equalsIgnoreCase(fences.group(1).trim())) {
                continue;
            }

            String recipe = fences.group(2);
            String context = precedingContext(markdown, fences.start()).toLowerCase();
            if (isNonXmlAdoptionRecipe(recipe, context)) {
                violations.add(relativePath + ": non-XML adoption recipe declares a processor leaf");
            }
        }
    }

    private static void inspectAdoptionProse(String relativePath, String markdown, List<String> violations) {
        String prose = MARKDOWN_FENCE.matcher(markdown).replaceAll("");
        for (String paragraph : prose.split("(?:\\R\\s*){2,}")) {
            String normalized = paragraph.replaceAll("\\s+", " ").trim();
            if (isProseAdoptionInstruction(normalized)) {
                violations.add(relativePath + ": prose adoption instruction selects a processor leaf: "
                        + abbreviate(normalized));
            }
        }
    }

    private static boolean isNonXmlAdoptionRecipe(String recipe, String context) {
        if (!PROCESSOR_LEAF_REFERENCE.matcher(recipe).find()) {
            return false;
        }
        String lowerCaseContext = context.toLowerCase();
        return recipe.contains("annotationProcessorPaths")
                || recipe.contains("annotation-processor-path")
                || lowerCaseContext.matches("(?s).*(?:add|configure|declare|install|processor path|"
                        + "annotationprocessorpaths|to adopt).*");
    }

    private static boolean isProseAdoptionInstruction(String prose) {
        if (!PROCESSOR_LEAF_REFERENCE.matcher(prose).find()) {
            return false;
        }
        String lowerCase = prose.toLowerCase();
        boolean directInstruction = DIRECT_ADOPTION_INSTRUCTION.matcher(prose).find();
        boolean pathInstruction = lowerCase.contains("annotationprocessorpaths")
                && (lowerCase.matches("(?s).*\\badd\\b.*")
                        || lowerCase.matches("(?s).*\\bto adopt\\b.*")
                        || lowerCase.matches("(?s).*\\bshould add\\b.*"));
        return directInstruction || pathInstruction;
    }

    private static String precedingContext(String markdown, int fenceStart) {
        int contextStart = Math.max(0, fenceStart - 500);
        return markdown.substring(contextStart, fenceStart);
    }

    private static String abbreviate(String value) {
        int limit = 180;
        return value.length() <= limit ? value : value.substring(0, limit) + "...";
    }

    private static boolean isExplicitLombokOptIn(String markdown, int fenceStart) {
        String context = precedingContext(markdown, fenceStart).toLowerCase();
        return context.contains("opt-in") || context.contains("opt in") || context.contains("internal example");
    }
}
