// SPDX-FileCopyrightText: 2026 Koivisto Capital Oy
// SPDX-License-Identifier: EUPL-1.2

package dev.vertique.examples.restclient;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertTrue;

import dev.vertique.application.test.VertiqueAppExtension;
import dev.vertique.examples.restclient.client.User;
import dev.vertique.examples.restclient.client.UserClient;
import dev.vertique.rest.client.RestClientBuilder;
import io.vertx.core.Vertx;
import io.vertx.core.json.JsonObject;
import io.vertx.junit5.VertxExtension;
import io.vertx.junit5.VertxTestContext;
import java.util.concurrent.ExecutionException;
import java.util.concurrent.TimeUnit;
import java.util.concurrent.TimeoutException;
import org.junit.jupiter.api.AfterAll;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.Timeout;
import org.junit.jupiter.api.extension.ExtendWith;
import org.junit.jupiter.api.extension.RegisterExtension;

/**
 * Integration test for the REST client example.
 *
 * <p>Boots the application via {@link VertiqueAppExtension} (using the factory generated by the
 * {@code @VertiqueApp} annotation processor) and drives its auto-wired {@link UserClient} against an
 * in-process {@link MockServerVerticle}. The mock server runs on a <em>separate</em> {@link Vertx}
 * instance from the application's: a {@code ContextLocal} fix makes two Vert.x in one JVM safe.
 *
 * <p>The mock binds on port {@code 0} (OS-allocated ephemeral) before the application starts; its
 * actual bound port is read via {@link MockServerVerticle#actualPort()} and threaded into
 * {@code restClient.userService.baseUrl} in the application config, so the singleton
 * {@link UserClient} resolves the live mock URL at construction. No external port allocation, no
 * {@code ServerSocket(0)}-style race.
 *
 * <p>{@link #userClientRoundTripsAgainstMockServer} exercises every {@code UserClient} operation
 * (list, findById hit + miss, create, delete) as real assertions on the returned values.
 * {@link #generatedProxy_selectedWhenOnClasspath} verifies that {@link RestClientBuilder} selects
 * the generated static proxy class ({@code UserClient_RestClientProxy}) when the
 * {@code vertique-codegen-rest-client} annotation processor is present, confirming the
 * zero-reflection path is active.
 */
@ExtendWith(VertxExtension.class)
@Timeout(value = 20, unit = TimeUnit.SECONDS)
class UserClientIT {

    /** A dedicated Vert.x hosting only the mock server, separate from the application's Vert.x. */
    static final Vertx mockVertx = Vertx.vertx();

    static int mockPort;

    static {
        MockServerVerticle mock = new MockServerVerticle(new MockConfig(0));
        try {
            mockVertx
                    .deployVerticle(mock)
                    .toCompletionStage()
                    .toCompletableFuture()
                    .get(10, TimeUnit.SECONDS);
        } catch (InterruptedException e) {
            Thread.currentThread().interrupt();
            throw new IllegalStateException("Interrupted while deploying mock server", e);
        } catch (ExecutionException | TimeoutException e) {
            throw new IllegalStateException("Mock server failed to deploy", e);
        }
        mockPort = mock.actualPort();
    }

    static final JsonObject CONFIG = new JsonObject()
            .put(
                    "restClient",
                    new JsonObject()
                            .put("userService", new JsonObject().put("baseUrl", "http://127.0.0.1:" + mockPort)));

    @RegisterExtension
    static final VertiqueAppExtension app = VertiqueAppExtension.forFactory(new AppComponentVertiqueComponentFactory())
            .withConfig(CONFIG);

    @AfterAll
    static void closeMock() throws Exception {
        // The application's own Vert.x is created and closed by the extension; only close the mock's.
        mockVertx.close().toCompletionStage().toCompletableFuture().get(10, TimeUnit.SECONDS);
    }

    @Test
    @DisplayName("UserClient round-trips list/findById/create/delete against the mock server")
    void userClientRoundTripsAgainstMockServer(VertxTestContext ctx) {
        UserClient client = app.<AppComponent>component().userClient();

        client.list(0)
                .compose(users -> {
                    ctx.verify(() -> {
                        assertEquals(2, users.size(), "mock returns two users");
                        assertEquals("Alice", users.get(0).name());
                        assertEquals("Bob", users.get(1).name());
                    });
                    return client.findById("1");
                })
                .compose(found -> {
                    ctx.verify(() -> {
                        assertTrue(found.isPresent(), "user 1 should be found");
                        assertEquals("Alice", found.get().name());
                        assertEquals("alice@example.com", found.get().email());
                    });
                    return client.findById("99");
                })
                .compose(missing -> {
                    ctx.verify(() -> assertFalse(missing.isPresent(), "user 99 should map a 404 to empty"));
                    return client.create(new User(null, "Charlie", "charlie@example.com"));
                })
                .compose(created -> {
                    ctx.verify(() -> {
                        assertNotNull(created.id(), "created user should have a server-assigned id");
                        assertEquals("Charlie", created.name());
                        assertEquals("charlie@example.com", created.email());
                    });
                    return client.delete(created.id());
                })
                .onComplete(ctx.succeedingThenComplete());
    }

    /**
     * Verifies that {@link RestClientBuilder} selects the generated static proxy class
     * ({@code UserClient_RestClientProxy}) when the annotation processor is present.
     *
     * <p>This test uses a placeholder base URL because the proxy selection happens at construction
     * time regardless of whether the server is reachable. No actual HTTP requests are made.
     */
    @Test
    @DisplayName("RestClientBuilder selects the generated static proxy when on the classpath")
    void generatedProxy_selectedWhenOnClasspath() {
        UserClient client = RestClientBuilder.create(app.vertx())
                .baseUrl("http://localhost:8081")
                .build(UserClient.class);

        assertTrue(
                client.getClass().getSimpleName().endsWith("_RestClientProxy"),
                "Expected generated static proxy but got: " + client.getClass().getName());
    }
}
