// SPDX-FileCopyrightText: 2026 Koivisto Capital Oy
// SPDX-License-Identifier: EUPL-1.2

package dev.vertique.codegen.aop;

import com.palantir.javapoet.AnnotationSpec;
import com.palantir.javapoet.ArrayTypeName;
import com.palantir.javapoet.ClassName;
import com.palantir.javapoet.CodeBlock;
import com.palantir.javapoet.FieldSpec;
import com.palantir.javapoet.JavaFile;
import com.palantir.javapoet.MethodSpec;
import com.palantir.javapoet.NameAllocator;
import com.palantir.javapoet.ParameterSpec;
import com.palantir.javapoet.ParameterizedTypeName;
import com.palantir.javapoet.TypeName;
import com.palantir.javapoet.TypeSpec;
import com.palantir.javapoet.TypeVariableName;
import dev.vertique.codegen.CodegenContext;
import dev.vertique.codegen.Diagnostics;
import dev.vertique.codegen.meta.AnnotationLiteralEmitter;
import dev.vertique.codegen.meta.MetadataEmitter;
import dev.vertique.codegen.support.Identifiers;
import java.beans.Introspector;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Comparator;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import java.util.Set;
import javax.lang.model.element.AnnotationMirror;
import javax.lang.model.element.ExecutableElement;
import javax.lang.model.element.Modifier;
import javax.lang.model.element.TypeElement;
import javax.lang.model.element.VariableElement;
import javax.lang.model.type.TypeKind;
import javax.lang.model.type.TypeMirror;

/**
 * Emits a reflection-free {@code <Bean>$AopProxy extends <Bean>} subclass proxy for a bean carrying
 * at least one {@link dev.vertique.aop.Aspect}-meta-annotated method (PRD Appendix A.5).
 *
 * <p>The generated proxy:
 * <ul>
 *   <li>extends the target bean and replicates its single {@code @Inject} constructor's parameters
 *       — including every qualifier / {@code @Nullable} / {@code Provider} / {@code Lazy} annotation
 *       — verbatim, passing them straight through to {@code super(...)};
 *   <li>appends one {@code AspectProvider<A>} constructor parameter per distinct aspect annotation
 *       used on the bean (typed as the parameterized interface, FR-013-17);
 *   <li>holds a {@code static final MethodMetadata} constant per intercepted method (generated by
 *       {@link MetadataEmitter}) and a {@code static final <Ann>} literal per aspect annotation
 *       (generated by {@link AnnotationLiteralEmitter});
 *   <li>builds each method's interceptor chain once in the constructor, ordered outermost-by-higher
 *       {@code @Aspect.ordering()} with ties broken by annotation fully-qualified name;
 *   <li>overrides each intercepted method to run the chain via
 *       {@code dev.vertique.aop.Invocations.run(...)} around a direct {@code super.<method>(...)}
 *       terminal call — never {@code Method.invoke}, never reflection.
 * </ul>
 *
 * <p>Framework SPI types ({@code MethodInterceptor}, {@code AspectProvider}, {@code Invocations},
 * {@code MethodMetadata}) are referenced by raw {@link ClassName} so the emitter does not need them
 * on its own compile classpath beyond the {@code vertique-aop} dependency.
 */
final class AopProxyEmitter {

    static final String PROXY_SUFFIX = "$AopProxy";

    private static final String GENERATOR_NAMESPACE = "Aop";

    // --- Framework SPI ClassName constants (referenced, rendered into generated source) ---
    private static final ClassName INVOCATIONS = ClassName.get("dev.vertique.aop", "Invocations");
    private static final ClassName METHOD_INTERCEPTOR = ClassName.get("dev.vertique.aop", "MethodInterceptor");
    private static final ClassName ASPECT_PROVIDER = ClassName.get("dev.vertique.aop", "AspectProvider");
    private static final ClassName METHOD_METADATA = ClassName.get("dev.vertique.core.codegen", "MethodMetadata");
    private static final ClassName INJECT = ClassName.get("jakarta.inject", "Inject");
    private static final ClassName FUTURE = ClassName.get("io.vertx.core", "Future");

    private final CodegenContext ctx;

    AopProxyEmitter(CodegenContext ctx) {
        this.ctx = ctx;
    }

    /**
     * Generates and writes the proxy for {@code bean}, plus its per-method {@code MethodMetadata}
     * impls and per-aspect annotation literals.
     *
     * <p>Every per-method generated member (the nested {@code MethodMetadata} type, the metadata
     * constant, and the chain field) is disambiguated by the method's <em>ordinal</em> — its index
     * among {@code interceptedMethods} — so overloaded intercepted methods (same simple name,
     * different parameters) never collide (Bug F4). The annotation literal <em>instance</em> baked
     * into each method's chain is built per annotation <em>occurrence</em> (from that method's own
     * mirror), so two methods carrying the same aspect with different attribute values materialize
     * distinct literals (Bug F2); the {@code <Ann>$AopLiteral} <em>class</em> itself is written at most
     * once per compilation via {@code emittedLiteralFqns}.
     *
     * @param bean             the target bean type element; must not be {@code null}
     * @param injectCtor       the bean's single {@code @Inject} constructor; must not be {@code null}
     * @param interceptedMethods the bean's aspect-annotated methods (in declaration order); must not
     *                         be empty
     * @param aspectFqns       the set of aspect trigger-annotation FQNs the processor recognises
     * @param emittedLiteralFqns the compilation-scoped set of {@code <Ann>$AopLiteral} FQNs already
     *                         written to the {@code Filer}; this method adds each literal class it
     *                         writes and skips any already present (per-compilation dedup, Bug F2)
     * @return the proxy's {@link ClassName} (binary-name style, with the {@code $AopProxy} suffix)
     */
    ClassName emit(
            TypeElement bean,
            ExecutableElement injectCtor,
            List<ExecutableElement> interceptedMethods,
            Set<String> aspectFqns,
            Set<String> emittedLiteralFqns) {
        // The proxy must always co-locate with the bean — in the bean's own package — so that
        // super(...) and super.method(...) calls are legal for package-private constructors and
        // intercepted methods. The -Avertique.codegen.package option moves only GeneratedAopModule
        // (which does not subclass anything); the proxy itself is not relocatable.
        String pkg = ctx.packageNameOf(bean);
        String proxySimpleName = Identifiers.generatedClassName(bean, PROXY_SUFFIX);
        ClassName proxyClass = ClassName.get(pkg, proxySimpleName);
        ClassName beanClass = ClassName.get(bean);

        // Distinct aspect annotation types across the bean, with a stable per-aspect provider name.
        Map<String, AspectRef> aspects = collectAspects(interceptedMethods, aspectFqns);

        TypeSpec.Builder proxy = TypeSpec.classBuilder(proxySimpleName)
                .addModifiers(Modifier.PUBLIC, Modifier.FINAL)
                .superclass(beanClass);

        // Per method: a nested MethodMetadata impl (so its int.class/int[].class/void.class literals
        // land in the proxy's own source) and a static final MethodMetadata constant holding it.
        // Names are disambiguated by ordinal so overloads do not collide (Bug F4). The metadata impl's
        // reflection-free findAnnotation/hasAnnotation is backed by one materialized literal per
        // runtime-retained method annotation (FR-013-13); each such <Ann>$AopLiteral CLASS is written at
        // most once per compilation via emittedLiteralFqns.
        Map<ExecutableElement, String> metaFieldNames = new LinkedHashMap<>();
        for (int i = 0; i < interceptedMethods.size(); i++) {
            ExecutableElement method = interceptedMethods.get(i);
            List<MetadataEmitter.AnnotationLiteralRef> methodAnnotations =
                    materializeMethodAnnotations(method, emittedLiteralFqns);
            List<List<MetadataEmitter.AnnotationLiteralRef>> parameterAnnotations =
                    materializeParameterAnnotations(method, emittedLiteralFqns);
            String metaTypeSimpleName = metaTypeName(method, i);
            ClassName nestedMeta = proxyClass.nestedClass(metaTypeSimpleName);
            proxy.addType(MetadataEmitter.methodMetadataType(
                            method, nestedMeta, ctx.types(), methodAnnotations, parameterAnnotations)
                    .addModifiers(Modifier.PRIVATE, Modifier.STATIC, Modifier.FINAL)
                    .build());
            String metaFieldName = metaFieldName(method, i);
            proxy.addField(buildStaticConstant(METHOD_METADATA, metaFieldName, CodeBlock.of("new $T()", nestedMeta)));
            metaFieldNames.put(method, metaFieldName);
        }

        // Emit each distinct aspect <Ann>$AopLiteral CLASS at most once per compilation (shared dedup set
        // with the method-annotation materialization above). materializeMethodAnnotations already emits
        // the class for a runtime-retained aspect trigger, but this guarantees the class exists for the
        // occurrence INSTANCE fields below even for an aspect annotation that is not runtime-retained.
        for (AspectRef aspect : aspects.values()) {
            ClassName literalClass = AnnotationLiteralEmitter.literalClassName(
                    aspect.annotationType, ctx.elements(), GENERATOR_NAMESPACE);
            if (emittedLiteralFqns.add(literalClass.canonicalName())) {
                write(AnnotationLiteralEmitter.emit(
                        aspect.annotationType,
                        aspect.representativeMirror,
                        ctx.elements(),
                        ctx.types(),
                        GENERATOR_NAMESPACE));
            }
        }

        // Per (method, aspect) occurrence: a static final <Ann> literal INSTANCE built from THAT
        // method's own mirror, so each occurrence's attribute values are preserved (Bug F2). The
        // field is keyed by method ordinal + aspect so distinct occurrences never share a constant.
        Map<OccurrenceKey, String> occurrenceLiteralFields = new LinkedHashMap<>();
        for (int i = 0; i < interceptedMethods.size(); i++) {
            ExecutableElement method = interceptedMethods.get(i);
            for (AspectOnMethod occurrence : orderedAspects(method, aspects.keySet())) {
                AspectRef ref = aspects.get(occurrence.fqn());
                ClassName literalClass = AnnotationLiteralEmitter.literalClassName(
                        ref.annotationType, ctx.elements(), GENERATOR_NAMESPACE);
                CodeBlock args =
                        AnnotationLiteralEmitter.constructorArgs(occurrence.mirror(), ctx.elements(), ctx.types());
                String literalFieldName = occurrenceLiteralFieldName(ref, i);
                proxy.addField(buildStaticConstant(
                        ClassName.get(ref.annotationType),
                        literalFieldName,
                        CodeBlock.of("new $T($L)", literalClass, args)));
                occurrenceLiteralFields.put(new OccurrenceKey(i, occurrence.fqn()), literalFieldName);
            }
        }

        // private final MethodInterceptor[] <method>_<i>$chain;
        for (int i = 0; i < interceptedMethods.size(); i++) {
            proxy.addField(
                    ArrayTypeName.of(METHOD_INTERCEPTOR),
                    chainFieldName(interceptedMethods.get(i), i),
                    Modifier.PRIVATE,
                    Modifier.FINAL);
        }

        // @Inject constructor: replicate super params verbatim, append AspectProvider<A> params.
        proxy.addMethod(
                buildConstructor(injectCtor, aspects, interceptedMethods, metaFieldNames, occurrenceLiteralFields));

        // @Override each intercepted method.
        for (int i = 0; i < interceptedMethods.size(); i++) {
            ExecutableElement method = interceptedMethods.get(i);
            proxy.addMethod(buildOverride(method, i, metaFieldNames.get(method)));
        }

        write(JavaFile.builder(pkg, proxy.build()).build());
        return proxyClass;
    }

    // --- method annotation materialization (reflection-free findAnnotation backing) ---

    /**
     * Materializes the method's {@code @Retention(RUNTIME)} annotations into
     * {@link MetadataEmitter.AnnotationLiteralRef}s backing the metadata impl's reflection-free
     * method-level {@code findAnnotation}/{@code hasAnnotation} (FR-013-13), delegating to
     * {@link #materializeAnnotations} with the method as both the annotated element and the diagnostic
     * target.
     *
     * @param method             the intercepted method whose annotations to materialize
     * @param emittedLiteralFqns the compilation-scoped set of already-written {@code <Ann>$AopLiteral} FQNs
     * @return the materialized literal refs, in annotation-declaration order (excluding skipped ones)
     */
    private List<MetadataEmitter.AnnotationLiteralRef> materializeMethodAnnotations(
            ExecutableElement method, Set<String> emittedLiteralFqns) {
        return materializeAnnotations(method, method, emittedLiteralFqns);
    }

    /**
     * Materializes each parameter's {@code @Retention(RUNTIME)} annotations into
     * {@link MetadataEmitter.AnnotationLiteralRef}s backing the nested {@code ParameterMetadataImpl}'s
     * reflection-free parameter-level {@code findAnnotation}/{@code hasAnnotation} (FR-015-07), the
     * parameter-level analogue of {@link #materializeMethodAnnotations}. Returns one list per parameter,
     * in parameter order (parallel to {@code method.getParameters()}); an unsupported attribute kind on a
     * parameter annotation is rejected via {@code Diagnostics.error} against the offending parameter
     * element (FR-013-13 / FR-013-09c) and skipped.
     *
     * @param method             the intercepted method whose parameters' annotations to materialize
     * @param emittedLiteralFqns the compilation-scoped set of already-written {@code <Ann>$AopLiteral} FQNs
     * @return one materialized-literal list per parameter, in parameter order (each may be empty)
     */
    private List<List<MetadataEmitter.AnnotationLiteralRef>> materializeParameterAnnotations(
            ExecutableElement method, Set<String> emittedLiteralFqns) {
        List<List<MetadataEmitter.AnnotationLiteralRef>> perParameter = new ArrayList<>();
        for (VariableElement parameter : method.getParameters()) {
            perParameter.add(materializeAnnotations(parameter, parameter, emittedLiteralFqns));
        }
        return perParameter;
    }

    /**
     * Materializes the {@code @Retention(RUNTIME)} annotations on {@code annotated} into
     * {@link MetadataEmitter.AnnotationLiteralRef}s — the shared core of method-level and
     * parameter-level annotation materialization. For each runtime-retained annotation it emits
     * (deduplicated per compilation via {@code emittedLiteralFqns}) the {@code <Ann>$AopLiteral} class and
     * returns a ref carrying the literal class plus this occurrence's constructor arguments.
     *
     * <p>{@code SOURCE}/{@code CLASS}-retained annotations are skipped. An annotation carrying a member
     * of an unsupported attribute kind ({@code char}/{@code float}/{@code double}, a nested-annotation
     * member, or an array of those) is rejected via {@code Diagnostics.error} against
     * {@code diagnosticTarget} (FR-013-13 / FR-013-09c) and skipped, so the literal emitter never
     * crashes on (or emits broken code for) an unrenderable kind.
     *
     * @param annotated          the annotated element (a method or a parameter) to read mirrors from
     * @param diagnosticTarget   the element the unsupported-kind diagnostic is attached to
     * @param emittedLiteralFqns the compilation-scoped set of already-written {@code <Ann>$AopLiteral} FQNs
     * @return the materialized literal refs, in annotation-declaration order (excluding skipped ones)
     */
    private List<MetadataEmitter.AnnotationLiteralRef> materializeAnnotations(
            javax.lang.model.element.Element annotated,
            javax.lang.model.element.Element diagnosticTarget,
            Set<String> emittedLiteralFqns) {
        List<MetadataEmitter.AnnotationLiteralRef> refs = new ArrayList<>();
        for (AnnotationMirror mirror : annotated.getAnnotationMirrors()) {
            TypeElement annType = (TypeElement) mirror.getAnnotationType().asElement();
            if (!isRuntimeRetained(annType)) {
                continue;
            }
            // Reject an unsupported attribute kind cleanly rather than letting the literal emitter crash.
            Optional<AnnotationLiteralEmitter.UnsupportedAttribute> unsupported =
                    AnnotationLiteralEmitter.firstUnsupportedAttribute(annType);
            if (unsupported.isPresent()) {
                AnnotationLiteralEmitter.UnsupportedAttribute bad = unsupported.get();
                ctx.diagnostics()
                        .error(
                                diagnosticTarget,
                                Diagnostics.unsupportedAnnotationAttributeKind(
                                        annType.getQualifiedName().toString(), bad.member(), bad.kind()));
                continue;
            }
            ClassName literalClass =
                    AnnotationLiteralEmitter.literalClassName(annType, ctx.elements(), GENERATOR_NAMESPACE);
            if (emittedLiteralFqns.add(literalClass.canonicalName())) {
                write(AnnotationLiteralEmitter.emit(annType, mirror, ctx.elements(), ctx.types(), GENERATOR_NAMESPACE));
            }
            CodeBlock args = AnnotationLiteralEmitter.constructorArgs(mirror, ctx.elements(), ctx.types());
            refs.add(new MetadataEmitter.AnnotationLiteralRef(ClassName.get(annType), literalClass, args));
        }
        return refs;
    }

    /** Returns {@code true} when the annotation type is declared with {@code @Retention(RUNTIME)}. */
    private boolean isRuntimeRetained(TypeElement annotationType) {
        return ctx.annotations()
                .find(annotationType, java.lang.annotation.Retention.class)
                .flatMap(m -> ctx.annotations().attribute(m, "value", javax.lang.model.element.VariableElement.class))
                .map(v -> v.getSimpleName().toString().equals("RUNTIME"))
                .orElse(false);
    }

    // --- aspect collection & ordering ---

    /**
     * Collects the distinct aspect annotation types used across the intercepted methods, keyed by
     * annotation FQN, assigning each a stable provider-parameter and literal-field name.
     */
    private Map<String, AspectRef> collectAspects(List<ExecutableElement> methods, Set<String> aspectFqns) {
        Map<String, AspectRef> byFqn = new LinkedHashMap<>();
        for (ExecutableElement method : methods) {
            for (AnnotationMirror mirror : aspectMirrors(method, aspectFqns)) {
                TypeElement annType = (TypeElement) mirror.getAnnotationType().asElement();
                String fqn = annType.getQualifiedName().toString();
                byFqn.computeIfAbsent(fqn, k -> new AspectRef(annType, mirror));
            }
        }
        return byFqn;
    }

    /**
     * Returns the aspect mirrors on {@code method}, ordered outermost-first: higher
     * {@code @Aspect.ordering()} first, ties broken by ascending annotation FQN.
     */
    private List<AspectOnMethod> orderedAspects(ExecutableElement method, Set<String> aspectFqns) {
        List<AspectOnMethod> list = new ArrayList<>();
        for (AnnotationMirror mirror : aspectMirrors(method, aspectFqns)) {
            TypeElement annType = (TypeElement) mirror.getAnnotationType().asElement();
            String fqn = annType.getQualifiedName().toString();
            list.add(new AspectOnMethod(fqn, aspectOrdering(annType), mirror));
        }
        list.sort(Comparator.comparingInt(AspectOnMethod::ordering).reversed().thenComparing(AspectOnMethod::fqn));
        return list;
    }

    /** Expands repeatable annotation containers so each occurrence receives its own literal. */
    private List<AnnotationMirror> aspectMirrors(ExecutableElement method, Set<String> aspectFqns) {
        List<AnnotationMirror> result = new ArrayList<>();
        for (AnnotationMirror mirror : method.getAnnotationMirrors()) {
            String fqn = ((TypeElement) mirror.getAnnotationType().asElement())
                    .getQualifiedName()
                    .toString();
            if (aspectFqns.contains(fqn)) {
                result.add(mirror);
                continue;
            }
            for (var entry : mirror.getElementValues().entrySet()) {
                if (!(entry.getValue().getValue() instanceof List<?> values)) continue;
                for (Object value : values) {
                    if (value instanceof javax.lang.model.element.AnnotationValue annotationValue
                            && annotationValue.getValue() instanceof AnnotationMirror nested) {
                        String nestedFqn = ((TypeElement)
                                        nested.getAnnotationType().asElement())
                                .getQualifiedName()
                                .toString();
                        if (aspectFqns.contains(nestedFqn)) result.add(nested);
                    }
                }
            }
        }
        return result;
    }

    /** Reads the {@code ordering()} member of the {@code @Aspect} meta-annotation on the trigger type. */
    private int aspectOrdering(TypeElement annotationType) {
        return ctx.annotations()
                .find(annotationType, dev.vertique.aop.Aspect.class)
                .flatMap(m -> ctx.annotations().attribute(m, "ordering", Integer.class))
                .orElse(1000);
    }

    // --- constructor ---

    /**
     * Builds the proxy's {@code @Inject} constructor: every super-ctor parameter replicated verbatim
     * (with its annotations) and passed to {@code super(...)}, then one {@code AspectProvider<A>}
     * parameter per distinct aspect, then per-method chain assignments.
     */
    private MethodSpec buildConstructor(
            ExecutableElement injectCtor,
            Map<String, AspectRef> aspects,
            List<ExecutableElement> interceptedMethods,
            Map<ExecutableElement, String> metaFieldNames,
            Map<OccurrenceKey, String> occurrenceLiteralFields) {
        MethodSpec.Builder ctor = MethodSpec.constructorBuilder()
                .addModifiers(Modifier.PUBLIC)
                .addAnnotation(AnnotationSpec.builder(INJECT).build());

        // Seed a NameAllocator with the super-ctor parameter names already in scope, so the appended
        // AspectProvider params get suffixed (e.g. fooProvider_) when a user parameter already uses
        // their chosen name (Bug R3-4). Replicated super params keep their original names verbatim.
        NameAllocator names = new NameAllocator();
        List<String> superArgs = new ArrayList<>();
        for (VariableElement param : injectCtor.getParameters()) {
            String paramName = names.newName(param.getSimpleName().toString());
            ParameterSpec.Builder p = ParameterSpec.builder(TypeName.get(param.asType()), paramName);
            for (AnnotationMirror am : param.getAnnotationMirrors()) {
                p.addAnnotation(AnnotationSpec.get(am));
            }
            ctor.addParameter(p.build());
            superArgs.add(paramName);
        }
        ctor.addStatement("super($L)", String.join(", ", superArgs));

        // Append AspectProvider<A> params — one per aspect TYPE (the provider is type-keyed,
        // FR-013-17). The per-occurrence literal value is supplied separately below. Each provider
        // param name is allocated through the NameAllocator so it never collides with a super param.
        Map<String, String> providerParamNames = new LinkedHashMap<>();
        for (AspectRef aspect : aspects.values()) {
            String providerParamName = names.newName(aspect.providerParamName);
            providerParamNames.put(aspect.providerParamName, providerParamName);
            TypeName providerType = ParameterizedTypeName.get(ASPECT_PROVIDER, ClassName.get(aspect.annotationType));
            ctor.addParameter(
                    ParameterSpec.builder(providerType, providerParamName).build());
        }

        // Build each method's chain = new MethodInterceptor[]{ provider.interceptor(META, LITERAL), ... }.
        // The LITERAL is the per-occurrence constant for THIS (method, aspect) pair (Bug F2).
        Set<String> aspectFqns = aspects.keySet();
        for (int i = 0; i < interceptedMethods.size(); i++) {
            ExecutableElement method = interceptedMethods.get(i);
            int ordinal = i;
            List<AspectOnMethod> ordered = orderedAspects(method, aspectFqns);
            List<CodeBlock> entries = ordered.stream()
                    .map(a -> {
                        AspectRef ref = aspects.get(a.fqn());
                        return CodeBlock.of(
                                "$N.interceptor($N, $N)",
                                providerParamNames.get(ref.providerParamName),
                                metaFieldNames.get(method),
                                occurrenceLiteralFields.get(new OccurrenceKey(ordinal, a.fqn())));
                    })
                    .toList();
            ctor.addStatement(
                    "this.$N = new $T[] {$L}",
                    chainFieldName(method, i),
                    METHOD_INTERCEPTOR,
                    CodeBlock.join(entries, ", "));
        }

        return ctor.build();
    }

    // --- method override ---

    /**
     * Builds the {@code @Override} for an intercepted method: gather args, run the chain around a
     * direct {@code super.<method>(...)} terminal, and map the result to the declared return type.
     *
     * <p>The override replicates the intercepted method's own type parameters (Bug N3) and its
     * {@code throws} clause (Bug N2) so the generated signature matches the bean method. The terminal
     * super-call reads its arguments back from the live {@code args} array — {@code (ParamType)
     * args[i]} — rather than from the original parameter locals (Bug N1, PRD A.5), so an aspect that
     * rewrites {@code invocation.arguments()[i]} actually reaches {@code super}. Because the terminal
     * is shaped as a {@code Supplier<Future<Object>>} (which cannot throw a checked exception), the
     * super call is wrapped in a {@code try/catch} that turns a synchronous checked throw into a
     * failed future (Bug N2); the {@link Invocations} nester already does the same for the no-aspect
     * fast path.
     */
    private MethodSpec buildOverride(ExecutableElement method, int ordinal, String metaField) {
        String name = method.getSimpleName().toString();
        TypeName returnType = TypeName.get(method.getReturnType());

        MethodSpec.Builder override = MethodSpec.methodBuilder(name)
                .addAnnotation(Override.class)
                .addModifiers(Modifier.PUBLIC)
                // Declare the method's own type parameters (e.g. <T>) so its T-referencing param and
                // return types resolve in the override (Bug N3).
                .addTypeVariables(method.getTypeParameters().stream()
                        .map(TypeVariableName::get)
                        .toList())
                .returns(returnType)
                // Replicate the bean method's checked-exception declaration so the override signature
                // matches (Bug N2); the Future-returning case never throws synchronously, but the
                // declaration must still mirror the overridden method.
                .addExceptions(
                        method.getThrownTypes().stream().map(TypeName::get).toList());

        // Seed a NameAllocator with the override's parameter names (already in scope) so every
        // generated local/lambda variable gets suffixed (e.g. args_) when a user parameter shares its
        // name (Bug R3-4). The allocator returns the original name when there is no clash, so the
        // common case still emits the readable args/result/cause locals.
        NameAllocator names = new NameAllocator();
        List<String> paramNames = new ArrayList<>();
        List<? extends VariableElement> params = method.getParameters();
        for (VariableElement p : params) {
            String paramName = names.newName(p.getSimpleName().toString());
            override.addParameter(TypeName.get(p.asType()), paramName);
            paramNames.add(paramName);
        }

        // Allocate the generated identifiers through the same allocator, after the user params are
        // seeded, so they never collide with a user parameter in scope.
        String argsVar = names.newName("args");
        String resultVar = names.newName("result");
        String mapVar = names.newName("v");
        String backCastVar = names.newName("o");
        String catchVar = names.newName("t");

        // Build the live-args super call: super.<name>((P0) <args>[0], (P1) <args>[1], ...). Reading the
        // (possibly aspect-mutated) array — not the original locals — is what makes argument mutation
        // observable at the terminal (Bug N1, PRD A.5).
        List<CodeBlock> superCallArgs = new ArrayList<>();
        for (int i = 0; i < params.size(); i++) {
            TypeName paramType = TypeName.get(params.get(i).asType());
            superCallArgs.add(CodeBlock.of("($T) $N[$L]", paramType, argsVar, i));
        }

        String argsCsv = String.join(", ", paramNames);
        override.addStatement("$T[] $N = {$L}", Object.class, argsVar, argsCsv);
        CodeBlock superCall = CodeBlock.of("super.$N($L)", name, CodeBlock.join(superCallArgs, ", "));

        // Terminal supplier performs the direct super call; result normalized to Future<Object>. The
        // super call may declare checked exceptions (Bug N2), so it is wrapped in a try/catch that
        // turns a synchronous throw into a failed future — the Supplier<Future<Object>> functional
        // type cannot itself throw a checked exception.
        boolean returnsFuture = isFuture(method.getReturnType());
        if (returnsFuture) {
            // Future<T> method: terminal returns the super future cast to Future<Object>.
            override.addStatement(
                    "$T<Object> $N = $T.run(this, $N, $N, this.$N, () -> {\n"
                            + "  try {\n"
                            + "    return $L.map($N -> (Object) $N);\n"
                            + "  } catch ($T $N) {\n"
                            + "    return $T.failedFuture($N);\n"
                            + "  }\n"
                            + "})",
                    FUTURE,
                    resultVar,
                    INVOCATIONS,
                    metaField,
                    argsVar,
                    chainFieldName(method, ordinal),
                    superCall,
                    mapVar,
                    mapVar,
                    Throwable.class,
                    catchVar,
                    FUTURE,
                    catchVar);
            // Map back to Future<T> via an unchecked cast on the element type.
            override.addStatement(
                    "return $N.map($N -> ($T) $N)",
                    resultVar,
                    backCastVar,
                    elementType(method.getReturnType()),
                    backCastVar);
        } else {
            // Non-Future return (sync): run the chain — the terminal wraps the synchronous super call
            // in a succeeded future — then unwrap the result. Because a sync-returning method has no
            // way to surface a deferred completion, the chain MUST settle synchronously. The
            // framework built-ins such as @Timed never defer, so the chain always completes here;
            // but the SPI is public, so a custom aspect could defer on a sync-returning method — the
            // FR-013-05 guard below makes that a loud failure (IllegalStateException) at the call site
            // rather than a silently-wrong value, a swallowed failure, or an NPE.
            TypeKind kind = method.getReturnType().getKind();
            if (kind == TypeKind.VOID) {
                override.addStatement(
                        "$T<Object> $N = $T.run(this, $N, $N, this.$N, () -> {\n"
                                + "  try {\n"
                                + "    $L;\n"
                                + "    return $T.succeededFuture((Object) null);\n"
                                + "  } catch ($T $N) {\n"
                                + "    return $T.failedFuture($N);\n"
                                + "  }\n"
                                + "})",
                        FUTURE,
                        resultVar,
                        INVOCATIONS,
                        metaField,
                        argsVar,
                        chainFieldName(method, ordinal),
                        superCall,
                        FUTURE,
                        Throwable.class,
                        catchVar,
                        FUTURE,
                        catchVar);
                emitSyncGuard(override, method, names, resultVar);
                // Void: the chain completed successfully; nothing to return.
                override.addStatement("return");
            } else {
                override.addStatement(
                        "$T<Object> $N = $T.run(this, $N, $N, this.$N, () -> {\n"
                                + "  try {\n"
                                + "    return $T.succeededFuture((Object) $L);\n"
                                + "  } catch ($T $N) {\n"
                                + "    return $T.failedFuture($N);\n"
                                + "  }\n"
                                + "})",
                        FUTURE,
                        resultVar,
                        INVOCATIONS,
                        metaField,
                        argsVar,
                        chainFieldName(method, ordinal),
                        FUTURE,
                        superCall,
                        Throwable.class,
                        catchVar,
                        FUTURE,
                        catchVar);
                emitSyncGuard(override, method, names, resultVar);
                // Cast to the boxed element type; auto-unboxing yields the primitive return when needed.
                override.addStatement("return ($T) $N.result()", returnType.box(), resultVar);
            }
        }

        return override.build();
    }

    /**
     * Emits the FR-013-05 sync-returning-method guard for the {@code result} future of a sync
     * override. A sync-returning method cannot surface a deferred completion, so the around-chain
     * MUST settle synchronously by the time the terminal call returns:
     * <ul>
     *   <li>if {@code result} is <em>not complete</em> — a custom aspect deferred completion on a
     *       sync-returning method — the override throws an {@link IllegalStateException} naming the
     *       method, rather than blocking, returning a wrong value, or NPEing on {@code result()};
     *   <li>if {@code result} <em>failed</em>, the cause is propagated: a {@link RuntimeException} or
     *       {@link Error} is rethrown as-is; a cause that is one of the method's declared checked
     *       exception types is also rethrown as-is (the override mirrors that {@code throws} clause,
     *       Bug N2); any other (undeclared checked) cause is wrapped in a {@link RuntimeException} so
     *       the sync method surfaces the failure to its caller.
     * </ul>
     *
     * <p>The completed-and-succeeded path falls through to the caller, which unwraps
     * {@code result.result()} (or returns, for {@code void}).
     *
     * @param override  the override method builder to append the guard statements to
     * @param method    the intercepted method, named in the {@code IllegalStateException} message; its
     *                  declared checked exception types are rethrown from the failed-chain branch as-is
     * @param names     the override's {@link NameAllocator} (already seeded with the user parameters and
     *                  the {@code result} local), used to allocate the guard's {@code cause}/{@code re}/
     *                  {@code err}/{@code checked<N>} bindings without colliding with a user parameter
     *                  (Bug R3-4)
     * @param resultVar the allocated name of the chain-result {@code Future<Object>} local
     */
    private static void emitSyncGuard(
            MethodSpec.Builder override, ExecutableElement method, NameAllocator names, String resultVar) {
        String causeVar = names.newName("cause");
        String reVar = names.newName("re");
        String errVar = names.newName("err");
        String qualifiedName =
                ((TypeElement) method.getEnclosingElement()).getQualifiedName() + "." + method.getSimpleName();
        override.beginControlFlow("if (!$N.isComplete())", resultVar);
        override.addStatement(
                "throw new $T($S)",
                IllegalStateException.class,
                "Aspect deferred completion on sync-returning method "
                        + qualifiedName
                        + "(); a sync-returning method requires a synchronous aspect (it cannot return a deferred result)");
        override.endControlFlow();
        override.beginControlFlow("if ($N.failed())", resultVar);
        override.addStatement("Throwable $N = $N.cause()", causeVar, resultVar);
        override.beginControlFlow("if ($N instanceof RuntimeException $N)", causeVar, reVar);
        override.addStatement("throw $N", reVar);
        override.endControlFlow();
        override.beginControlFlow("if ($N instanceof Error $N)", causeVar, errVar);
        override.addStatement("throw $N", errVar);
        override.endControlFlow();
        // Rethrow a cause that matches one of the method's declared checked exception types as-is —
        // the override declares the same throws clause, so this is type-safe (Bug N2). Distinct binding
        // names avoid pattern-variable shadowing when a method declares several checked types.
        List<? extends TypeMirror> thrown = method.getThrownTypes();
        for (int i = 0; i < thrown.size(); i++) {
            String checkedVar = names.newName("checked" + i);
            override.beginControlFlow("if ($N instanceof $T $N)", causeVar, TypeName.get(thrown.get(i)), checkedVar);
            override.addStatement("throw $N", checkedVar);
            override.endControlFlow();
        }
        override.addStatement("throw new $T($N)", RuntimeException.class, causeVar);
        override.endControlFlow();
    }

    // --- naming & type helpers ---

    /**
     * Names the nested {@code MethodMetadata} type for the intercepted method at the given ordinal:
     * {@code <Name>_<ordinal>_MethodMetadata}. The ordinal disambiguates overloaded methods that
     * share a simple name (Bug F4), matching the PRD A.5 ordinal convention.
     */
    private static String metaTypeName(ExecutableElement method, int ordinal) {
        return method.getSimpleName() + "_" + ordinal + "_MethodMetadata";
    }

    /**
     * Names the {@code static final MethodMetadata} constant for the intercepted method at the given
     * ordinal: {@code <NAME>_<ordinal>_META}. The ordinal disambiguates overloads (Bug F4).
     */
    private static String metaFieldName(ExecutableElement method, int ordinal) {
        return Identifiers.constantName(method.getSimpleName().toString()) + "_" + ordinal + "_META";
    }

    /**
     * Names the per-method interceptor chain field for the intercepted method at the given ordinal:
     * {@code <name>_<ordinal>$chain}. The ordinal disambiguates overloads (Bug F4).
     */
    private static String chainFieldName(ExecutableElement method, int ordinal) {
        return method.getSimpleName().toString() + "_" + ordinal + "$chain";
    }

    /**
     * Names the per-occurrence annotation literal constant for an aspect on the method at the given
     * ordinal: {@code <NAME>_<ordinal>_LITERAL} where {@code <NAME>} is the aspect simple name in
     * {@code SCREAMING_SNAKE_CASE}. Keying by method ordinal (not just aspect type) gives each
     * (method, aspect) occurrence its own constant so distinct attribute values are preserved (Bug
     * F2).
     */
    private static String occurrenceLiteralFieldName(AspectRef aspect, int ordinal) {
        return Identifiers.constantName(aspect.annotationType.getSimpleName().toString()) + "_" + ordinal + "_LITERAL";
    }

    private boolean isFuture(TypeMirror type) {
        TypeMirror unwrapped = ctx.unwrapFuture(type);
        return unwrapped != type;
    }

    private TypeName elementType(TypeMirror futureType) {
        return TypeName.get(ctx.unwrapFuture(futureType)).box();
    }

    private static FieldSpec buildStaticConstant(TypeName type, String name, CodeBlock initializer) {
        return FieldSpec.builder(type, name, Modifier.PRIVATE, Modifier.STATIC, Modifier.FINAL)
                .initializer(initializer)
                .build();
    }

    private void write(JavaFile file) {
        try {
            file.writeTo(ctx.filer());
        } catch (IOException e) {
            ctx.diagnostics()
                    .error(null, "Failed to write %s: %s", file.typeSpec().name(), e.getMessage());
        }
    }

    // --- value carriers ---

    /**
     * A distinct aspect annotation TYPE used by the bean, with its stable {@code AspectProvider<A>}
     * constructor-parameter name. The {@code representativeMirror} is used only to emit the
     * per-type {@code <Ann>$AopLiteral} CLASS (whose shape is identical regardless of attribute values);
     * the per-occurrence literal INSTANCE constants are built separately from each method's own
     * mirror (Bug F2).
     */
    private static final class AspectRef {
        final TypeElement annotationType;
        final AnnotationMirror representativeMirror;
        final String providerParamName;

        AspectRef(TypeElement annotationType, AnnotationMirror representativeMirror) {
            this.annotationType = annotationType;
            this.representativeMirror = representativeMirror;
            String simple = annotationType.getSimpleName().toString();
            this.providerParamName = Identifiers.sanitize(Introspector.decapitalize(simple)) + "Provider";
        }
    }

    /**
     * Identifies one aspect occurrence on a specific intercepted method — the (method ordinal,
     * aspect FQN) pair that keys the per-occurrence literal constant in the proxy (Bug F2).
     *
     * @param methodOrdinal the intercepted method's index among the bean's intercepted methods
     * @param aspectFqn     the aspect trigger annotation's fully-qualified name
     */
    private record OccurrenceKey(int methodOrdinal, String aspectFqn) {}

    /**
     * One aspect occurrence on a specific method, carrying its resolved ordering for chain sorting
     * and its own {@link AnnotationMirror} so the per-occurrence literal is built from THIS method's
     * attribute values (Bug F2).
     *
     * @param fqn      the aspect trigger annotation's fully-qualified name (the tie-breaker key)
     * @param ordering the resolved {@code @Aspect.ordering()} value (higher = outermost in the chain)
     * @param mirror   this occurrence's annotation mirror, read for its attribute values
     */
    private record AspectOnMethod(String fqn, int ordering, AnnotationMirror mirror) {}
}
