// SPDX-FileCopyrightText: 2026 Koivisto Capital Oy
// SPDX-License-Identifier: EUPL-1.2

package dev.vertique.examples.services.codegen;

import static io.restassured.RestAssured.given;
import static org.hamcrest.Matchers.equalTo;
import static org.hamcrest.Matchers.notNullValue;

import dev.vertique.application.test.VertiqueAppExtension;
import io.restassured.RestAssured;
import io.restassured.filter.log.RequestLoggingFilter;
import io.restassured.filter.log.ResponseLoggingFilter;
import io.restassured.http.ContentType;
import io.vertx.core.json.JsonObject;
import java.util.concurrent.TimeUnit;
import org.junit.jupiter.api.AfterAll;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.Timeout;
import org.junit.jupiter.api.extension.RegisterExtension;

/**
 * Integration tests for the example-services-codegen module.
 *
 * <p>Boots the application via {@link VertiqueAppExtension} (using the factory generated by the
 * {@code @VertiqueApp} annotation processor) and verifies end-to-end behavior of both service
 * contracts registered via the CG-005-generated {@code GeneratedServicesModule}:
 * <ul>
 *   <li>{@code BillingService} — direct-impl path ({@code BillingServiceImpl})</li>
 *   <li>{@code ShippingService} — handler-pattern path ({@code ShippingServiceHandler})</li>
 * </ul>
 *
 * <p>Each test is independent — they share no mutable state and can run in any order.
 */
@Timeout(value = 20, unit = TimeUnit.SECONDS)
public class BillingShippingIT {

    @RegisterExtension
    static final VertiqueAppExtension app = VertiqueAppExtension.forFactory(new AppComponentVertiqueComponentFactory())
            .withConfig(new JsonObject()
                    .put("http", new JsonObject().put("port", 0).put("host", "127.0.0.1"))
                    .put("management", new JsonObject().put("enabled", false)));

    /**
     * Configures RestAssured base URI, port, and logging filters.
     */
    @BeforeAll
    static void setUp() {
        RestAssured.baseURI = "http://127.0.0.1";
        RestAssured.port = app.httpPort();
        RestAssured.filters(new RequestLoggingFilter(), new ResponseLoggingFilter());
    }

    /**
     * Resets RestAssured configuration after all tests complete.
     */
    @AfterAll
    static void tearDown() {
        RestAssured.reset();
    }

    /**
     * Verifies that the billing charge endpoint processes a request and returns a receipt
     * with the expected order ID, amount, and currency via the direct-impl codegen path.
     */
    @Test
    void shouldChargeViaBillingService() {
        given().contentType(ContentType.JSON)
                .body("{\"orderId\":\"order-001\",\"amountCents\":4999,\"currency\":\"USD\"}")
                .when()
                .post("/billing/charge")
                .then()
                .statusCode(200)
                .body("receiptId", notNullValue())
                .body("orderId", equalTo("order-001"))
                .body("amountCents", equalTo(4999))
                .body("currency", equalTo("USD"));
    }

    /**
     * Verifies that the shipping dispatch endpoint processes a request and returns a receipt
     * with the expected order ID and destination via the handler-pattern codegen path.
     */
    @Test
    void shouldShipViaShippingService() {
        given().contentType(ContentType.JSON)
                .body("{\"orderId\":\"order-002\",\"destinationCity\":\"Helsinki\"}")
                .when()
                .post("/shipping/ship")
                .then()
                .statusCode(200)
                .body("trackingId", notNullValue())
                .body("orderId", equalTo("order-002"))
                .body("destinationCity", equalTo("Helsinki"));
    }

    /**
     * Verifies that the one-way dispatch notification endpoint returns 204 with no body,
     * demonstrating the {@code @OneWay} fire-and-forget pattern.
     */
    @Test
    void shouldSendDispatchNotificationOneWay() {
        given().when().post("/shipping/notify?orderId=order-002").then().statusCode(204);
    }
}
