// SPDX-FileCopyrightText: 2026 Koivisto Capital Oy
// SPDX-License-Identifier: EUPL-1.2

package dev.vertique.examples.services.codegen;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;

import dev.vertique.application.test.VertiqueAppExtension;
import dev.vertique.core.util.GeneratedNames;
import dev.vertique.examples.services.codegen.service.BillingService;
import dev.vertique.examples.services.codegen.service.ShippingService;
import io.vertx.core.json.JsonObject;
import java.lang.reflect.Proxy;
import java.util.concurrent.TimeUnit;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.Timeout;
import org.junit.jupiter.api.extension.RegisterExtension;

/**
 * CG-015 activation proof: verifies that {@code ServiceClientFactory.create()} selects the
 * generated {@code _ServiceClientProxy} companion for each service contract, rather than falling
 * back to a JDK dynamic proxy, inside a real, Dagger-wired application.
 *
 * <p>Boots the application via {@link VertiqueAppExtension} exactly like {@link BillingShippingIT}
 * (using the factory generated by the {@code @VertiqueApp} annotation processor), then obtains the
 * {@link BillingService} and {@link ShippingService} client proxies through the {@link
 * AppComponent} accessors ({@link AppComponent#billingService()}, {@link
 * AppComponent#shippingService()}) and asserts each client's runtime class is the companion class
 * emitted for its contract by {@code vertique-codegen-services} — the same companion class the
 * annotation processor inherited from {@code vertique-example-parent} already emits into the
 * example's {@code generated-sources}.
 */
@Timeout(value = 20, unit = TimeUnit.SECONDS)
public class GeneratedClientSelectionIT {

    @RegisterExtension
    static final VertiqueAppExtension app = VertiqueAppExtension.forFactory(new AppComponentVertiqueComponentFactory())
            .withConfig(new JsonObject()
                    .put("http", new JsonObject().put("port", 0).put("host", "127.0.0.1"))
                    .put("management", new JsonObject().put("enabled", false)));

    private static AppComponent component;

    /**
     * Captures the started application's {@link AppComponent} for use by every test.
     */
    @BeforeAll
    static void setUp() {
        component = app.component();
    }

    /**
     * Verifies that the injected {@link BillingService} client is the generated
     * {@code BillingService_ServiceClientProxy} companion, not a JDK dynamic proxy.
     */
    @Test
    @DisplayName("selects the generated BillingService companion, not a JDK dynamic proxy")
    void shouldSelectGeneratedCompanionForBillingService() {
        BillingService client = component.billingService();

        assertEquals(
                GeneratedNames.companionFqn(BillingService.class, "_ServiceClientProxy"),
                client.getClass().getName());
        assertFalse(Proxy.isProxyClass(client.getClass()));
    }

    /**
     * Verifies that the injected {@link ShippingService} client is the generated
     * {@code ShippingService_ServiceClientProxy} companion, not a JDK dynamic proxy.
     */
    @Test
    @DisplayName("selects the generated ShippingService companion, not a JDK dynamic proxy")
    void shouldSelectGeneratedCompanionForShippingService() {
        ShippingService client = component.shippingService();

        assertEquals(
                GeneratedNames.companionFqn(ShippingService.class, "_ServiceClientProxy"),
                client.getClass().getName());
        assertFalse(Proxy.isProxyClass(client.getClass()));
    }
}
