// SPDX-FileCopyrightText: 2026 Koivisto Capital Oy
// SPDX-License-Identifier: EUPL-1.2

package dev.vertique.rest.openapi.docs.schema;

import com.fasterxml.jackson.databind.node.ObjectNode;
import dev.vertique.json.schema.AnnotationJsonSchemaGenerator;
import dev.vertique.json.schema.HiddenMember;
import dev.vertique.json.schema.HidingMarker;
import dev.vertique.json.schema.OutputRename;
import dev.vertique.rest.core.RestConfigurationException;
import io.vertx.core.json.JsonObject;
import jakarta.annotation.Nullable;
import java.lang.reflect.Type;
import java.util.List;

/**
 * Generates the output-direction schema of one published response type and checks it for the
 * constructs a published schema may not hold.
 *
 * <p>The schema is generated by the output generator of the operation's profile ({@link
 * OutputGenerators}), read into a tree the document owns by the same path captured input schemas
 * take ({@link SchemaTrees#tree}), and checked by {@link SchemaRefusals}. Nothing is published
 * here: the checked schema is relocated into a component only when the document is written.
 *
 * <p>After generating the schema, the same generator reports the type's renamed members and its
 * hidden members, in that order. A member whose serialized name differs from the name the schema
 * describes fails publication, naming the first such member's declaring type, member, serialized
 * name, and schema name. A described member or type carrying a hiding marker the output generator
 * does not honor fails publication, naming the first reported entry, its marker, and the one fix its
 * position implies; the generator's output is never changed, so the member is not dropped.
 *
 * <p>Any exception from resolving the profile, building its generator, generating the schema, or
 * reporting its renamed or hidden members fails publication with a {@link
 * RestConfigurationException} that names the document's configuration path, the application and its
 * mount, the operation, what was being published, and its status, and keeps the original exception
 * as its cause. No message carries schema text.
 *
 * <p>Internal to the OpenAPI documentation module; not an application API.
 */
public final class OutputSchemas {

    private OutputSchemas() {}

    /**
     * Generates and checks the output schema of one published type.
     *
     * @param prefix the failure-message prefix naming the document's configuration path, the
     *     application, and its mount
     * @param subject the failure-message subject naming the application and its mount, used by the
     *     refused-construct check
     * @param generators the output generators of the document's assembly
     * @param target the published type and where it is published
     * @return the checked schema, to publish as the target's component
     * @throws RestConfigurationException when the schema cannot be generated, describes a member
     *     under a name other than its serialized name, describes a member or type carrying a hiding
     *     marker, or holds a refused construct
     */
    public static SchemaEmbedder.CheckedSchema check(
            String prefix, String subject, OutputGenerators generators, Target target) {
        AnnotationJsonSchemaGenerator generator;
        String text;
        try {
            generator = generators.generator(target.profileId());
            text = generator.generateCanonical(target.type());
        } catch (RuntimeException e) {
            throw failure(prefix, target, "generating it in output direction failed", e);
        }
        List<OutputRename> renames;
        try {
            renames = generator.outputRenames(target.type());
        } catch (RuntimeException e) {
            throw failure(prefix, target, "inspecting it for renamed members failed", e);
        }
        if (!renames.isEmpty()) {
            throw renamed(prefix, target, renames.get(0));
        }
        List<HiddenMember> hidden;
        try {
            hidden = generator.hiddenMembers(target.type());
        } catch (RuntimeException e) {
            throw failure(prefix, target, "inspecting it for hidden members failed", e);
        }
        if (!hidden.isEmpty()) {
            throw hidden(prefix, target, hidden.get(0));
        }
        ObjectNode tree = SchemaTrees.tree(new JsonObject(text));
        SchemaPublicationSubject publicationSubject = target.publicationSubject();
        SchemaRefusals.check(subject, publicationSubject, tree);
        return new SchemaEmbedder.CheckedSchema(publicationSubject, tree);
    }

    /** Builds the refusal of an output type whose member is described under another name. */
    private static RestConfigurationException renamed(String prefix, Target target, OutputRename rename) {
        return new RestConfigurationException(prefix + ": operation '" + target.operationId() + "' publishes "
                + rename.declaringType() + " as an output type of status " + target.status() + "; its member '"
                + rename.member() + "' is serialized as '" + rename.serializedName() + "' but described as '"
                + rename.schemaName() + "', so the document would describe a property the response never carries;"
                + " make @Schema(name) agree with the serialized name or remove it");
    }

    /** Builds the refusal of an output type that describes a member or type carrying a hiding marker. */
    private static RestConfigurationException hidden(String prefix, Target target, HiddenMember entry) {
        return new RestConfigurationException(prefix + ": operation '" + target.operationId()
                + "' publishes an output type of status " + target.status() + " that describes "
                + HiddenMemberRefusal.what(entry) + ", which carries " + HiddenMemberRefusal.marker(entry.marker())
                + "; " + hiddenFix(entry));
    }

    /** Chooses the fix for a hidden output entry from its position and marker only. */
    private static String hiddenFix(HiddenMember entry) {
        if (entry.member() == null) {
            return "the output generator does not hide a type; declare @Schema(hidden = true) on the field or"
                    + " getter of each member that references it, or hide the operation";
        }
        if (entry.hideableBySchemaHidden()) {
            if (entry.marker() == HidingMarker.HIDDEN) {
                return "the output generator ignores @Hidden; declare @Schema(hidden = true) on the property's own"
                        + " field or getter";
            }
            return "the output generator ignores @Schema(hidden = true) where it is declared; declare it directly"
                    + " on the property's own field or getter, not through a bundle or mix-in";
        }
        return "the output generator cannot leave this member out where the document describes it (an enum"
                + " constant or @JsonUnwrapped content); remove it from the published type, or hide the operation";
    }

    /**
     * Builds the failure of one published type.
     *
     * @param prefix the failure-message prefix
     * @param target the published type
     * @param reason why the type cannot be published, without schema text
     * @param cause the original exception
     * @return the failure
     */
    static RestConfigurationException failure(String prefix, Target target, String reason, Throwable cause) {
        return new RestConfigurationException(
                prefix + ": operation '" + target.operationId() + "' cannot publish the output " + target.what()
                        + " of status " + target.status() + ": " + reason,
                cause);
    }

    /**
     * One published output type and where it is published.
     *
     * @param operationId the runtime id of the operation
     * @param status the status a failure names
     * @param header the name of the header whose schema the type is, or {@code null} for a content
     *     schema
     * @param keySuffix the part of the component key after the operation id, before replacement
     * @param type the resolved type to generate
     * @param profileId the operation's resolved output profile id
     */
    public record Target(
            String operationId, String status, @Nullable String header, String keySuffix, Type type, String profileId) {

        /**
         * Returns how a failure names the published schema.
         *
         * @return {@code content schema}, or {@code header '<name>' schema}
         */
        String what() {
            return header == null ? "content schema" : "header '" + header + "' schema";
        }

        /**
         * Returns the subject of the published schema, which names its component key and its
         * messages.
         *
         * @return the response schema's subject, whose collision phrase names the status and the
         *     operation
         */
        SchemaPublicationSubject publicationSubject() {
            String noun = header == null
                    ? "output schema of status " + status
                    : "output schema of header '" + header + "' of status " + status;
            return SchemaPublicationSubject.output(operationId, noun, keySuffix);
        }
    }
}
