// SPDX-FileCopyrightText: 2026 Koivisto Capital Oy
// SPDX-License-Identifier: EUPL-1.2

/**
 * Example application demonstrating typed delayed job contracts with webhook delivery. There is no
 * hand-written {@code MainVerticle}: the entry point is
 * {@link dev.vertique.examples.webhook.AppComponent}, the root Dagger {@code @Component} annotated
 * {@link dev.vertique.application.VertiqueApp} and extending
 * {@link dev.vertique.application.VertiqueApplicationComponent}. The
 * {@code vertique-codegen-application} annotation processor generates
 * {@code AppComponentVertiqueComponentFactory} (and its {@code META-INF/services} registration) for
 * that component; at runtime the launcher's bootstrap verticle discovers that factory and the
 * host-neutral lifecycle runner ({@code VertiqueApplicationBootstrap}) builds the component from the
 * pre-resolved {@code config()} tree and drives startup per lifecycle phase. The runner reproduces
 * the legacy four-phase choreography: Jackson configuration via {@code CoreLifecycleStepsModule}
 * ({@code CONFIGURE}); the {@code MIGRATE}-phase {@code FlywayMigrationStartupStep} contributed by
 * {@code DbFlywayModule} runs the Flyway migration before any verticle deploys, ensuring the job
 * tables exist before any poller starts (replacing the manual {@code migrationRunner().migrate(vertx)}
 * call); the management verticle ({@code INFRA}); the event-bus service verticles via the
 * {@code SERVICES}-phase {@code ServiceDeploymentStartupStep} contributed by {@code DispatchModule}
 * followed by the framework background workers — delayed-job pollers, cron lifecycle —
 * ({@code SERVICES}); then the {@link dev.vertique.rest.core.router.HttpVerticle} ({@code EDGE}) —
 * preserving the legacy migrate &rarr; {@code INFRA} &rarr; service-dispatch-deploy &rarr;
 * {@code SERVICES} &rarr; {@code EDGE} ordering.
 *
 * <p>{@link dev.vertique.examples.webhook.AppComponent} wires together {@code VertxModule},
 * {@code RestModule}, {@code RestClientModule}, {@code DispatchModule}, {@code DbModule},
 * {@code DbPostgresqlModule}, {@code DbFlywayModule}, {@code DelayedJobModule}, {@code AppModule},
 * and {@code WebhookModule}. This module serves as a reference implementation for the typed delayed
 * job contract pattern: a {@code @DelayedJob} interface whose static proxy is generated by
 * {@code vertique-codegen-delayed-job}, enqueued and executed durably against PostgreSQL.
 */
package dev.vertique.examples.webhook;
