// SPDX-FileCopyrightText: 2026 Koivisto Capital Oy
// SPDX-License-Identifier: EUPL-1.2

package dev.vertique.job.delayed;

import com.fasterxml.jackson.annotation.JsonAutoDetect;
import dev.vertique.core.context.DurableMetadata;
import java.time.Instant;
import lombok.Builder;
import lombok.Getter;
import lombok.experimental.Accessors;

/**
 * Immutable value object describing a delayed job to enqueue.
 *
 * <p>Use the {@link #builder()} to construct instances. The only required field is
 * {@link #handler} — all others have sensible defaults.
 *
 * <p>Example usage:
 * <pre>{@code
 * DelayedJob job = DelayedJob.builder()
 *     .handler("send-welcome-email")
 *     .payload(new WelcomeEmailPayload(userId, email))
 *     .runAt(Instant.now().plusSeconds(60))
 *     .maxAttempts(5)
 *     .build();
 * delayedJobService.enqueue(job);
 * }</pre>
 */
@Getter
@Builder
@Accessors(fluent = true)
@JsonAutoDetect(fieldVisibility = JsonAutoDetect.Visibility.ANY, getterVisibility = JsonAutoDetect.Visibility.NONE)
public class DelayedJob {

    /**
     * The handler name. Maps to the event bus address {@code job.delayed.<handler>}.
     * Must correspond to a method annotated with {@link DelayedJobHandlerMethod}.
     */
    private final String handler;

    /**
     * The typed job data passed to the handler. May be any Jackson-serializable object.
     * Stored as JSONB in the database.
     */
    @Builder.Default
    private final Object payload = null;

    /**
     * When to execute this job. {@code null} or a past time causes the job to become eligible
     * for claiming immediately. A future time sets {@code scheduled_at} to that instant;
     * the job is still created as {@code ENQUEUED}, but the poller's claim query filters by
     * {@code scheduled_at <= NOW()}, so it will not be claimed until the scheduled time passes.
     */
    @Builder.Default
    private final Instant runAt = null;

    /**
     * The logical queue to place this job on. The {@link DelayedJobPoller} for the matching
     * queue will claim and dispatch this job. Defaults to {@code "default"}.
     */
    @Builder.Default
    private final String queue = "default";

    /**
     * Priority for claiming order. Higher values are claimed first by the poller.
     * Defaults to {@code 0}.
     */
    @Builder.Default
    private final int priority = 0;

    /**
     * Maximum number of execution attempts before the job is moved to dead-letter state.
     * Defaults to {@code 3}.
     */
    @Builder.Default
    private final int maxAttempts = 3;

    /**
     * Logical job identifier, stable across retries. If {@code null}, a UUID-based identifier
     * is auto-generated by {@link DelayedJobService} at enqueue time.
     */
    @Builder.Default
    private final String jobId = null;

    /**
     * Durable context-propagation metadata as a {@link DurableMetadata} namespaced document.
     * Defaults to {@link DurableMetadata#empty()}.
     *
     * <p>{@code DelayedJobService.toExecution(...)} merges this document with any ambient
     * holder-bound durable context via
     * {@code DurableContextPropagator.mergeCaptured(metadata, DispatchBoundary.DELAYED_JOB)} —
     * namespace collisions throw per FR-CTX-063. The merged result is persisted into
     * {@code job_executions.metadata JSONB} via {@link DurableMetadata#toCarrier()}, then decoded
     * back into the outgoing service envelope's caller-overrides by
     * {@code DelayedJobPoller.dispatch(...)} on poll.
     *
     * <p>Callers who have already captured + merged their durable context themselves (workflow
     * timer create / recovery) should use {@code DelayedJobOptions.premergedMetadata(...)}
     * through the typed-proxy path instead, which routes to a no-recapture enqueue variant.
     */
    @Builder.Default
    private final DurableMetadata metadata = DurableMetadata.empty();
}
