// SPDX-FileCopyrightText: 2026 Koivisto Capital Oy
// SPDX-License-Identifier: EUPL-1.2

package dev.vertique.examples.hello.resource;

import dagger.Module;
import dagger.Provides;
import dagger.multibindings.IntoSet;
import jakarta.ws.rs.ext.ExceptionMapper;

/**
 * Dagger module for JAX-RS extension bindings in the example-hello application.
 *
 * <p>JAX-RS resource bindings ({@code @JaxRsResources}) are no longer declared here — they are
 * auto-generated by {@code vertique-codegen-dagger}'s {@code AutoWireProcessor} into
 * {@code GeneratedJaxRsResourcesModule}, which is wired into {@link
 * dev.vertique.examples.hello.AppComponent} instead.
 *
 * <p>This module retains non-resource bindings such as {@link ExceptionMapper} contributions.
 */
@Module
public class ResourceModule {

    /**
     * Contributes the {@link GreetingLimitExceptionMapper} to the {@code Set<ExceptionMapper<?>>}
     * multibinding so the framework registers it in the
     * {@link dev.vertique.rest.jaxrs.ExceptionMapperRegistry}.
     *
     * @param mapper the mapper instance provided by Dagger
     * @return the mapper as a typed {@link ExceptionMapper} for the multibinding set
     */
    @Provides
    @IntoSet
    ExceptionMapper<?> greetingLimitExceptionMapper(GreetingLimitExceptionMapper mapper) {
        return mapper;
    }
}
