// SPDX-FileCopyrightText: 2026 Koivisto Capital Oy
// SPDX-License-Identifier: EUPL-1.2

package dev.vertique.examples.hello.resource;

import dagger.Module;

/**
 * Dagger module for JAX-RS extension bindings in the example-hello application.
 *
 * <p>JAX-RS resource bindings ({@code @JaxRsResources}) are no longer declared here — they are
 * auto-generated by {@code vertique-codegen-dagger}'s {@code AutoWireProcessor} into
 * {@code GeneratedJaxRsResourcesModule}, which is wired into {@link
 * dev.vertique.examples.hello.AppComponent} instead.
 *
 * <p>Retained as an explicit extension point for non-resource JAX-RS bindings; it currently
 * contributes none. The prototype {@code GreetingLimitExceptionMapper} binding this module used to
 * hold was retired (T013): {@code HelloResource#greetLimited} now carries {@code @RateLimited} and
 * relies entirely on {@code RestRateLimitModule}'s own {@code 429}/{@code 503} exception mappers
 * (installed on {@link dev.vertique.examples.hello.AppComponent}), never a hand-rolled mapper.
 */
@Module
public class ResourceModule {}
