#!/usr/bin/env bash
# SPDX-FileCopyrightText: 2026 Koivisto Capital Oy
# SPDX-License-Identifier: EUPL-1.2

set -euo pipefail

readonly warmup_count=2
readonly sample_count=7
readonly overhead_budget_percent=15

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
repository_root="$(cd "$script_dir/.." && pwd)"
maven_wrapper="$repository_root/mvnw"
benchmark_root="$repository_root/target/codegen-benchmark"
run_id="run-$(date -u +%Y%m%dT%H%M%SZ)-$$"
run_root="$benchmark_root/$run_id"
workspaces_root="$run_root/workspaces"
raw_root="$run_root/raw"
logs_root="$run_root/logs"
environment_report="$run_root/environment.txt"
summary_report="$run_root/summary.tsv"
dry_run=false
dependencies_prepared=false

usage() {
    cat <<'EOF'
Usage: ./scripts/measure-codegen-facade.sh [--dependencies-prepared] [--dry-run]

Measures clean Maven compilation for three representative applications using:
  1. their manually selected Vertique processor leaves; and
  2. dev.vertique:vertique-codegen-all.

The benchmark always uses Maven 3.9.9, two unrecorded warmups, seven measured
samples per configuration, and a 15% facade-median overhead gate.

Options:
  --dependencies-prepared
             Skip reactor installation and dependency:go-offline. Use only when
             those exact preparation steps completed immediately before this run.
  --dry-run  Generate isolated benchmark POMs and print preparation/sampling work
             without invoking Maven or recording timing samples.
  -h, --help Show this help.

Environment:
  CODEGEN_BENCHMARK_REVISION
      Reactor version used for the generated benchmark children. Defaults to
      the root POM's revision property.
EOF
}

while [[ $# -gt 0 ]]; do
    case "$1" in
        --dry-run)
            dry_run=true
            ;;
        --dependencies-prepared)
            dependencies_prepared=true
            ;;
        -h | --help)
            usage
            exit 0
            ;;
        *)
            echo "Unknown argument: $1" >&2
            usage >&2
            exit 2
            ;;
    esac
    shift
done

if [[ ! -x "$maven_wrapper" ]]; then
    echo "Maven wrapper is not executable: $maven_wrapper" >&2
    exit 1
fi

resolve_reactor_revision() {
    local root_revision

    if [[ -n "${CODEGEN_BENCHMARK_REVISION:-}" ]]; then
        printf '%s\n' "$CODEGEN_BENCHMARK_REVISION"
        return
    fi

    root_revision="$(awk '
        /<revision>/ {
            line = $0
            sub(/^.*<revision>[[:space:]]*/, "", line)
            sub(/[[:space:]]*<\/revision>.*$/, "", line)
            print line
            exit
        }
    ' "$repository_root/pom.xml")"
    if [[ -z "$root_revision" || "$root_revision" == *'${'* ]]; then
        echo "Cannot derive a concrete reactor revision from $repository_root/pom.xml" >&2
        exit 1
    fi

    printf '%s\n' "$root_revision"
}

reactor_revision="$(resolve_reactor_revision)"
benchmark_maven_opts="-Xms512m -Xmx2g -XX:+UseG1GC"
unset JAVA_TOOL_OPTIONS _JAVA_OPTIONS JDK_JAVA_OPTIONS MAVEN_ARGS
export MAVEN_OPTS="$benchmark_maven_opts"

mkdir -p "$workspaces_root" "$raw_root" "$logs_root"

xml_escape() {
    sed -e 's/&/\&amp;/g' -e 's/</\&lt;/g' -e 's/>/\&gt;/g' -e 's/"/\&quot;/g'
}

extract_dependencies() {
    local source_pom="$1"

    awk '
        !capturing && /^[[:space:]]*<dependencies>[[:space:]]*$/ {
            capturing = 1
        }
        capturing {
            print
        }
        capturing && /^[[:space:]]*<\/dependencies>[[:space:]]*$/ {
            exit
        }
    ' "$source_pom"
}

write_benchmark_pom() {
    local application="$1"
    local source_directory="$2"
    local configuration="$3"
    shift 3

    local workspace="$workspaces_root/$application-$configuration"
    local source_pom="$repository_root/$source_directory/pom.xml"
    local benchmark_pom="$workspace/pom.xml"
    local escaped_parent_path
    local escaped_reactor_revision
    local processor_artifact

    if [[ ! -f "$source_pom" ]]; then
        echo "Representative application POM does not exist: $source_pom" >&2
        exit 1
    fi

    mkdir -p "$workspace"
    ln -s "$repository_root/$source_directory/src" "$workspace/src"
    escaped_parent_path="$(printf '%s' "$repository_root/pom.xml" | xml_escape)"
    escaped_reactor_revision="$(printf '%s' "$reactor_revision" | xml_escape)"

    {
        cat <<EOF
<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by scripts/measure-codegen-facade.sh; do not commit. -->
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>dev.vertique</groupId>
        <artifactId>vertique-parent</artifactId>
        <version>$escaped_reactor_revision</version>
        <relativePath>$escaped_parent_path</relativePath>
    </parent>
    <artifactId>codegen-benchmark-$application-$configuration</artifactId>
    <name>Codegen benchmark: $application ($configuration)</name>
EOF
        extract_dependencies "$source_pom"
        cat <<'EOF'
    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <configuration>
                    <annotationProcessorPaths combine.children="append">
EOF
        for processor_artifact in "$@"; do
            cat <<EOF
                        <path>
                            <groupId>dev.vertique</groupId>
                            <artifactId>$processor_artifact</artifactId>
                            <version>\${project.version}</version>
                        </path>
EOF
        done
        cat <<'EOF'
                    </annotationProcessorPaths>
                </configuration>
            </plugin>
        </plugins>
    </build>
</project>
EOF
    } >"$benchmark_pom"
}

write_benchmark_pair() {
    local application="$1"
    local source_directory="$2"
    shift 2

    write_benchmark_pom "$application" "$source_directory" manual "$@"
    write_benchmark_pom "$application" "$source_directory" facade vertique-codegen-all
}

print_command() {
    local argument

    printf 'DRY-RUN: MAVEN_OPTS=%q' "$MAVEN_OPTS"
    for argument in "$@"; do
        printf ' %q' "$argument"
    done
    printf '\n'
}

run_maven() {
    local log_file="$1"
    shift

    if $dry_run; then
        print_command "$maven_wrapper" -ntp "-Drevision=$reactor_revision" "$@"
        return 0
    fi

    if ! "$maven_wrapper" -ntp "-Drevision=$reactor_revision" "$@" >"$log_file" 2>&1; then
        echo "Maven command failed; tail of $log_file:" >&2
        tail -n 80 "$log_file" >&2
        return 1
    fi
}

verify_maven_version() {
    local version_output
    local detected_version

    version_output="$("$maven_wrapper" -v 2>&1)"
    detected_version="$(printf '%s\n' "$version_output" | awk '/^Apache Maven / { print $3; exit }')"
    if [[ "$detected_version" != "3.9.9" ]]; then
        echo "CODEGEN-014 benchmark requires Maven 3.9.9; detected '${detected_version:-unknown}'" >&2
        printf '%s\n' "$version_output" >&2
        exit 1
    fi

    printf '%s\n' "$version_output"
}

write_environment_report() {
    local maven_environment="$1"

    {
        printf 'run_id=%s\n' "$run_id"
        printf 'started_utc=%s\n' "$(date -u +%Y-%m-%dT%H:%M:%SZ)"
        printf 'repository_root=%s\n' "$repository_root"
        printf 'reactor_revision=%s\n' "$reactor_revision"
        printf 'maven_opts=%s\n' "$MAVEN_OPTS"
        printf 'warmups_per_configuration=%s\n' "$warmup_count"
        printf 'measured_samples_per_configuration=%s\n' "$sample_count"
        printf 'overhead_budget_percent=%s\n' "$overhead_budget_percent"
        printf 'dependencies_prepared_externally=%s\n' "$dependencies_prepared"
        printf 'uname=%s\n' "$(uname -a)"
        printf '\n%s\n' "$maven_environment"
    } >"$environment_report"
}

prepare_dependencies() {
    local workspace_pom

    run_maven "$logs_root/reactor-install.log" \
        -Dmaven.test.skip=true \
        -Djacoco.skip=true \
        -pl \
        "vertique-codegen/vertique-codegen-all,examples/vertique-example-hello,examples/vertique-example-services-codegen,examples/vertique-example-aop" \
        -am \
        install

    for workspace_pom in "$workspaces_root"/*/pom.xml; do
        run_maven "$logs_root/$(basename "$(dirname "$workspace_pom")")-go-offline.log" \
            -f "$workspace_pom" \
            -Dmaven.test.skip=true \
            -Djacoco.skip=true \
            dependency:go-offline
    done
}

warm_os_cache() {
    local source_directory

    for source_directory in \
        "$repository_root/examples/vertique-example-hello/src" \
        "$repository_root/examples/vertique-example-services-codegen/src" \
        "$repository_root/examples/vertique-example-aop/src" \
        "$workspaces_root"; do
        if [[ -d "$source_directory" ]]; then
            find "$source_directory" -type f -exec cat {} + >/dev/null
        fi
    done
}

now_nanoseconds() {
    local timestamp

    timestamp="$(date +%s%N 2>/dev/null || true)"
    if [[ "$timestamp" =~ ^[0-9]{16,}$ ]]; then
        printf '%s\n' "$timestamp"
        return
    fi

    if command -v python3 >/dev/null 2>&1; then
        python3 -c 'import time; print(time.monotonic_ns())'
        return
    fi

    if command -v perl >/dev/null 2>&1; then
        perl -MTime::HiRes=time -e 'printf "%.0f\n", time() * 1_000_000_000'
        return
    fi

    echo "A nanosecond clock requires date(1) with %N support, python3, or perl" >&2
    exit 1
}

last_elapsed_ms=0

compile_once() {
    local application="$1"
    local configuration="$2"
    local phase="$3"
    local iteration="$4"
    local workspace="$workspaces_root/$application-$configuration"
    local log_file="$logs_root/$application-$configuration-$phase-$iteration.log"
    local started_ns
    local finished_ns

    started_ns="$(now_nanoseconds)"
    run_maven "$log_file" \
        --offline \
        -f "$workspace/pom.xml" \
        -DskipTests \
        -Djacoco.skip=true \
        clean \
        compile
    finished_ns="$(now_nanoseconds)"

    last_elapsed_ms=$(((finished_ns - started_ns) / 1000000))
}

record_sample() {
    local application="$1"
    local configuration="$2"
    local sample="$3"
    local sample_file="$raw_root/$application-$configuration.tsv"

    compile_once "$application" "$configuration" "sample" "$sample"
    printf '%s\t%s\n' "$sample" "$last_elapsed_ms" >>"$sample_file"
    printf '  %-12s %-6s sample %d/%d: %d ms\n' \
        "$application" "$configuration" "$sample" "$sample_count" "$last_elapsed_ms"
}

median_ms() {
    local sample_file="$1"

    tail -n +2 "$sample_file" | cut -f2 | sort -n | sed -n '4p'
}

benchmark_application() {
    local application="$1"
    local iteration
    local configuration
    local sample_file

    echo "Benchmarking $application"
    for configuration in manual facade; do
        sample_file="$raw_root/$application-$configuration.tsv"
        printf 'sample\telapsed_ms\n' >"$sample_file"
    done

    for ((iteration = 1; iteration <= warmup_count; iteration++)); do
        compile_once "$application" manual warmup "$iteration"
        compile_once "$application" facade warmup "$iteration"
    done

    for ((iteration = 1; iteration <= sample_count; iteration++)); do
        if ((iteration % 2 == 1)); then
            record_sample "$application" manual "$iteration"
            record_sample "$application" facade "$iteration"
        else
            record_sample "$application" facade "$iteration"
            record_sample "$application" manual "$iteration"
        fi
    done
}

evaluate_application() {
    local application="$1"
    local manual_median
    local facade_median
    local overhead_percent
    local status

    manual_median="$(median_ms "$raw_root/$application-manual.tsv")"
    facade_median="$(median_ms "$raw_root/$application-facade.tsv")"

    if [[ -z "$manual_median" || -z "$facade_median" || "$manual_median" -le 0 ]]; then
        echo "Invalid timing samples for $application" >&2
        return 1
    fi

    overhead_percent="$(awk -v manual="$manual_median" -v facade="$facade_median" \
        'BEGIN { printf "%.2f", ((facade / manual) - 1) * 100 }')"
    status="PASS"
    if ((facade_median * 100 > manual_median * (100 + overhead_budget_percent))); then
        status="FAIL"
    fi

    printf '%s\t%s\t%s\t%s\t%s\n' \
        "$application" "$manual_median" "$facade_median" "$overhead_percent" "$status" \
        >>"$summary_report"
    printf '%-12s manual=%6d ms facade=%6d ms overhead=%7s%% %s\n' \
        "$application" "$manual_median" "$facade_median" "$overhead_percent" "$status"

    [[ "$status" == "PASS" ]]
}

write_benchmark_pair \
    hello-jaxrs \
    examples/vertique-example-hello \
    vertique-codegen-jaxrs \
    vertique-codegen-dagger \
    vertique-codegen-application

write_benchmark_pair \
    services \
    examples/vertique-example-services-codegen \
    vertique-codegen-jaxrs \
    vertique-codegen-dagger \
    vertique-codegen-services \
    vertique-codegen-application

write_benchmark_pair \
    aop \
    examples/vertique-example-aop \
    vertique-codegen-aop

if $dry_run; then
    if ! $dependencies_prepared; then
        prepare_dependencies
    fi
    echo "DRY-RUN: warm representative source and generated-POM files into the OS cache"
    echo "DRY-RUN: run $warmup_count unrecorded warmups and $sample_count measured offline clean compiles"
    echo "DRY-RUN: compare each facade median against its manual median with a $overhead_budget_percent% budget"
    echo "Generated benchmark workspaces: $workspaces_root"
    exit 0
fi

maven_environment="$(verify_maven_version)"
write_environment_report "$maven_environment"
if ! $dependencies_prepared; then
    prepare_dependencies
fi
warm_os_cache

benchmark_application hello-jaxrs
benchmark_application services
benchmark_application aop

printf 'application\tmanual_median_ms\tfacade_median_ms\toverhead_percent\tstatus\n' >"$summary_report"

failures=0
for application in hello-jaxrs services aop; do
    if ! evaluate_application "$application"; then
        failures=$((failures + 1))
    fi
done

echo "Raw samples: $raw_root"
echo "Environment: $environment_report"
echo "Summary: $summary_report"

if ((failures > 0)); then
    echo "FAIL: facade compilation exceeded the 15% median budget for $failures application(s)" >&2
    exit 1
fi

echo "PASS: facade compilation medians are within 15% of all manual baselines"
