// SPDX-FileCopyrightText: 2026 Koivisto Capital Oy
// SPDX-License-Identifier: EUPL-1.2

package dev.vertique.examples.services;

import static io.restassured.RestAssured.given;
import static org.hamcrest.Matchers.equalTo;
import static org.hamcrest.Matchers.greaterThanOrEqualTo;

import com.atlassian.oai.validator.OpenApiInteractionValidator;
import com.atlassian.oai.validator.report.LevelResolver;
import com.atlassian.oai.validator.report.ValidationReport;
import com.atlassian.oai.validator.restassured.OpenApiValidationFilter;
import dev.vertique.application.test.VertiqueAppExtension;
import io.restassured.RestAssured;
import io.restassured.filter.log.RequestLoggingFilter;
import io.restassured.filter.log.ResponseLoggingFilter;
import io.vertx.core.json.JsonObject;
import java.util.concurrent.TimeUnit;
import org.junit.jupiter.api.*;
import org.junit.jupiter.api.extension.RegisterExtension;

/**
 * Integration tests for the user service using the real {@link UserServiceImpl}.
 *
 * <p>Tests are ordered to prevent the delete operation from affecting the list check.
 *
 * <p>The application is booted through {@link VertiqueAppExtension} using the factory generated by
 * the {@code @VertiqueApp} annotation processor — there is no {@code MainVerticle}. The extension
 * owns the awaited startup and teardown, eliminating the manual bootstrap dance and the
 * awaited-teardown footgun.
 */
@Timeout(value = 20, unit = TimeUnit.SECONDS)
@TestMethodOrder(MethodOrderer.OrderAnnotation.class)
class UserServiceIT {

    @RegisterExtension
    static final VertiqueAppExtension app = VertiqueAppExtension.forFactory(new AppComponentVertiqueComponentFactory())
            .withConfig(new JsonObject()
                    .put("http", new JsonObject().put("port", 0))
                    .put("management", new JsonObject().put("enabled", false)));

    @BeforeAll
    static void setUp() {
        String specUrl = UserServiceIT.class.getResource("/openapi.json").toString();
        OpenApiValidationFilter openApiFilter =
                new OpenApiValidationFilter(OpenApiInteractionValidator.createForSpecificationUrl(specUrl)
                        .withLevelResolver(LevelResolver.create()
                                .withLevel("validation.response.status.unknown", ValidationReport.Level.IGNORE)
                                .withLevel("validation.response.body.unexpected", ValidationReport.Level.IGNORE)
                                .withLevel("validation.request.security.missing", ValidationReport.Level.IGNORE)
                                .build())
                        .build());

        RestAssured.baseURI = "http://localhost";
        RestAssured.port = app.httpPort();
        RestAssured.filters(new RequestLoggingFilter(), new ResponseLoggingFilter(), openApiFilter);
    }

    @AfterAll
    static void tearDown() {
        RestAssured.reset();
    }

    @Test
    @Order(1)
    void shouldGetUserById() {
        given().when()
                .get("/users/1")
                .then()
                .statusCode(200)
                .body("id", equalTo("1"))
                .body("name", equalTo("Alice"))
                .body("email", equalTo("alice@example.com"));
    }

    @Test
    @Order(2)
    void shouldListUsers() {
        given().when().get("/users").then().statusCode(200).body("size()", greaterThanOrEqualTo(3));
    }

    @Test
    @Order(3)
    void shouldReturn404ForUnknownUser() {
        given().when().get("/users/999").then().statusCode(404);
    }

    @Test
    @Order(4)
    void shouldDeleteUser() {
        given().when().delete("/users/3").then().statusCode(204);
    }
}
