// SPDX-FileCopyrightText: 2026 Koivisto Capital Oy
// SPDX-License-Identifier: EUPL-1.2

package dev.vertique.examples.services;

import static io.restassured.RestAssured.given;
import static org.hamcrest.Matchers.equalTo;

import dev.vertique.application.test.VertiqueAppExtension;
import io.restassured.RestAssured;
import io.restassured.filter.log.RequestLoggingFilter;
import io.restassured.filter.log.ResponseLoggingFilter;
import io.vertx.core.json.JsonObject;
import java.util.concurrent.TimeUnit;
import org.junit.jupiter.api.*;
import org.junit.jupiter.api.extension.RegisterExtension;

/**
 * Integration tests for the user service using the sandbox ({@code sandboxEnabled=true}).
 *
 * <p>The application is booted through {@link VertiqueAppExtension} using the factory generated by
 * the {@code @VertiqueApp} annotation processor — there is no {@code MainVerticle}. The extension
 * owns the awaited startup and teardown, selecting the sandbox handler via {@code sandboxEnabled=true}
 * in the supplied config.
 */
@Timeout(value = 20, unit = TimeUnit.SECONDS)
class UserServiceSandboxIT {

    @RegisterExtension
    static final VertiqueAppExtension app = VertiqueAppExtension.forFactory(new AppComponentVertiqueComponentFactory())
            .withConfig(new JsonObject()
                    .put("http", new JsonObject().put("port", 0).put("host", "127.0.0.1"))
                    .put("sandboxEnabled", true)
                    .put("management", new JsonObject().put("enabled", false))
                    .put("resilience", ResilienceTestPolicies.probeConfig())
                    .put(
                            "rateLimit",
                            new JsonObject()
                                    .put(
                                            "policies",
                                            new JsonObject()
                                                    .put(
                                                            "rate-limit-probe-shared",
                                                            RateLimitTestPolicies.probeShared()))));

    @BeforeAll
    static void setUp() {
        RestAssured.baseURI = "http://127.0.0.1";
        RestAssured.port = app.httpPort();
        RestAssured.filters(new RequestLoggingFilter(), new ResponseLoggingFilter());
    }

    @AfterAll
    static void tearDown() {
        RestAssured.reset();
    }

    @Test
    void shouldReturnSandboxUser() {
        given().when()
                .get("/users/any-id")
                .then()
                .statusCode(200)
                .body("name", equalTo("Sandbox User"))
                .body("email", equalTo("sandbox@example.com"));
    }

    @Test
    void shouldReturnSandboxUserList() {
        given().when()
                .get("/users")
                .then()
                .statusCode(200)
                .body("size()", equalTo(2))
                .body("[0].name", equalTo("Sandbox Alice"));
    }
}
