<?xml version="1.0" encoding="UTF-8"?>
<!--
SPDX-FileCopyrightText: 2026 Koivisto Capital Oy
SPDX-License-Identifier: EUPL-1.2
-->

<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">

    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>dev.vertique</groupId>
        <artifactId>vertique-parent</artifactId>
        <version>${revision}</version>
        <relativePath>../pom.xml</relativePath>
    </parent>

    <artifactId>vertique-starter</artifactId>
    <packaging>pom</packaging>
    <name>Vertique Starter</name>
    <description>Starter aggregates that compose framework Dagger modules into supported application foundations</description>

    <modules>
        <module>vertique-starter-core</module>
        <module>vertique-starter-rest</module>
        <module>vertique-starter-services</module>
        <module>vertique-starter-postgresql</module>
        <module>vertique-starter-integration-tests</module>
    </modules>
</project>
