// SPDX-FileCopyrightText: 2026 Koivisto Capital Oy
// SPDX-License-Identifier: EUPL-1.2

package dev.vertique.json.schema;

import static java.util.concurrent.TimeUnit.MILLISECONDS;
import static java.util.concurrent.TimeUnit.SECONDS;
import static org.junit.jupiter.api.Assertions.assertAll;
import static org.junit.jupiter.api.Assertions.assertDoesNotThrow;
import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertThrows;
import static org.junit.jupiter.api.Assertions.assertTrue;
import static org.junit.jupiter.api.Assertions.fail;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.databind.PropertyName;
import com.fasterxml.jackson.databind.PropertyNamingStrategies;
import com.fasterxml.jackson.databind.introspect.Annotated;
import com.fasterxml.jackson.databind.introspect.AnnotatedMember;
import com.fasterxml.jackson.databind.introspect.JacksonAnnotationIntrospector;
import com.fasterxml.jackson.databind.json.JsonMapper;
import dev.vertique.core.json.JsonMapperProfile;
import dev.vertique.core.json.JsonProfileId;
import dev.vertique.json.JsonMapperProfiles;
import io.swagger.v3.oas.annotations.media.Schema;
import java.lang.management.ManagementFactory;
import java.lang.management.ThreadInfo;
import java.lang.management.ThreadMXBean;
import java.lang.reflect.Type;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import java.util.concurrent.CountDownLatch;
import java.util.concurrent.FutureTask;
import java.util.concurrent.atomic.AtomicBoolean;
import java.util.concurrent.locks.LockSupport;
import java.util.function.Supplier;
import java.util.stream.Stream;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.Arguments;
import org.junit.jupiter.params.provider.MethodSource;

/**
 * {@link AnnotationJsonSchemaGenerator#outputRenames(Type)} reports every member reachable from an
 * output-direction generator's schema whose published schema property name differs from the name
 * Jackson serializes, ordered by declaring type and then member, empty when none; it refuses every
 * generator not built by {@code forOutputProfile}, and keeps {@code generateCanonical}'s accepted
 * type grammar, failure contract, per-instance lock, and per-instance restore behavior.
 */
class OutputRenameReportTest {

    /** Bounded wait for an event the lock-ordering row requires; a timeout fails the row. */
    private static final long AWAIT_SECONDS = 10L;

    /**
     * Under the snake-case profile, Jackson serializes {@code firstName} as {@code first_name}, but
     * {@code @Schema(name = "label")} publishes it as {@code label}.
     */
    static final class SnakeCaseLabel {
        @Schema(name = "label")
        public String firstName;
    }

    /**
     * A bare {@code @JsonProperty} names nothing, so Jackson serializes {@code code} under its own
     * name while {@code @Schema(name = "label")} publishes it as {@code label}.
     */
    static final class BareJsonPropertyAndLabel {
        @JsonProperty
        @Schema(name = "label")
        public String code;
    }

    /**
     * A {@code @JsonProperty} naming the member itself does not take precedence either: Jackson
     * serializes {@code code}, and {@code @Schema(name = "label")} publishes it as {@code label}.
     */
    static final class SelfNamedJsonPropertyAndLabel {
        @JsonProperty("code")
        @Schema(name = "label")
        public String code;
    }

    /** No {@code @Schema} override at all: the only rename is Jackson's own {@code @JsonProperty}. */
    static final class JsonPropertyRenameOnly {
        @JsonProperty("wire")
        public String code;
    }

    /**
     * A non-empty {@code @JsonProperty} naming a different name takes precedence: despite
     * {@code @Schema(name = "label")}, the schema publishes {@code wire}, the name Jackson serializes.
     */
    static final class WireAndLabel {
        @JsonProperty("wire")
        @Schema(name = "label")
        public String code;
    }

    /**
     * Generated by the caller the lock-ordering row holds inside the generator's lock: its one field
     * is renamed, so a recording open while that generation publishes it would take the rename.
     */
    static final class HeldRename {
        @Schema(name = "held-out")
        public String held;
    }

    /** No annotation at all: the snake-case mapper alone names the property, so both names agree. */
    record UnannotatedSnakeCaseName(String firstName) {}

    /**
     * Declares its two renamed fields in reverse alphabetical member-name order, and with schema
     * names ("a-out", "b-out") that sort opposite the member-name order the report requires ("first"
     * before "second"): passing the schema library's own schema-name-ordered visit order off as the
     * report's sorted order would turn the ordering assertion red.
     */
    static final class Alpha {
        @Schema(name = "a-out")
        public String second;

        @Schema(name = "b-out")
        public String first;
    }

    /** Reached once, through a {@code List<Beta>} member of {@link Envelope}. */
    static final class Beta {
        @Schema(name = "delta-out")
        public String delta;
    }

    /**
     * A generic member type reached twice from {@link Envelope}, under two different type arguments
     * ({@code Box<String>} and {@code Box<Integer>}): the schema library visits its one renamed field
     * once per instantiation, but type-argument erasure keeps it the same {@link
     * java.lang.reflect.Member}, so dropping deduplication would report it twice.
     */
    static final class Box<T> {
        @Schema(name = "v-out")
        public T value;
    }

    /**
     * The root type: its own renamed field (schema name "aaa-out", sorting before every {@link Alpha}
     * schema name), two members reaching {@link Alpha} (so it is reached twice and must be reported
     * once), one member reaching {@link Beta} through a list element, and two members reaching {@link
     * Box} under different type arguments (so it too is reached twice and must be reported once).
     */
    static final class Envelope {
        @Schema(name = "aaa-out")
        public String zeta;

        public Alpha alphaOne;
        public List<Beta> betas;
        public Alpha alphaTwo;
        public Box<String> boxOfString;
        public Box<Integer> boxOfInteger;
    }

    private static final JsonMapperProfile PROFILE =
            JsonMapperProfiles.of(JsonProfileId.of("output-rename-report-test"), new ObjectMapper());

    private static final JsonMapperProfile SNAKE_CASE_PROFILE = JsonMapperProfiles.of(
            JsonProfileId.of("output-rename-report-test-snake-case"),
            new ObjectMapper().setPropertyNamingStrategy(PropertyNamingStrategies.SNAKE_CASE));

    @Test
    @DisplayName("A property renamed away from its serialized name is reported, and generateCanonical's output is"
            + " unaffected by the call")
    void reportsAPropertyRenamedAwayFromItsSerializedName() {
        AnnotationJsonSchemaGenerator generator = AnnotationJsonSchemaGenerator.forOutputProfile(PROFILE);
        AnnotationJsonSchemaGenerator snakeCaseGenerator =
                AnnotationJsonSchemaGenerator.forOutputProfile(SNAKE_CASE_PROFILE);

        assertAll(
                () -> assertRenameReported(
                        generator,
                        SchemaRenameCollisionTest.FallbackToOwnPropertyAndRenameWithoutCollision.class,
                        List.of(new OutputRename(
                                SchemaRenameCollisionTest.FallbackToOwnPropertyAndRenameWithoutCollision.class
                                        .getName(),
                                "note",
                                "note",
                                "y"))),
                () -> assertRenameReported(
                        snakeCaseGenerator,
                        SnakeCaseLabel.class,
                        List.of(new OutputRename(SnakeCaseLabel.class.getName(), "firstName", "first_name", "label"))),
                () -> assertRenameReported(
                        generator,
                        BareJsonPropertyAndLabel.class,
                        List.of(new OutputRename(BareJsonPropertyAndLabel.class.getName(), "code", "code", "label"))),
                () -> assertRenameReported(
                        generator,
                        SelfNamedJsonPropertyAndLabel.class,
                        List.of(new OutputRename(
                                SelfNamedJsonPropertyAndLabel.class.getName(), "code", "code", "label"))));
    }

    @ParameterizedTest(name = "{0}")
    @MethodSource("agreeingNameCases")
    @DisplayName("Nothing is reported where the schema name equals the serialized name, once the fixture is shown to"
            + " actually publish the property")
    void reportsNothingWhereSchemaAndSerializedNamesAgree(
            String label, JsonMapperProfile profile, Class<?> type, String publishedProperty) {
        AnnotationJsonSchemaGenerator generator = AnnotationJsonSchemaGenerator.forOutputProfile(profile);
        String json = generator.generateCanonical(type);

        assertAll(
                label,
                () -> assertTrue(
                        publishedPropertyNames(json).contains(publishedProperty),
                        () -> label + ": the fixture must actually publish \"" + publishedProperty + "\": " + json),
                () -> assertEquals(List.of(), generator.outputRenames(type)));
    }

    private static Stream<Arguments> agreeingNameCases() {
        return Stream.of(
                Arguments.of(
                        "a Lombok-style boolean field whose rename lands on its own accessor pair's property",
                        PROFILE,
                        SchemaRenameCollisionTest.BooleanIsFieldAlignedWithItsAccessors.class,
                        "active"),
                Arguments.of(
                        "a prefixed field whose rename lands on its own accessor pair's property",
                        PROFILE,
                        SchemaRenameCollisionTest.PrefixedFieldAlignedWithItsAccessors.class,
                        "name"),
                Arguments.of(
                        "a rename onto the member's own name",
                        PROFILE,
                        SchemaRenameCollisionTest.RenamedOntoItself.class,
                        "x"),
                Arguments.of(
                        "a snake-case component renamed onto its own snake-case name",
                        SNAKE_CASE_PROFILE,
                        SchemaRenameCollisionTest.ComponentRenamedToItsOwnSnakeCaseName.class,
                        "first_name"),
                Arguments.of(
                        "an unannotated field whose snake-case serialized name already matches",
                        SNAKE_CASE_PROFILE,
                        UnannotatedSnakeCaseName.class,
                        "first_name"),
                Arguments.of(
                        "a rename via @JsonProperty only, with no Swagger name override",
                        PROFILE,
                        JsonPropertyRenameOnly.class,
                        "wire"),
                Arguments.of(
                        "a non-empty @JsonProperty naming a different name, which takes precedence over"
                                + " @Schema(name)",
                        PROFILE,
                        WireAndLabel.class,
                        "wire"));
    }

    @Test
    @DisplayName("Every reachable rename is reported once, ordered by declaring type and then member, including a"
            + " generic member reached under two different type arguments")
    void reportsEveryReachableRenameOnceInOrder() {
        AnnotationJsonSchemaGenerator generator = AnnotationJsonSchemaGenerator.forOutputProfile(PROFILE);
        List<OutputRename> expected = List.of(
                rename(Alpha.class, "first", "first", "b-out"),
                rename(Alpha.class, "second", "second", "a-out"),
                rename(Beta.class, "delta", "delta", "delta-out"),
                rename(Box.class, "value", "value", "v-out"),
                rename(Envelope.class, "zeta", "zeta", "aaa-out"));

        List<OutputRename> actual = generator.outputRenames(Envelope.class);
        String json = generator.generateCanonical(Envelope.class);
        Set<String> published = publishedPropertyNames(json);

        assertAll(
                () -> assertEquals(expected, actual),
                () -> assertTrue(
                        expected.stream().allMatch(entry -> published.contains(entry.schemaName())),
                        () -> "every reported schemaName must be a published property of " + json));
    }

    private static OutputRename rename(
            Class<?> declaringType, String member, String serializedName, String schemaName) {
        return new OutputRename(declaringType.getName(), member, serializedName, schemaName);
    }

    @ParameterizedTest(name = "{0}")
    @MethodSource("constructionModes")
    @DisplayName("Only a forOutputProfile generator answers outputRenames; every other construction mode refuses"
            + " with IllegalStateException")
    void refusesAGeneratorThatIsNotOutputDirection(
            String label, Supplier<AnnotationJsonSchemaGenerator> factory, boolean refuses) {
        AnnotationJsonSchemaGenerator generator = factory.get();

        if (refuses) {
            assertThrows(
                    IllegalStateException.class,
                    () -> generator.outputRenames(
                            SchemaRenameCollisionTest.FallbackToOwnPropertyAndRenameWithoutCollision.class),
                    label);
        } else {
            assertDoesNotThrow(
                    () -> generator.outputRenames(
                            SchemaRenameCollisionTest.FallbackToOwnPropertyAndRenameWithoutCollision.class),
                    label);
        }
    }

    private static Stream<Arguments> constructionModes() {
        return Stream.of(
                Arguments.of(
                        "an input-direction generator refuses",
                        (Supplier<AnnotationJsonSchemaGenerator>)
                                () -> AnnotationJsonSchemaGenerator.forInputProfile(PROFILE),
                        true),
                Arguments.of(
                        "a Victools-defaults generator refuses",
                        (Supplier<AnnotationJsonSchemaGenerator>) AnnotationJsonSchemaGenerator::withVictoolsDefaults,
                        true),
                Arguments.of(
                        "an output-direction generator answers",
                        (Supplier<AnnotationJsonSchemaGenerator>)
                                () -> AnnotationJsonSchemaGenerator.forOutputProfile(PROFILE),
                        false));
    }

    /** Reflected on to obtain an unresolved {@link java.lang.reflect.TypeVariable}. */
    @SuppressWarnings("unused")
    private static <T> T genericMethodForATypeVariableFixture() {
        return null;
    }

    @Test
    @DisplayName("outputRenames keeps generateCanonical's accepted type grammar and bounded failure contract, and"
            + " leaves no residual state on the instance after either failure")
    void keepsTheGeneratorsFailureContract() throws NoSuchMethodException {
        AnnotationJsonSchemaGenerator generator = AnnotationJsonSchemaGenerator.forOutputProfile(PROFILE);
        Type typeVariable = OutputRenameReportTest.class
                .getDeclaredMethod("genericMethodForATypeVariableFixture")
                .getGenericReturnType();

        // Failure kind 1: outside generateCanonical's accepted Type grammar.
        JsonSchemaGenerationException typeVariableFailure =
                assertThrows(JsonSchemaGenerationException.class, () -> generator.outputRenames(typeVariable));
        assertTrue(
                typeVariableFailure.getMessage().contains("unresolved type variable"),
                typeVariableFailure.getMessage());

        // Failure kind 2: the existing rename-collision refusal, naming the same type and member that
        // generateCanonical's own pinned refusal for this fixture names (SchemaRenameCollisionTest).
        JsonSchemaGenerationException collisionFailure = assertThrows(
                JsonSchemaGenerationException.class,
                () -> generator.outputRenames(SchemaRenameCollisionTest.RenamedOntoVisibleProperty.class));
        String message = collisionFailure.getMessage();
        String expectedType = SchemaRenameCollisionTest.RenamedOntoVisibleProperty.class.getTypeName();
        assertAll(
                () -> assertTrue(message.contains(expectedType), message),
                () -> assertTrue(message.contains("\"note\""), message),
                () -> assertTrue(message.contains("\"wire\""), message),
                () -> assertTrue(message.contains("@JsonProperty"), message));

        // Reuse: the two aborted calls above must leave no residual state on this instance — its later
        // results equal a fresh instance's.
        List<OutputRename> reusedRenames =
                generator.outputRenames(SchemaRenameCollisionTest.FallbackToOwnPropertyAndRenameWithoutCollision.class);
        String reusedSchema = generator.generateCanonical(
                SchemaRenameCollisionTest.FallbackToOwnPropertyAndRenameWithoutCollision.class);
        AnnotationJsonSchemaGenerator fresh = AnnotationJsonSchemaGenerator.forOutputProfile(PROFILE);
        assertAll(
                () -> assertEquals(
                        fresh.outputRenames(
                                SchemaRenameCollisionTest.FallbackToOwnPropertyAndRenameWithoutCollision.class),
                        reusedRenames),
                () -> assertEquals(
                        fresh.generateCanonical(
                                SchemaRenameCollisionTest.FallbackToOwnPropertyAndRenameWithoutCollision.class),
                        reusedSchema));
    }

    @Test
    @DisplayName("outputRenames takes the instance lock before it opens its recording: a report waiting behind"
            + " another type's generation on the same instance holds only its own type's renames")
    void takesTheLockBeforeOpeningItsRecording() throws Exception {
        Class<?> reportedType = SchemaRenameCollisionTest.FallbackToOwnPropertyAndRenameWithoutCollision.class;
        // The held type's rename is real: a recording open while its generation publishes it takes it.
        assertEquals(
                List.of(rename(HeldRename.class, "held", "held", "held-out")),
                AnnotationJsonSchemaGenerator.forOutputProfile(PROFILE).outputRenames(HeldRename.class));

        GatingIntrospector gate = new GatingIntrospector();
        AnnotationJsonSchemaGenerator generator = AnnotationJsonSchemaGenerator.forOutputProfile(JsonMapperProfiles.of(
                JsonProfileId.of("output-rename-report-test-gated"),
                JsonMapper.builder().annotationIntrospector(gate).build()));
        FutureTask<String> heldGeneration = new FutureTask<>(() -> generator.generateCanonical(HeldRename.class));
        FutureTask<List<OutputRename>> report = new FutureTask<>(() -> generator.outputRenames(reportedType));
        Thread heldCaller = new Thread(heldGeneration, "output-rename-report-test-held-generation");
        Thread reportCaller = new Thread(report, "output-rename-report-test-report");
        heldCaller.setDaemon(true);
        reportCaller.setDaemon(true);
        try {
            heldCaller.start();
            assertTrue(
                    gate.entered.await(AWAIT_SECONDS, SECONDS),
                    "the held generation never reached the gate inside the generator's lock");
            reportCaller.start();
            awaitBlockedOnAMonitorHeldBy(reportCaller, heldCaller);
        } finally {
            gate.release.countDown();
        }

        List<OutputRename> reported = report.get(AWAIT_SECONDS, SECONDS);
        String heldSchema = heldGeneration.get(AWAIT_SECONDS, SECONDS);
        assertAll(
                () -> assertEquals(List.of(rename(reportedType, "note", "note", "y")), reported),
                () -> assertTrue(
                        publishedPropertyNames(heldSchema).contains("held-out"),
                        () -> "the held generation must publish its renamed property: " + heldSchema),
                () -> assertTrue(gate.releasedByTheTest, "the gate timed out instead of being released by the test"));
    }

    /**
     * Waits, bounded, until {@code waiter} is blocked entering a monitor {@code owner} holds: the
     * generator's lock, which the report's call enters before anything else.
     */
    private static void awaitBlockedOnAMonitorHeldBy(Thread waiter, Thread owner) {
        ThreadMXBean threads = ManagementFactory.getThreadMXBean();
        long deadline = System.nanoTime() + SECONDS.toNanos(AWAIT_SECONDS);
        while (true) {
            Thread.State state = waiter.getState();
            ThreadInfo info = threads.getThreadInfo(waiter.threadId());
            boolean waiting = state == Thread.State.BLOCKED || state == Thread.State.WAITING;
            if (waiting && info != null && info.getLockOwnerId() == owner.threadId()) {
                return;
            }
            if (System.nanoTime() - deadline > 0) {
                fail(waiter.getName() + " never blocked on a monitor " + owner.getName() + " holds; its state is "
                        + state);
            }
            LockSupport.parkNanos(MILLISECONDS.toNanos(1));
        }
    }

    /**
     * The profile mapper's annotation introspector, parking the first serialization-name lookup of a
     * {@link HeldRename} member until the test releases it. The schema library and the output name
     * resolver both introspect a type's serialization names while generating it, inside the
     * generator's lock and before either publishes one of its members, so the caller that reaches the
     * gate is held inside the lock with the rename not yet published.
     */
    private static final class GatingIntrospector extends JacksonAnnotationIntrospector {
        private final CountDownLatch entered = new CountDownLatch(1);
        private final CountDownLatch release = new CountDownLatch(1);
        private final AtomicBoolean armed = new AtomicBoolean(true);
        private volatile boolean releasedByTheTest = true;

        @Override
        public PropertyName findNameForSerialization(Annotated annotated) {
            if (annotated instanceof AnnotatedMember member
                    && member.getDeclaringClass() == HeldRename.class
                    && armed.compareAndSet(true, false)) {
                entered.countDown();
                try {
                    releasedByTheTest = release.await(AWAIT_SECONDS * 2, SECONDS);
                } catch (InterruptedException interrupted) {
                    Thread.currentThread().interrupt();
                    releasedByTheTest = false;
                }
            }
            return super.findNameForSerialization(annotated);
        }
    }

    private static void assertRenameReported(
            AnnotationJsonSchemaGenerator generator, Class<?> type, List<OutputRename> expected) {
        String before = generator.generateCanonical(type);
        List<OutputRename> actual = generator.outputRenames(type);
        String after = generator.generateCanonical(type);
        Set<String> published = publishedPropertyNames(before);

        assertEquals(expected, actual);
        assertEquals(before, after, "outputRenames must not change what generateCanonical later publishes");
        assertTrue(
                expected.stream().allMatch(entry -> published.contains(entry.schemaName())),
                () -> "every reported schemaName must be a published property of " + before);
    }

    /**
     * The keys of every {@code properties} object anywhere in {@code json}: the root's, every nested
     * schema's, and every {@code $defs} entry's.
     */
    private static Set<String> publishedPropertyNames(String json) {
        JsonNode document;
        try {
            document = new ObjectMapper().readTree(json);
        } catch (JsonProcessingException notJson) {
            throw new AssertionError("the generated schema is not JSON: " + json, notJson);
        }
        Set<String> names = new HashSet<>();
        collectPropertyNames(document, names);
        return names;
    }

    private static void collectPropertyNames(JsonNode node, Set<String> names) {
        if (node.isObject()) {
            JsonNode properties = node.get("properties");
            if (properties != null && properties.isObject()) {
                properties.fieldNames().forEachRemaining(names::add);
            }
        }
        for (JsonNode child : node) {
            collectPropertyNames(child, names);
        }
    }
}
