// SPDX-FileCopyrightText: 2026 Koivisto Capital Oy
// SPDX-License-Identifier: EUPL-1.2

package dev.vertique.examples.websocket;

import static org.junit.jupiter.api.Assertions.*;

import com.fasterxml.jackson.databind.ObjectMapper;
import dev.vertique.application.test.VertiqueAppExtension;
import dev.vertique.examples.websocket.chat.ChatEvent;
import dev.vertique.examples.websocket.chat.ChatMessage;
import dev.vertique.rest.auth.jwt.JwtAuthFactory;
import dev.vertique.rest.websocket.transport.WebSocketUpgradeException;
import dev.vertique.rest.websocket.transport.WebSocketUpgradeExceptions;
import dev.vertique.rest.websocket.transport.WebSocketUpgradeRejected;
import dev.vertique.rest.websocket.transport.WebSocketUpgradeTransportFailure;
import io.vertx.core.Future;
import io.vertx.core.http.WebSocket;
import io.vertx.core.http.WebSocketClient;
import io.vertx.core.http.WebSocketConnectOptions;
import io.vertx.core.json.JsonArray;
import io.vertx.core.json.JsonObject;
import io.vertx.core.json.jackson.DatabindCodec;
import io.vertx.ext.auth.jwt.JWTAuth;
import io.vertx.junit5.Checkpoint;
import io.vertx.junit5.VertxExtension;
import io.vertx.junit5.VertxTestContext;
import java.util.List;
import java.util.concurrent.TimeUnit;
import java.util.concurrent.atomic.AtomicBoolean;
import org.junit.jupiter.api.*;
import org.junit.jupiter.api.extension.ExtendWith;
import org.junit.jupiter.api.extension.RegisterExtension;

/**
 * Black-box integration test for the WebSocket chat room example.
 *
 * <p>Boots the application via {@link VertiqueAppExtension} (using the factory generated by the
 * {@code @VertiqueApp} annotation processor) on a random port, issues HS256 JWT tokens from the
 * same symmetric key used by {@link AppModule}, and verifies wire-level behaviour: JWT-gated
 * upgrade, welcome frame on connect, broadcast fan-out to room peers, room isolation, and clean
 * close.
 */
@Timeout(value = 20, unit = TimeUnit.SECONDS)
@ExtendWith(VertxExtension.class)
public class WebSocketChatIT {

    @RegisterExtension
    static final VertiqueAppExtension app = VertiqueAppExtension.forFactory(new AppComponentVertiqueComponentFactory())
            .withConfig(new JsonObject()
                    .put("http", new JsonObject().put("port", 0).put("host", "127.0.0.1"))
                    .put("management", new JsonObject().put("enabled", false)));

    private static JWTAuth jwtAuth;
    private static WebSocketClient wsClient;
    // Use the shared Vert.x mapper which already has Instant serialization support via VertxModule.
    private static final ObjectMapper mapper = DatabindCodec.mapper();

    @BeforeAll
    static void setUp() {
        jwtAuth = JwtAuthFactory.fromSymmetricKey(app.vertx(), "HS256", AppModule.DEMO_JWT_SECRET);
        wsClient = app.vertx().createWebSocketClient();
    }

    @AfterAll
    static void tearDown() {
        if (wsClient != null) {
            wsClient.close();
        }
    }

    // --- Helpers ---

    /**
     * Generates an HS256 JWT with the given subject and roles.
     *
     * @param sub   token subject
     * @param roles roles to include in the {@code roles} claim
     * @return signed JWT string
     */
    private String token(String sub, String... roles) {
        JsonObject claims = new JsonObject().put("sub", sub).put("roles", new JsonArray(List.of(roles)));
        return jwtAuth.generateToken(claims);
    }

    /**
     * Opens a WebSocket connection to the given room using the provided bearer token.
     *
     * @param room  room identifier used as the path parameter
     * @param token bearer token for the Authorization header
     * @return future that completes with the connected {@link WebSocket}
     */
    private Future<WebSocket> connect(String room, String token) {
        WebSocketConnectOptions opts = new WebSocketConnectOptions()
                .setHost("127.0.0.1")
                .setPort(app.httpPort())
                .setURI("/ws/chat/" + room)
                .addHeader("Authorization", "Bearer " + token);
        return wsClient.connect(opts);
    }

    /**
     * Parses a JSON text frame into a {@link ChatEvent}. Throws {@link AssertionError} on failure.
     *
     * @param msg raw JSON string from the WebSocket
     * @return the deserialized {@link ChatEvent}
     */
    private ChatEvent parseEvent(String msg) {
        try {
            return mapper.readValue(msg, ChatEvent.class);
        } catch (Exception e) {
            throw new AssertionError("failed to parse ChatEvent: " + msg, e);
        }
    }

    // --- Tests ---

    @Test
    @DisplayName("missing Bearer token → upgrade rejected")
    void missingTokenRejectedWith401(VertxTestContext ctx) {
        WebSocketConnectOptions opts = new WebSocketConnectOptions()
                .setHost("127.0.0.1")
                .setPort(app.httpPort())
                .setURI("/ws/chat/general");

        wsClient.connect(opts).onComplete(ctx.failing(err -> {
            ctx.verify(() -> {
                // Translate the raw transport exception into the framework-typed family so we
                // assert against framework-owned types instead of pattern-matching on raw
                // Netty/Vert.x classes (see rest-websocket transport package).
                WebSocketUpgradeException upgradeErr = WebSocketUpgradeExceptions.translate(err);
                if (upgradeErr instanceof WebSocketUpgradeRejected rejected) {
                    assertEquals(401, rejected.status(), "expected 401, got status=" + rejected.status());
                } else {
                    // The server closed the socket mid-handshake before the status line could
                    // be parsed (typical under CI scheduler load). Still proof of rejection;
                    // the precise status is just not recoverable in this case.
                    assertInstanceOf(WebSocketUpgradeTransportFailure.class, upgradeErr);
                }
            });
            ctx.completeNow();
        }));
    }

    @Test
    @DisplayName("valid token → connect succeeds; first frame is welcome ChatEvent")
    void validTokenReceivesWelcomeFrame(VertxTestContext ctx) {
        String tk = token("alice", "chat:connect");

        connect("welcome-room", tk).onComplete(ctx.succeeding(ws -> {
            ws.textMessageHandler(msg -> {
                ctx.verify(() -> {
                    ChatEvent evt;
                    try {
                        evt = mapper.readValue(msg, ChatEvent.class);
                    } catch (Exception e) {
                        throw new AssertionError("failed to parse ChatEvent: " + msg, e);
                    }
                    assertEquals("welcome", evt.type(), "first frame must be welcome event");
                });
                ws.close();
                ctx.completeNow();
            });
        }));
    }

    @Test
    @DisplayName("two clients in same room: A sends message, B receives broadcast ChatEvent")
    void broadcastBetweenPeers(VertxTestContext ctx) {
        String tkA = token("alice", "chat:connect");
        String tkB = token("bob", "chat:connect");

        // Connect both clients simultaneously; set up handlers only after both are connected
        // (avoids the race where a welcome arrives before the handler is registered).
        Checkpoint bGotMessage = ctx.checkpoint();

        Future<WebSocket> futureA = connect("peer-room", tkA);
        Future<WebSocket> futureB = connect("peer-room", tkB);

        Future.all(futureA, futureB).onComplete(ctx.succeeding(cf -> {
            WebSocket wsA = futureA.result();
            WebSocket wsB = futureB.result();

            // Both are connected; set up message handlers. Welcomes may have already
            // arrived, so we send immediately without waiting for the welcome frame.
            wsB.textMessageHandler(msg -> {
                ctx.verify(() -> {
                    ChatEvent evt = parseEvent(msg);
                    if ("message".equals(evt.type())) {
                        assertEquals("alice", evt.author());
                        assertEquals("hi", evt.text());
                        bGotMessage.flag();
                    }
                    // welcome frames are silently ignored here
                });
            });

            // Drain any pending welcomes from the buffer then send.
            sendChatMessage(wsA, "alice", "hi", ctx);
        }));
    }

    /**
     * Writes a {@link ChatMessage} JSON frame to the given WebSocket. Fails the test context on error.
     *
     * @param ws     the sender WebSocket
     * @param author message author
     * @param text   message body
     * @param ctx    test context for failure propagation
     */
    private void sendChatMessage(WebSocket ws, String author, String text, VertxTestContext ctx) {
        try {
            ws.writeTextMessage(mapper.writeValueAsString(new ChatMessage(author, text)));
        } catch (Exception ex) {
            ctx.failNow(ex);
        }
    }

    @Test
    @DisplayName("path-param isolation: message in room A is not received in room B")
    void pathParamIsolation(VertxTestContext ctx) {
        String tkA = token("alice", "chat:connect");
        String tkB = token("bob", "chat:connect");

        AtomicBoolean aGotBroadcast = new AtomicBoolean(false);

        Future<WebSocket> futureA = connect("iso-room-a", tkA);
        Future<WebSocket> futureB = connect("iso-room-b", tkB);

        Future.all(futureA, futureB).onComplete(ctx.succeeding(cf -> {
            WebSocket wsA = futureA.result();
            WebSocket wsB = futureB.result();

            // B's handler: welcome frames are silently ignored; any "message" frame is a
            // violation of room isolation. We do not gate the test on B's welcome — that
            // races with handler registration in slower CI environments.
            wsB.textMessageHandler(msg -> ctx.verify(() -> {
                ChatEvent evt = parseEvent(msg);
                if ("message".equals(evt.type())) {
                    ctx.failNow(new AssertionError("isolation violated: B received A's message"));
                }
            }));

            // A's handler: welcome is ignored; on the first "message" frame (A's own broadcast)
            // start a 200ms quiet window. If isolation held, B will not have failed the context
            // by the time the timer fires; we then close both sockets and complete.
            wsA.textMessageHandler(msg -> ctx.verify(() -> {
                ChatEvent evt = parseEvent(msg);
                if ("message".equals(evt.type()) && aGotBroadcast.compareAndSet(false, true)) {
                    // Use app.vertx() — the WebSocket connections run on the app's Vert.x
                    // instance (Vert.x-B), not VertxExtension's lazy instance (Vert.x-A).
                    app.vertx().setTimer(200L, id -> Future.all(wsA.close(), wsB.close())
                            .onComplete(v -> ctx.completeNow()));
                }
            }));

            // Send immediately after both peers are connected. Pending welcome frames are
            // already buffered on both sides and are filtered out by the handlers above.
            sendChatMessage(wsA, "alice", "room-a-only", ctx);
        }));
    }

    @Test
    @DisplayName("after client A closes, broadcast in room C still succeeds")
    void closeAndContinuedBroadcast(VertxTestContext ctx) {
        String tkA = token("alice", "chat:connect");
        String tkC = token("carol", "chat:connect");

        Checkpoint cGotMessage = ctx.checkpoint();

        connect("close-room-a", tkA).onComplete(ctx.succeeding(wsA -> {
            wsA.textMessageHandler(msg -> {
                ctx.verify(() -> {
                    ChatEvent evt = parseEvent(msg);
                    if ("welcome".equals(evt.type())) {
                        // A joined; close A and start C independently.
                        wsA.close();
                    }
                });
            });

            connect("close-room-c", tkC).onComplete(ctx.succeeding(wsC -> {
                AtomicBoolean cWelcomeReceived = new AtomicBoolean(false);
                wsC.textMessageHandler(msg -> {
                    ctx.verify(() -> {
                        ChatEvent evt = parseEvent(msg);
                        if ("welcome".equals(evt.type()) && cWelcomeReceived.compareAndSet(false, true)) {
                            // C sends to its own room; A's close must not affect this.
                            sendChatMessage(wsC, "carol", "after-close", ctx);
                            return;
                        }
                        if ("message".equals(evt.type())) {
                            assertEquals("carol", evt.author());
                            cGotMessage.flag();
                        }
                    });
                });
            }));
        }));
    }
}
