// SPDX-FileCopyrightText: 2026 Koivisto Capital Oy
// SPDX-License-Identifier: EUPL-1.2

package dev.vertique.examples.db;

import static io.restassured.RestAssured.given;
import static org.hamcrest.Matchers.equalTo;
import static org.hamcrest.Matchers.greaterThanOrEqualTo;
import static org.hamcrest.Matchers.notNullValue;

import com.atlassian.oai.validator.OpenApiInteractionValidator;
import com.atlassian.oai.validator.report.LevelResolver;
import com.atlassian.oai.validator.report.ValidationReport;
import com.atlassian.oai.validator.restassured.OpenApiValidationFilter;
import dev.vertique.application.test.VertiqueAppExtension;
import dev.vertique.db.test.PostgresContainer;
import io.restassured.RestAssured;
import io.restassured.filter.log.RequestLoggingFilter;
import io.restassured.filter.log.ResponseLoggingFilter;
import io.restassured.http.ContentType;
import io.vertx.core.json.JsonObject;
import java.util.concurrent.TimeUnit;
import org.junit.jupiter.api.AfterAll;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.MethodOrderer;
import org.junit.jupiter.api.Order;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.TestMethodOrder;
import org.junit.jupiter.api.Timeout;
import org.junit.jupiter.api.extension.RegisterExtension;

/**
 * Integration tests for the Items REST API.
 *
 * <p>Boots the full application through {@link VertiqueAppExtension} (using the factory generated by
 * the {@code @VertiqueApp} annotation processor) against a Testcontainers PostgreSQL database, and
 * verifies all CRUD operations via HTTP using REST Assured. Tests are ordered to exercise the
 * create &rarr; read &rarr; list &rarr; update &rarr; delete lifecycle in sequence.
 *
 * <p><strong>Container ordering.</strong> The PostgreSQL container is started in a static
 * initializer, and the application config is built from the running container at static-init time,
 * <em>before</em> the {@link VertiqueAppExtension} field is constructed. Static field/initializer
 * order therefore guarantees the container is up and {@link #CONFIG} holds its mapped jdbc/pool
 * settings before the extension's {@code beforeAll} boots the app — whose {@code MIGRATE}-phase
 * Flyway step connects to the container during startup. The container does <em>not</em> run
 * migrations itself ({@code withMigration()} is intentionally omitted); the application's
 * {@code MIGRATE} step runs Flyway ({@code flyway.mode=MIGRATE}), exercising the runner's migration
 * phase end to end.
 */
@Timeout(value = 20, unit = TimeUnit.SECONDS)
@TestMethodOrder(MethodOrderer.OrderAnnotation.class)
public class ItemResourceIT {

    static final PostgresContainer db = new PostgresContainer().withDatabaseName("example_db");

    static {
        db.start();
    }

    static final JsonObject CONFIG = buildConfig();

    @RegisterExtension
    static final VertiqueAppExtension app = VertiqueAppExtension.forFactory(new AppComponentVertiqueComponentFactory())
            .withConfig(CONFIG);

    private static String createdId;

    /**
     * Builds the application config from the running container: the {@code db} pool settings point
     * at the container, and {@code flyway.mode=MIGRATE} drives the application's {@code MIGRATE}-phase
     * step to apply the migrations (the Flyway runner falls back to the {@code db} credentials and
     * host/port/database for the migration connection).
     *
     * @return the root application config
     */
    private static JsonObject buildConfig() {
        return new JsonObject()
                .put("http", new JsonObject().put("port", 0))
                .put(
                        "db",
                        new JsonObject()
                                .put("host", db.toPoolConfig().host())
                                .put("port", db.toPoolConfig().port())
                                .put("database", db.toPoolConfig().database())
                                .put("user", db.toPoolConfig().user())
                                .put("password", db.toPoolConfig().password()))
                .put("flyway", new JsonObject().put("mode", "MIGRATE"))
                .put("management", new JsonObject().put("enabled", false));
    }

    @BeforeAll
    static void setUp() {
        String specUrl = ItemResourceIT.class.getResource("/openapi.json").toString();
        OpenApiValidationFilter openApiFilter =
                new OpenApiValidationFilter(OpenApiInteractionValidator.createForSpecificationUrl(specUrl)
                        .withLevelResolver(LevelResolver.create()
                                .withLevel("validation.response.status.unknown", ValidationReport.Level.IGNORE)
                                .withLevel("validation.response.body.unexpected", ValidationReport.Level.IGNORE)
                                .withLevel("validation.request.security.missing", ValidationReport.Level.IGNORE)
                                .withLevel("validation.response.contentType.notAllowed", ValidationReport.Level.IGNORE)
                                .withLevel(
                                        "validation.response.body.schema.additionalProperties",
                                        ValidationReport.Level.IGNORE)
                                .build())
                        .build());

        RestAssured.baseURI = "http://localhost";
        RestAssured.port = app.httpPort();
        RestAssured.filters(new RequestLoggingFilter(), new ResponseLoggingFilter(), openApiFilter);
    }

    @AfterAll
    static void tearDown() {
        RestAssured.reset();
        db.close();
    }

    @Test
    @Order(1)
    void shouldCreateItem() {
        createdId = given().contentType(ContentType.JSON)
                .body(new JsonObject()
                        .put("name", "Widget")
                        .put("description", "A test widget")
                        .encode())
                .when()
                .post("/items")
                .then()
                .statusCode(201)
                .body("name", equalTo("Widget"))
                .body("description", equalTo("A test widget"))
                .body("id", notNullValue())
                .extract()
                .path("id");
    }

    @Test
    @Order(2)
    void shouldGetItemById() {
        given().when()
                .get("/items/" + createdId)
                .then()
                .statusCode(200)
                .body("name", equalTo("Widget"))
                .body("id", equalTo(createdId));
    }

    @Test
    @Order(3)
    void shouldListItems() {
        given().when()
                .get("/items")
                .then()
                .statusCode(200)
                .body("size()", greaterThanOrEqualTo(1))
                .body("[0].name", equalTo("Widget"));
    }

    @Test
    @Order(4)
    void shouldUpdateItem() {
        given().contentType(ContentType.JSON)
                .body(new JsonObject()
                        .put("name", "Updated Widget")
                        .put("description", "Updated desc")
                        .encode())
                .when()
                .put("/items/" + createdId)
                .then()
                .statusCode(200)
                .body("name", equalTo("Updated Widget"))
                .body("description", equalTo("Updated desc"));
    }

    @Test
    @Order(5)
    void shouldDeleteItem() {
        given().when().delete("/items/" + createdId).then().statusCode(204);
    }

    @Test
    @Order(6)
    void shouldReturn404ForDeletedItem() {
        given().when().get("/items/" + createdId).then().statusCode(404);
    }

    @Test
    void shouldReturn404ForNonExistentItem() {
        given().when().get("/items/00000000-0000-0000-0000-000000000000").then().statusCode(404);
    }

    @Test
    void shouldReturn400ForInvalidUuid() {
        given().when().get("/items/not-a-uuid").then().statusCode(400);
    }

    @Test
    void shouldReturn400ForMissingName() {
        given().contentType(ContentType.JSON)
                .body(new JsonObject().put("description", "No name").encode())
                .when()
                .post("/items")
                .then()
                .statusCode(400);
    }

    // -- Pagination tests --

    @Test
    @Order(10)
    void shouldReturnFirstPageWithPagination() {
        // Create 3 items with sorted names
        createItem("Alpha", "First item");
        createItem("Bravo", "Second item");
        createItem("Charlie", "Third item");

        // Request first page with pageSize=2
        var response = given().queryParam("pageSize", "2")
                .when()
                .get("/items/page")
                .then()
                .statusCode(200)
                .body("items.size()", equalTo(2))
                .body("items[0].name", equalTo("Alpha"))
                .body("items[1].name", equalTo("Bravo"))
                .body("nextCursorToken", notNullValue())
                .body("previousCursorToken", org.hamcrest.Matchers.nullValue())
                .extract();

        // Follow next cursor to get page 2
        String nextCursor = response.path("nextCursorToken");
        given().queryParam("cursor", nextCursor)
                .queryParam("pageSize", "2")
                .when()
                .get("/items/page")
                .then()
                .statusCode(200)
                .body("items.size()", greaterThanOrEqualTo(1))
                .body("items[0].name", equalTo("Charlie"))
                .body("previousCursorToken", notNullValue());
    }

    @Test
    @Order(11)
    void shouldReturnEmptyPageWhenNoItems() {
        // Delete all items first
        var items = given().when().get("/items").then().extract().jsonPath().getList("id", String.class);
        for (String id : items) {
            given().when().delete("/items/" + id);
        }

        given().queryParam("pageSize", "10")
                .when()
                .get("/items/page")
                .then()
                .statusCode(200)
                .body("items.size()", equalTo(0))
                .body("nextCursorToken", org.hamcrest.Matchers.nullValue())
                .body("previousCursorToken", org.hamcrest.Matchers.nullValue());
    }

    @Test
    void shouldReturn400ForInvalidCursor() {
        given().queryParam("cursor", "not-valid-cursor!@#")
                .when()
                .get("/items/page")
                .then()
                .statusCode(400);
    }

    @Test
    void shouldReturn400ForInvalidPageSize() {
        given().queryParam("pageSize", "0").when().get("/items/page").then().statusCode(400);
    }

    @Test
    void shouldReturn400ForPageSizeTooLarge() {
        given().queryParam("pageSize", "500")
                .when()
                .get("/items/page")
                .then()
                .statusCode(400)
                .body("detail", equalTo("pageSize 500 is out of range [1, 100]"))
                .body("requestedPageSize", equalTo(500))
                .body("minPageSize", equalTo(1))
                .body("maxPageSize", equalTo(100));
    }

    @Test
    @Order(12)
    void shouldOverrideCursorPageSizeWithQueryParam() {
        // Create items if needed
        createItem("Delta", "Fourth item");
        createItem("Echo", "Fifth item");

        // Get first page with pageSize=1 (creates cursor with embedded size 1)
        var response = given().queryParam("pageSize", "1")
                .when()
                .get("/items/page")
                .then()
                .statusCode(200)
                .body("items.size()", equalTo(1))
                .body("nextCursorToken", notNullValue())
                .extract();

        // Follow cursor with overridden pageSize=10 (overrides embedded size of 1)
        String nextCursor = response.path("nextCursorToken");
        given().queryParam("cursor", nextCursor)
                .queryParam("pageSize", "10")
                .when()
                .get("/items/page")
                .then()
                .statusCode(200)
                .body("items.size()", greaterThanOrEqualTo(1));
    }

    @Test
    @Order(13)
    void shouldUseCursorEmbeddedSizeWhenPageSizeAbsent() {
        // Create items
        createItem("Foxtrot", "Sixth item");
        createItem("Golf", "Seventh item");

        // Get first page with pageSize=1
        var response = given().queryParam("pageSize", "1")
                .when()
                .get("/items/page")
                .then()
                .statusCode(200)
                .body("items.size()", equalTo(1))
                .body("nextCursorToken", notNullValue())
                .extract();

        // Follow cursor WITHOUT pageSize param — should use cursor's embedded size (1)
        String nextCursor = response.path("nextCursorToken");
        given().queryParam("cursor", nextCursor)
                .when()
                .get("/items/page")
                .then()
                .statusCode(200)
                .body("items.size()", equalTo(1));
    }

    private static void createItem(String name, String description) {
        given().contentType(ContentType.JSON)
                .body(new JsonObject()
                        .put("name", name)
                        .put("description", description)
                        .encode())
                .when()
                .post("/items");
    }
}
