// SPDX-FileCopyrightText: 2026 Koivisto Capital Oy
// SPDX-License-Identifier: EUPL-1.2

package dev.vertique.examples.localization;

import static io.restassured.RestAssured.given;
import static org.hamcrest.Matchers.equalTo;

import dev.vertique.application.test.VertiqueAppExtension;
import io.restassured.RestAssured;
import io.restassured.filter.log.RequestLoggingFilter;
import io.restassured.filter.log.ResponseLoggingFilter;
import io.vertx.core.json.JsonArray;
import io.vertx.core.json.JsonObject;
import java.util.concurrent.TimeUnit;
import org.junit.jupiter.api.*;
import org.junit.jupiter.api.extension.RegisterExtension;

/**
 * Integration tests verifying end-to-end inbound locale negotiation.
 *
 * <p>Boots the application via {@link VertiqueAppExtension} (using the factory generated by the
 * {@code @VertiqueApp} annotation processor). Three cases are tested against {@code GET /locale}:
 * <ol>
 *   <li>Header {@code Accept-Language: sv-SE} → negotiated locale is {@code sv},
 *       source is {@code rest-accept-language}.</li>
 *   <li>Query parameter {@code ?lang=fi} with header {@code Accept-Language: sv-SE} → negotiated
 *       locale is {@code fi}, source is {@code query-param} (custom source C12 wins).</li>
 *   <li>No {@code Accept-Language}, no {@code ?lang=} → negotiated locale is {@code en}
 *       (configured default), source is {@code default-locale}.</li>
 * </ol>
 */
@Timeout(value = 20, unit = TimeUnit.SECONDS)
public class LocaleResourceIT {

    @RegisterExtension
    static final VertiqueAppExtension app = VertiqueAppExtension.forFactory(new AppComponentVertiqueComponentFactory())
            .withConfig(new JsonObject()
                    .put("http", new JsonObject().put("port", 0).put("host", "127.0.0.1"))
                    .put("management", new JsonObject().put("enabled", false))
                    .put(
                            "localization",
                            new JsonObject()
                                    .put("defaultLocale", "en")
                                    .put("defaultZone", "UTC")
                                    .put(
                                            "supportedLocales",
                                            new JsonArray().add("en").add("sv").add("fi"))));

    @BeforeAll
    static void setUp() {
        RestAssured.baseURI = "http://127.0.0.1";
        RestAssured.port = app.httpPort();
        RestAssured.filters(new RequestLoggingFilter(), new ResponseLoggingFilter());
    }

    @AfterAll
    static void tearDown() {
        RestAssured.reset();
    }

    @Test
    @DisplayName("Accept-Language header sv-SE resolves to sv via rest-accept-language source")
    void shouldResolveLocaleFromAcceptLanguageHeader() {
        given().header("Accept-Language", "sv-SE")
                .when()
                .get("/locale")
                .then()
                .statusCode(200)
                .body("languageTag", equalTo("sv"))
                .body("localeSource", equalTo("rest-accept-language"));
    }

    @Test
    @DisplayName("?lang=fi with Accept-Language sv-SE resolves to fi via query-param source (C12)")
    void shouldPreferQueryParamOverAcceptLanguageHeader() {
        given().header("Accept-Language", "sv-SE")
                .queryParam("lang", "fi")
                .when()
                .get("/locale")
                .then()
                .statusCode(200)
                .body("languageTag", equalTo("fi"))
                .body("localeSource", equalTo("query-param"));
    }

    @Test
    @DisplayName("No Accept-Language and no ?lang= falls back to configured default locale en")
    void shouldFallBackToDefaultLocaleWhenNoHintProvided() {
        given().when()
                .get("/locale")
                .then()
                .statusCode(200)
                .body("languageTag", equalTo("en"))
                .body("localeSource", equalTo("default-locale"));
    }
}
